yes
mate-academy/layout_catalog pull request #1000
Opened 2021-07-19 16:27 UTC by technoloverbaby

2021-07-20 11:38 UTC, vkryvytskyy requested changes

2021-07-20 11:38 UTC, vkryvytskyy commented on src/styles/blocks/catalog.scss
> +  box-sizing: border-box;
Укажи это для всех элементов на странице, через селектор *

2021-07-20 11:38 UTC, vkryvytskyy commented on src/styles/blocks/catalog.scss
> +  padding: 32px 20px 40px;
Укажи вертикальные и горизонтальные паддингы для самой карточки

2021-07-20 11:38 UTC, vkryvytskyy commented on src/styles/blocks/header.scss
> +  .navLink.is-active::after {
```suggestion
  .is-active::after {
```
Думаю хватит просто .is-active

2021-07-20 11:38 UTC, vkryvytskyy commented on src/styles/blocks/header.scss
> +  }
Используй scss вложенность

2021-07-20 11:38 UTC, vkryvytskyy commented on src/styles/blocks/header.scss
> +  .navLink.is-active::after {
![image](https://user-images.githubusercontent.com/38065883/126317528-53858bab-89c8-4a2b-8bec-8b9f79fb9815.png)
Она должна быть на границе хедера

2021-07-20 11:38 UTC, vkryvytskyy commented on src/styles/blocks/header.scss
> +    font-size: 12px;
Добавь ссылкам line-height равный высоте хедера, чтобы увеличить кликабельную зону

2021-07-26 12:00 UTC, vkryvytskyy requested changes

2021-07-26 12:00 UTC, vkryvytskyy commented on src/index.html
> +                  >
Не надо использовать svg здесь, переиспользуй код из layout__stars, где звезды были заданы через background

2021-07-27 09:51 UTC, mykola-yarchuk submitted a review, later dismissed

2021-07-27 09:51 UTC, mykola-yarchuk commented on src/index.html
> +        data-qa="hover"
```suggestion
          data-qa="hover"
```

2021-07-27 09:51 UTC, mykola-yarchuk commented on src/index.html
> +          <img src="images/logo.png" alt="logo img">
```suggestion
          <img src="images/logo.png" alt="moyo logo img">
```

2021-07-27 09:51 UTC, mykola-yarchuk commented on src/styles/blocks/catalog.scss
> +.catalog {
обмеж максимальну ширину щоб карточки не могли стояти 5 в ряд
![image](https://user-images.githubusercontent.com/35385361/127133714-7c75560b-d6b8-4b7c-bff2-8eaca573807a.png)
винеси ширину карточки, ширину відступу між карточками в змінні і вираховуй максимальну ширину 4* ширна карточки + 3* ширина відступу, можна ще винести кількість карточок в змінну

2021-07-27 09:51 UTC, mykola-yarchuk commented on src/styles/blocks/header.scss
> +  /* #endregion */
![image](https://user-images.githubusercontent.com/35385361/127133905-b7d074bd-7435-4286-97c1-50147bd8acd2.png)
в кінці кожного файлу повинен бути пустий рядок налаштуй свій редактор так щоб він ставив його автоматично або перевіряй перед відправкою вручну

2021-07-27 09:51 UTC, mykola-yarchuk commented on src/styles/blocks/catalog.scss
> +  margin-top: 50px;
.catalog це блок, блоку не можна задавати зовнішні відступи, якщо хочеш задати відступи створи або обгортку і задай там падінги, або додай до каталогу ще один клас який буде описувати поведінку каталогу як елемента іншого блоку і там уже можна задавати відступи

2021-07-30 12:48 UTC, vkryvytskyy requested changes

2021-07-30 12:48 UTC, vkryvytskyy commented on readme.md
> +- [TEST REPORT LINK](https://technoloverbaby.github.io/layout_catalog/report/html_report/)
![image](https://user-images.githubusercontent.com/38065883/127654929-b0a0fd80-aaf8-4a86-b44a-81126b55e801.png)
У меня что-то не все соответствует дизайну(это в firefox)

2021-07-30 12:48 UTC, vkryvytskyy commented on readme.md
> +- [TEST REPORT LINK](https://technoloverbaby.github.io/layout_catalog/report/html_report/)
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/38065883/127655083-a131995d-d684-48ce-bd46-ca3686344bf5.png">
Почему у тебя контент залезает на паддинги карточки?

2021-07-30 12:48 UTC, vkryvytskyy commented on src/styles/blocks/catalog.scss
> +  padding-right: 16px;
Задай боковые паддинги один раз для всей карточки

2021-07-31 15:24 UTC, technoloverbaby commented on readme.md
> +- [TEST REPORT LINK](https://technoloverbaby.github.io/layout_catalog/report/html_report/)
Не знаю как возможно исправить

2021-08-03 11:27 UTC, vpolets approved these changes

2022-10-11 08:04 UTC, closed without merging