solution 1th
mate-academy/layout_catalog pull request #1015
Opened 2021-08-18 12:23 UTC by VikaShkomar

[DEMO LINK](https://VikaShkomar.github.io/layout_catalog/)
TEST REPORT LINK](https://VikaShkomar.github.io/layout_catalog/report/html_report/)

2021-08-19 14:17 UTC, vkryvytskyy requested changes
![image](https://user-images.githubusercontent.com/38065883/130084334-fe6380db-a4f4-49d0-82a4-b2a2b35ea3c3.png)
Текст в меню меньше чем должен быть

2021-08-19 14:17 UTC, vkryvytskyy commented on src/index.html
> +               class="logo2">
```suggestion
          <img 
            src="./images/logo.png"
            alt="Logo"
            class="logo"
          >
```
Почему logo2?

2021-08-19 14:17 UTC, vkryvytskyy commented on src/index.html
> +            <h1 class="card__product-name">Моноблок APPLE A1419 iMac<br>27" Retina 5K (MNED2UA/A)</h1>
Используй h2, h1 обычно 1-2 на всю страницу

2021-08-19 14:17 UTC, vkryvytskyy commented on src/index.html
> +        <div class="card card--3" data-qa="card">
```suggestion
        <div class="card" data-qa="card">
```
Зачем тут card--3?
Используй `nth-child` если надо

2021-08-19 14:17 UTC, vkryvytskyy commented on src/styles/main.scss
> +@import "./blocks/card.scss";
В PR не добавились все файлы со стилями, добавь их

2021-08-20 08:50 UTC, VikaShkomar commented on src/styles/main.scss
> +@import "./blocks/card.scss";
Не получается добавить, не знаю как

2021-08-21 11:32 UTC, vkryvytskyy commented on src/styles/main.scss
> +@import "./blocks/card.scss";
https://stackoverflow.com/questions/2419249/how-can-i-stage-and-commit-all-files-including-newly-added-files-using-a-singl

2021-08-21 11:33 UTC, vkryvytskyy requested changes

2021-08-21 11:33 UTC, vkryvytskyy commented on src/index.html
> +            <p class="card__product-name">Моноблок APPLE A1419 iMac<br>27" Retina 5K (MNED2UA/A)</p>
Используй тег заголовка(h2, h3 и так далее)

2021-08-23 19:27 UTC, vpolets approved these changes

2023-06-02 14:36 UTC, closed without merging