some message
mate-academy/layout_catalog pull request #1026
Opened 2021-08-22 13:31 UTC by perronogrande

- [DEMO LINK](https://perronogrande.github.io/layout_catalog/)
- [TEST REPORT LINK](https://perronogrande.github.io/layout_catalog/report/html_report/)

A MEESAGE TO MENTOR:
so I added div to an active link in nav because it kept telling me that a tag cannot have 2 classes. it's weird, because in other tasks there wasn't such a problem. also, it doesn't pass the tests because of minor differences that to be honest would take a lot of time to find a fix. it's graphically the same though.

2021-08-24 20:53 UTC, AndreyMalyshev147 requested changes
Убери отступ и расскажи мне лично, что это за класс)
Ошибкой посчитать не могу, поскольку интересно)

2021-08-24 20:53 UTC, AndreyMalyshev147 commented on src/styles/main.scss
> +
Лишний отступ
```suggestion
```

2021-08-24 20:53 UTC, AndreyMalyshev147 commented on src/styles/main.scss
> +  &s {
Что это за класс такой?)

2021-08-25 12:02 UTC, perronogrande commented on src/styles/main.scss
> +  &s {
это типо cards)). есть card, а есть cards, который их обьеденяет

2021-08-25 12:15 UTC, AndreyMalyshev147 approved these changes
Great work!

2021-08-25 13:35 UTC, aliceblunt8 requested changes

2021-08-25 13:35 UTC, aliceblunt8 commented on src/index.html
> +          </li>
> add class is-active to the first link (Apple) in navigation
```suggestion
          <li class="nav__item">
              <a class="nav__link is-active" href="">APPLE</a>
          </li>
```

2021-08-25 13:35 UTC, aliceblunt8 commented on src/index.html
> +            <p class="price__value">69 999 грн</p>
```suggestion
          <div class="card__price">
            <h3 class="card__price-title">Цена:</h3>
            <p class="card__price-value">69 999 грн</p>
```

2021-08-25 13:35 UTC, aliceblunt8 commented on src/index.html
> +          <button data-qa="card-hover" class="button">КУПИТЬ</button>
```suggestion
          <button data-qa="card-hover" class="card__button">
            КУПИТЬ
          </button>
```

2021-08-25 13:35 UTC, aliceblunt8 commented on src/index.html
> +        <div class="card" data-qa="card">
attribute data-qa="card" should be added only to the first card

2021-08-25 13:35 UTC, aliceblunt8 commented on src/styles/main.scss
> +  &s {
we don't do such thing in scss, move cards to the separate class above card itself

2021-08-25 13:35 UTC, aliceblunt8 commented on src/styles/main.scss
> +  font-family: Roboto, sans-serif;
remove, you've already added to html
```suggestion
```

2021-08-25 13:35 UTC, aliceblunt8 commented on src/styles/main.scss
> +    font-family: Roboto, sans-serif;
same

2021-08-25 13:35 UTC, aliceblunt8 commented on src/styles/main.scss
> +    font-family: Roboto, sans-serif;
same

2021-08-25 13:35 UTC, aliceblunt8 commented on src/styles/main.scss
> +  font-family: Roboto, sans-serif;
same

2023-05-10 08:41 UTC, closed without merging