Develop
mate-academy/layout_catalog pull request #1126
Opened 2021-10-14 03:34 UTC by voronvasia

Підскажіть, будь ласка, бо не можу зрозуміти що не так з активною ссилкою...

2021-10-14 03:35 UTC, voronvasia commented
https://voronvasia.github.io/layout_catalog/
https://voronvasia.github.io/layout_catalog/report/html_report/

2021-10-14 03:35 UTC, voronvasia commented
> Підскажіть, будь ласка, бо не можу зрозуміти що не так з активною ссилкою...

https://voronvasia.github.io/layout_catalog/
https://voronvasia.github.io/layout_catalog/report/html_report/

2021-10-17 22:41 UTC, vkryvytskyy requested changes

2021-10-17 22:41 UTC, vkryvytskyy commented on readme.md
> +- [DEMO LINK](https://voronvasia.github.io/layout_catalog/)
https://user-images.githubusercontent.com/38065883/137647412-817b7fcf-1d40-4998-9e41-c0f01fd23a76.mov

Тень у хедера выглядит не так, как должна

2021-10-17 22:41 UTC, vkryvytskyy commented on src/index.html
> +            >
```suggestion
            <a class="menu__link" href="#">
```
Если у тега меньше трех атрибутов - можно записывать вот так

2021-10-17 22:41 UTC, vkryvytskyy commented on src/styles/blocks/menu.scss
> +      // transform: translateX(-50%);
Комментарии можно удалить

2021-10-18 02:40 UTC, voronvasia commented
исправил тень, но тест не проходит, что то не так с активной ссылкой в хедере, не могу понять что не так

2021-10-19 09:25 UTC, danylo-onishchuk approved these changes
В целом не страшно, что там пару пикселей не сходится

2023-12-09 20:16 UTC, closed without merging