Catalog
mate-academy/layout_catalog pull request #1154
Opened 2021-10-20 16:02 UTC by Veronika-Korona

- [DEMO LINK](https://veronika-korona.github.io/layout_catalog/)
- [TEST REPORT LINK](https://veronika-korona.github.io/layout_catalog/report/html_report/)

2021-10-21 08:59 UTC, IrynaHerasymchuk commented on src/index.html
> +      <span>
Not sure that you need this span tag, it works fine without it

2021-10-21 09:07 UTC, IrynaHerasymchuk commented on src/index.html
> +      <div class="product">
I think that you can add this class to <main> so you wouldn't have one extra div

2021-10-21 09:16 UTC, IrynaHerasymchuk commented on src/index.html
> +            >
Just fix indentation here
```suggestion
            <a
              href="#toBuy"
              data-qa="card-hover"
              class="product-card__button"
            >
```

2021-10-21 09:22 UTC, IrynaHerasymchuk commented on src/index.html
> +          <div class="product-card product-card--margin-right">
Did you use this --margin-right modificator? Couldn't find it in styles

2021-10-21 09:33 UTC, IrynaHerasymchuk commented on src/styles/blocks/stars.scss
> +    background-image: url(../images/star-active.svg);
You can use SASS @for loop here

2021-10-21 09:34 UTC, IrynaHerasymchuk commented on src/styles/html.scss
> +}
You can also move this to reset.scss :)

2021-10-21 09:36 UTC, IrynaHerasymchuk reviewed
Overall pretty good, just pay attention to formatting

2021-10-21 16:29 UTC, ihor-jpeg requested changes
Good work! There are a few fixes to be made

2021-10-21 16:29 UTC, ihor-jpeg commented on src/index.html
> +          <li class="nav__item"><a class="nav__link" href="#samsung">SAMSUNG</a></li>
```suggestion
          <li class="nav__item">
            <a class="nav__link" href="#samsung">
              SAMSUNG
            </a>
          </li>
```

2021-10-21 16:29 UTC, ihor-jpeg commented on src/styles/blocks/nav.scss
> +    display: block;
display here is not necessary

2021-10-21 16:29 UTC, ihor-jpeg commented on src/styles/blocks/nav.scss
> +    width: 100%;
if you set `right: 0; left: 0;`, it will take 100% of the width automatically

2021-10-21 16:29 UTC, ihor-jpeg commented on src/styles/blocks/product-card.scss
> +    font-weight: 400;
400 is the default value

2021-10-22 08:52 UTC, ihor-jpeg approved these changes
Good work!

2025-01-07 19:24 UTC, closed without merging