solution to catalog
mate-academy/layout_catalog pull request #1206
Opened 2021-11-23 14:22 UTC by mykola-koval

- [DEMO LINK](https://mykola-koval.github.io/layout_catalog/)
- [TEST REPORT LINK](https://mykola-koval.github.io/layout_catalog/report/html_report/)

2021-11-25 08:43 UTC, ArtemTopolskyi requested changes

2021-11-25 08:43 UTC, ArtemTopolskyi commented on src/index.html
> +          alt="moyo"
```suggestion
          alt="Moyo logotype"
```

2021-11-25 08:43 UTC, ArtemTopolskyi commented on src/index.html
> +          alt=""
do not left alt attribute empty

2021-11-25 08:43 UTC, ArtemTopolskyi commented on src/index.html
> +      </div>
```suggestion
        >
          Купить
        </a>
      </div>
```

2021-11-25 08:43 UTC, ArtemTopolskyi commented on src/styles/blocks/header.scss
> +.nav {
these styles must be in separate 'nav.scss' file

2021-11-25 10:34 UTC, mykola-koval commented
npm run deploy seems not working
any ideas?

2021-11-26 09:04 UTC, ArtemTopolskyi approved these changes

2022-12-19 11:07 UTC, closed without merging