tests does not approve my solution
mate-academy/layout_catalog pull request #1208
Opened 2021-11-23 14:54 UTC by Bohdan-Maksymiuk

- [DEMO LINK](https://Bohdan-Maksymiuk.github.io/layout_catalog/)
- [TEST REPORT LINK](https://Bohdan-Maksymiuk.github.io/layout_catalog/report/html_report/)

2021-11-23 17:19 UTC, HrynykNataliia requested changes

2021-11-23 17:19 UTC, HrynykNataliia commented on src/styles/blocks/nav.scss
> +    margin: 0;
move margin and padding to _reset.scss

2021-11-23 17:19 UTC, HrynykNataliia commented on src/styles/blocks/nav.scss
> +    list-style: none;
you already have list-style: none in nav__list

2021-11-23 17:19 UTC, HrynykNataliia commented on src/styles/blocks/nav.scss
> +.is-active {
it is a block
so move it to another file

2021-11-23 17:19 UTC, HrynykNataliia commented on src/styles/blocks/catalog.scss
> +  }
it is duplicate

2021-11-23 17:41 UTC, Bohdan-Maksymiuk commented on src/styles/blocks/nav.scss
> +.is-active {
is-active більше модифікатор ніж блок.
Проте його в завданні просили вказати окремим класом, а не модифікатором

2021-11-23 17:55 UTC, HrynykNataliia commented on src/styles/blocks/nav.scss
> +.is-active {
окей, погоджуюсь

2021-11-23 17:55 UTC, HrynykNataliia approved these changes

2021-11-24 05:57 UTC, Bohdan-Maksymiuk commented
злетів reset країв списку в навігації в демці на github, проте на локальному хості і в тестах норм

2021-11-24 09:47 UTC, ArtemTopolskyi approved these changes
Looks good :rocket:

2022-12-15 11:27 UTC, closed without merging