Catalog
mate-academy/layout_catalog pull request #1215
Opened 2021-11-23 19:28 UTC by marina-tilniak

- [DEMO LINK](https://marina-tilniak.github.io/layout_catalog/)
- [TEST REPORT LINK](https://marina-tilniak.github.io/layout_catalog/report/html_report/)

2021-11-25 07:08 UTC, Denchepornyuk requested changes
good job 👍

2021-11-25 07:08 UTC, Denchepornyuk commented on src/index.html
> +      <nav class="header__nav nav">
якщо ти не стилізуєш header__nav то його не потрібно прописувати

2021-11-25 07:08 UTC, Denchepornyuk commented on src/styles/blocks/card.scss
> +  }
для  display: flex; краще створити mixin або palceholder і використовувати його в кожного з цих селекторів

2021-11-25 11:52 UTC, Denchepornyuk approved these changes

2022-09-13 20:27 UTC, marina-tilniak reviewed
<input type="text">

2023-05-23 12:26 UTC, sTorba24 approved these changes
So nice work! Approve for science :)

2025-06-09 17:16 UTC, closed without merging