Add solution
mate-academy/layout_catalog pull request #125
Opened 2019-07-31 13:27 UTC by amserhii11

- [UPDATE DEMO LINK](https://amserhii11.github.io/layout_catalog/)
- [UPDATE TEST REPORT LINK](https://amserhii11.github.io/layout_catalog/report/html_report/)

2019-07-31 14:46 UTC, irenhh requested changes
Check every line of your code and correct indentations where necessary

2019-07-31 14:46 UTC, irenhh commented on src/index.html
> +      <img src="./images/logo.png" alt="logotype">
will you understand if somebody says you 'logotype'? what could it mean...

2019-07-31 14:46 UTC, irenhh commented on src/style.css
> +  font-style: normal;
why font-style normal???

2019-07-31 14:46 UTC, irenhh commented on src/style.css
> +  padding: 0;
you already reseted paddings

2019-08-01 10:36 UTC, danheim approved these changes
Please, look at the comments.

2019-08-01 10:36 UTC, danheim commented on src/index.html
> +    <a href="#" class="logo">
indent

2019-08-01 10:36 UTC, danheim commented on src/index.html
> +            <h1 class="product-name"> Моноблок APPLE A1419 iMac 27" Retina 5K (MNED2UA/A) </h1>
```suggestion
            <h2 class="product-name"> Моноблок APPLE A1419 iMac 27" Retina 5K (MNED2UA/A) </h2>
```

2019-08-01 10:36 UTC, danheim commented on src/index.html
> +            Отзывов: 5
indent

2019-08-01 10:36 UTC, danheim commented on src/style.css
> +  font-family: "Roboto", sans-serif;
brackets not necessary

2025-09-02 14:50 UTC, closed without merging