develop
mate-academy/layout_catalog pull request #1264
Opened 2021-12-28 16:30 UTC by trtskvalerie

- [DEMO LINK](https://trtskvalerie.github.io/layout_catalog/)
- [TEST REPORT LINK](https://trtskvalerie.github.io/layout_catalog/report/html_report/)

2021-12-28 20:28 UTC, Vonatlus requested changes
Код очень акуратно и грамотно написан, но:
 1. page width is always >= 1024px, и как следствие
 2. there should always be 4 cards in a row (not 2, 3 or 5)

2021-12-28 20:28 UTC, Vonatlus commented on src/styles/blocks/nav.scss
> +
лишний пробел между двумя свойствами блочной модели

2021-12-28 20:28 UTC, Vonatlus commented on src/styles/blocks/page.scss
> +
лишний пробел между двумя свойствами блочной модели

2021-12-28 20:28 UTC, Vonatlus commented on src/styles/blocks/product-card.scss
> +
лишний пробел между двумя свойствами блочной модели

2021-12-29 12:41 UTC, Vonatlus approved these changes

2021-12-29 14:05 UTC, OleksiiBlezniuk requested changes
Хорошая работа, но не для всех цветов использовала переменные, исправь пожалуйста 🙂

2021-12-29 16:34 UTC, OleksiiBlezniuk approved these changes
Good job!

2024-03-17 12:23 UTC, closed without merging