title was created
mate-academy/layout_catalog pull request #1277
Opened 2021-12-29 22:04 UTC by maksym-mishchanchuk

Попередня збірка. SCSS ще не розбитий на блоки, хочу попередню оцінку помилок

2021-12-30 15:34 UTC, jursylian approved these changes
Очень хорошая работа!! Молодец!

2021-12-30 15:34 UTC, jursylian commented on src/index.html
> +             href="#" data-qa="card-hover hover"
можно убрать просто `hover`

2021-12-30 15:34 UTC, jursylian commented on src/index.html
> +          <a class="card-block__buy" href="#" data-qa="hover">
тут можно убрать `data-qa=hover` и в других местах, мы добавляем только внутри 1 карточки.

2021-12-30 15:34 UTC, jursylian commented on src/index.html
> +              data-qa="hover"
здесь также можно убрать, могут не пройти тесты из за лишних `data-qa`

2021-12-30 15:34 UTC, jursylian commented on src/index.html
> +          <a class="card-block__buy" href="#" data-qa="hover">
здесь тоже лучше убрать  `data-qa`

2021-12-30 15:34 UTC, jursylian commented on src/index.html
> +              data-qa="hover"
и здесь.

2021-12-30 15:34 UTC, jursylian commented on src/index.html
> +          <a class="card-block__buy" href="#" data-qa="hover">
и здесь

2021-12-30 15:34 UTC, jursylian commented on src/index.html
> +              data-qa="hover"
и тут)

2021-12-30 15:34 UTC, jursylian commented on src/index.html
> +          <a class="card-block__buy" href="#" data-qa="hover">
и тут можно)

2021-12-30 15:34 UTC, jursylian commented on src/index.html
> +              data-qa="hover"
и конечно здесь..

2021-12-30 15:34 UTC, jursylian commented on src/index.html
> +          <a class="card-block__buy" href="#" data-qa="hover">
и тут

2021-12-30 15:34 UTC, jursylian commented on src/index.html
> +              data-qa="hover"
и тут

2021-12-30 15:34 UTC, jursylian commented on src/index.html
> +          <a class="card-block__buy" href="#" data-qa="hover">
то есть нужно оставить `data-qa` атрибуты только для 1 карточки

2021-12-30 15:34 UTC, jursylian commented on src/index.html
> +              data-qa="hover"
здесь тоже

2021-12-30 16:27 UTC, OleksiiBlezniuk requested changes

2021-12-30 16:27 UTC, OleksiiBlezniuk commented on src/styles/blocks/card-block.scss
> +    margin-bottom: 16px;
Это значение часто используется, вынеси его в переменную

2021-12-30 16:27 UTC, OleksiiBlezniuk commented on src/styles/blocks/card-block.scss
> +    line-height: 18px;
Это значение часто используется, вынеси его в переменную

2021-12-30 16:27 UTC, OleksiiBlezniuk commented on src/styles/blocks/nav.scss
> +    font-family: Roboto, sans-serif;
Ты ведь уже подключаешь шрифт к тегу  body, не нужно дублировать

2021-12-30 16:27 UTC, OleksiiBlezniuk commented on src/styles/blocks/stars.scss
> +    height: 16px;
Можно вынести в миксин и использовать в logo

2021-12-30 16:27 UTC, OleksiiBlezniuk commented on src/styles/blocks/card-block.scss
> +    color: #fff;
Используй переменную для цветов

2021-12-31 09:17 UTC, OleksiiBlezniuk approved these changes
Good job!

2021-12-31 09:17 UTC, OleksiiBlezniuk commented on src/styles/utils/_variables.scss
> +$margin-bottom-crd-block: 16px;
Можно было дать не настолько точное название переменной, не дублировать её и использовать везде, где было указано такое значение

2023-07-17 19:27 UTC, closed without merging