done
mate-academy/layout_catalog pull request #1386
Opened 2022-02-22 13:09 UTC by misha200119

- [DEMO LINK](https://misha200119.github.io/layout_catalog/)
- [TEST REPORT LINK](https://misha200119.github.io/layout_catalog/report/html_report/)

2022-02-22 14:35 UTC, KostiaO commented on src/styles/main.scss
> +  gap: 4px;
gap не читается тестом

2022-02-22 14:39 UTC, KostiaO requested changes
просто используй margin вместо gap, а так все норм

2022-02-23 07:23 UTC, misha200119 commented on src/styles/main.scss
> +  &__buy-link:hover {
I desided do that like this because i think it simplify of code reading, but ok, i'll do that

2022-02-23 07:26 UTC, misha200119 commented on src/styles/main.scss
> +  gap: 4px;
i have some bugs with tests last 2 my projects and anyway it don't pass tests... also more correctly do like that

2022-02-23 22:12 UTC, MaksimusCRS requested changes

2022-02-23 22:12 UTC, MaksimusCRS commented on src/styles/main.scss
> +      border: 1px solid #00acdc;
зачем тут рамочку добавлять, что поменялось с предыдущего задания?

2022-02-23 22:12 UTC, MaksimusCRS commented on src/styles/main.scss
> -body {
Для каждого блока должен быть отдельный файл

2022-03-09 11:13 UTC, illiarerun requested changes
few more fixes left:

2022-03-09 11:13 UTC, illiarerun commented on src/index.html
> +      <a href="index.html" class="header__logoImage" alt="MOYO logo"></a>
three attributes in one line, you should fix it

2022-03-09 11:13 UTC, illiarerun commented on src/index.html
> +              </div>
you can fit it in one line, actually

2022-03-09 11:13 UTC, illiarerun commented on src/styles/blocks/cards.scss
> +  width: 1024px;
Don't hardcode width, checklist 11th item, use max-width with formula to calculate it

2022-03-09 11:13 UTC, illiarerun commented on src/styles/blocks/goods-card.scss
> +  margin-bottom: 46px;
don't add margins to a block, use mix for it (create a cards__card element)

2022-03-09 11:13 UTC, illiarerun commented on src/styles/blocks/goods-card.scss
> +.stars {
create file for this block, too

2022-03-09 11:13 UTC, illiarerun commented on src/styles/blocks/goods-card.scss
> +.stars--5 > :nth-child(-n+5) {
you can use loop here

2022-03-09 11:13 UTC, illiarerun commented on src/styles/blocks/nav.scss
> +  &__link {
add some spaces here to improve readability

2022-03-09 11:13 UTC, illiarerun commented on src/styles/main.scss
>  }
?

2022-03-09 11:13 UTC, illiarerun commented
Also, rerun your tests one more time and deploy, something wrong with them

2022-03-10 10:59 UTC, illiarerun approved these changes

2025-01-03 14:21 UTC, closed without merging