Add layout_catalog
mate-academy/layout_catalog pull request #1398
Opened 2022-02-22 21:20 UTC by YegorKochetkov

- [DEMO LINK](https://YegorKochetkov.github.io/layout_catalog/)
- [TEST REPORT LINK](https://YegorKochetkov.github.io/layout_catalog/report/html_report/)

2022-02-23 14:13 UTC, kurochka-vladyslav approved these changes

2022-02-23 19:43 UTC, kurochka-vladyslav commented
А что со звездами, немного не понял?

2022-02-23 20:48 UTC, YegorKochetkov commented
а что со звездами? немного переделал css с учетом новых знанинй о sass

On Wed, Feb 23, 2022 at 9:43 PM Vladyslav Kurochka ***@***.***>
wrote:

> А что со звездами, немного не понял?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mate-academy/layout_catalog/pull/1398#issuecomment-1049147867>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AF73MSV5EOHZPJEM3FLIOSTU4U2GDANCNFSM5PCRY2VA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-02-23 22:10 UTC, MaksimusCRS requested changes

2022-02-23 22:10 UTC, MaksimusCRS commented on src/styles/main.scss
> +@import "./blocks/stars";
нет отдельного файлика для блока nav, хотя он у тебя блок

2022-02-23 22:10 UTC, MaksimusCRS commented on src/index.html
> +          width="200"
Какой профит задавать размер картинке тут?

2022-02-24 09:20 UTC, YegorKochetkov commented on src/index.html
> +          width="200"
а где-то по ссылками под видео лекциями вычитал рекомендации всегда задавать в html, мол это предотвращает дерганье

2022-03-08 14:00 UTC, illiarerun approved these changes
Great job 🔥 Probably the best solution of this task that i've seen

2022-11-01 22:08 UTC, closed without merging