Develop
mate-academy/layout_catalog pull request #1418
Opened 2022-02-23 22:29 UTC by OksanaAzarnina

- [DEMO LINK](https://OksanaAzarnina.github.io/layout_catalog/)
- [TEST REPORT LINK](https://OksanaAzarnina.github.io/layout_catalog/report/html_report/)

Кількість питань збільшується.
1. Не проходять два останніх теста. При наведенні мишкою на "Купить" кнопка змінює колір. Але що требо для тестів не розумію.
2. В мене загальна ширина контейнера для карток задана жорстко. Не можу зрозуміти, як робити перенесення після четвертого елемента.
3. Центрування загального контейнера зроблена через margin: 0 auto;. Хотілось би через justify-content: center; Но чомусь в мене не центрується.

2022-02-28 13:12 UTC, vkryvytskyy commented
> * [DEMO LINK](https://OksanaAzarnina.github.io/layout_catalog/)
> 
>     * [TEST REPORT LINK](https://OksanaAzarnina.github.io/layout_catalog/report/html_report/)
> 
> 
> Кількість питань збільшується.
> 
>     1. Не проходять два останніх теста. При наведенні мишкою на "Купить" кнопка змінює колір. Але що требо для тестів не розумію.
> 
>     2. В мене загальна ширина контейнера для карток задана жорстко. Не можу зрозуміти, як робити перенесення після четвертого елемента.
> 
>     3. Центрування загального контейнера зроблена через margin: 0 auto;. Хотілось би через justify-content: center; Но чомусь в мене не центрується.

2. display: flex и flex-wrap должны с этим справиться, при условии что у тебя будет правильно задана ширина карточек и отступы между ними

3. Для этого надо на родительский элемент `загального контейнера` добавить display: flex, и ему указывать justify-content: center

2022-02-28 13:15 UTC, vkryvytskyy requested changes

2022-02-28 13:15 UTC, vkryvytskyy commented on src/index.html
> +        <div class="card table__card" data-qa="card">
<img width="673" alt="image" src="https://user-images.githubusercontent.com/38065883/155989489-b0aad651-d7e3-4d0b-b79a-fae502eff709.png">
Это же не первая карточка

2022-03-10 09:38 UTC, vitaliy-martynyuk approved these changes

2023-02-22 13:55 UTC, closed without merging