done
mate-academy/layout_catalog pull request #1430
Opened 2022-03-14 20:49 UTC by ShevchyshynRoman

- [DEMO LINK](https://ShevchyshynRoman.github.io/layout_catalog/)
- [TEST REPORT LINK](https://ShevchyshynRoman.github.io/layout_catalog/report/html_report/)

2022-03-15 12:17 UTC, andriyshvets requested changes

2022-03-15 12:17 UTC, andriyshvets commented on src/styles/blocks/card.scss
> +  width: 200px;
```suggestion
  width: 200px;
```
use variable
використай змінну

2022-03-15 12:17 UTC, andriyshvets commented on src/styles/main.scss
> +.cards {
створи для cards окремий блок

2022-03-16 06:59 UTC, Bohdan-Maksymiuk approved these changes
Great job!

2022-03-17 12:00 UTC, aliceblunt8 approved these changes

2025-03-06 15:51 UTC, closed without merging