catalog v01
mate-academy/layout_catalog pull request #1446
Opened 2022-04-01 19:43 UTC by ZUBOV-ILLIA

- [DEMO LINK](https://ZUBOV-ILLIA.github.io/layout_catalog/)
- [TEST REPORT LINK](https://ZUBOV-ILLIA.github.io/layout_catalog/report/html_report/)

2022-04-02 08:27 UTC, EnjSadman requested changes

2022-04-02 08:27 UTC, EnjSadman commented on src/styles/main.scss
> +    background: #f3f3f3;
background color not changing on `:hover`

2022-04-02 08:27 UTC, EnjSadman commented on src/styles/main.scss
> +.stars__star:nth-child(-n + 4) {
'stars' потрібно імплементувати з інших завдань. Щоб при зміні класу з stars--4 на stars--3 змінювалась кількість активних зірочок.
пункти про nth-child відносяться до кількості карток у рядку

2022-04-04 15:33 UTC, Anna-Tkachenko requested changes
Good job!
Small fixes

2022-04-04 15:33 UTC, Anna-Tkachenko commented on src/styles/header.scss
> +  display: block;
Use scss nesting

2022-04-04 15:33 UTC, Anna-Tkachenko commented on src/styles/page.scss
> +  margin: 0 0 46px;
You can't set margins to BEM block

2022-04-05 17:05 UTC, Anna-Tkachenko requested changes
Good job!
Just fix small comments and add scss variables for repeated values (it can be colors or font-size values)

2022-04-06 12:18 UTC, Anna-Tkachenko approved these changes
Well Done! ✔️

2025-03-07 09:13 UTC, closed without merging