Solution
mate-academy/layout_catalog pull request #1447
Opened 2022-04-02 19:12 UTC by yelnikov-andrii

- [DEMO LINK](https://yelnikov-andrii.github.io/layout_catalog/)
- [TEST REPORT LINK](https://yelnikov-andrii.github.io/layout_catalog/report/html_report/)

2022-04-03 06:44 UTC, EnjSadman requested changes
Не працюють демо-лінки. Спробуй ще раз зробити деплой

2022-04-03 14:35 UTC, yelnikov-andrii commented
> Не працюють демо-лінки. Спробуй ще раз зробити деплой

fixed

2022-04-06 12:17 UTC, Anna-Tkachenko requested changes
Fix comments and try to pass tests

2022-04-06 12:17 UTC, Anna-Tkachenko commented on src/index.html
> +      <img class="header__logo" src="./images/logo.png" alt="logo">
It should be the link

2022-04-06 12:17 UTC, Anna-Tkachenko commented on src/index.html
> +            </a>
Set correct hrefs for the links

2022-04-06 12:17 UTC, Anna-Tkachenko commented on src/index.html
> +        </span>
Fix indents
```suggestion
        <span class="card__code">
          Код товара: 195434
        </span>
```

2022-04-06 12:17 UTC, Anna-Tkachenko commented on src/styles/blocks/header.scss
> +  justify-content: space-between;
Will be better to use variable for correct indents between the cards (it should fix the tests)

2022-04-06 12:17 UTC, Anna-Tkachenko commented on src/styles/blocks/header.scss
> +      font-size: 12px;
Move it to nav.scss file

2022-04-06 12:17 UTC, Anna-Tkachenko commented on src/styles/blocks/main.scss
> +  padding: 32px 16px 16px;
Move this styles to container.css and card.scss files

2022-04-06 12:17 UTC, Anna-Tkachenko commented on src/styles/blocks/main.scss
> +}
Use cycle instead of 5 selectors
Move this styles to stars.scss file

2022-04-06 12:17 UTC, Anna-Tkachenko commented on src/styles/blocks/main.scss
> +  font-size: 16px;
Move this styles to card.scss file

2022-04-07 09:43 UTC, Anna-Tkachenko requested changes
Fix comments, check font styles and indents for your page and try to pass tests

2022-04-07 09:43 UTC, Anna-Tkachenko commented on src/index.html
> +          </li>
Set correct href for all links

2022-04-07 09:43 UTC, Anna-Tkachenko commented on src/index.html
> +                href="/">
Fix indents

2022-04-07 09:43 UTC, Anna-Tkachenko commented on src/styles/blocks/card.scss
> +  margin-right: $gapX;
You can't set width and margins for BEM block

2022-04-07 09:43 UTC, Anna-Tkachenko commented on src/styles/blocks/main.scss
> +  margin: 0 auto;
You can't set width and margin for BEM block

2022-04-07 09:43 UTC, Anna-Tkachenko commented on src/styles/blocks/nav.scss
> +  width: 756px;
Same here

2022-04-07 14:23 UTC, Anna-Tkachenko approved these changes

2022-04-07 14:23 UTC, Anna-Tkachenko commented on src/styles/blocks/card.scss
> +}
Move this styles to main.scss file

2022-04-07 14:23 UTC, Anna-Tkachenko commented on src/styles/blocks/header.scss
> +}
Use nesting

2022-04-07 14:23 UTC, Anna-Tkachenko commented on src/styles/blocks/main.scss
> +  margin: 0 auto;
Move this styles to page.scss file

2022-04-07 14:23 UTC, Anna-Tkachenko commented on src/styles/style.scss
> +}
Move this styles to page.scss
You can't set margins to BEM block

2024-03-19 14:39 UTC, closed without merging