catalog
mate-academy/layout_catalog pull request #1475
Opened 2022-04-09 13:40 UTC by ISRLv2021

- [DEMO LINK](https://ISRLv2021.github.io/layout_catalog/)
- [TEST REPORT LINK](https://ISRLv2021.github.io/layout_catalog/report/html_report/)

2022-04-10 14:06 UTC, ZUBOV-ILLIA requested changes

2022-04-10 14:06 UTC, ZUBOV-ILLIA commented on src/styles/blocks/card.scss
> +      border-color: $blueAccent;
`&__btn-link` must have `transition` option.

2022-04-10 14:06 UTC, ZUBOV-ILLIA commented on src/styles/blocks/navigation.scss
> +    }
`&__link` must have `transition` option.

2022-04-10 21:53 UTC, ISRLv2021 commented on src/styles/utils/_loops.scss
> +    background-position: center;
got it

2022-04-10 21:53 UTC, ISRLv2021 commented on src/styles/blocks/card.scss
> +      border-color: $blueAccent;
corrected

2022-04-10 21:56 UTC, ISRLv2021 commented on src/styles/blocks/navigation.scss
> +    }
Thanks a lot, completed

2022-04-11 11:35 UTC, Denchepornyuk requested changes
<img width="129" alt="Screenshot 2022-04-11 at 14 33 30" src="https://user-images.githubusercontent.com/37452763/162731164-8e2228b6-247a-4e53-998f-cb42905eb3f4.png">

something wrong with stars

2022-04-11 11:35 UTC, Denchepornyuk commented on src/index.html
> +          class="logo__img">
```suggestion
          class="logo__img"
        >
```

2022-04-11 11:35 UTC, Denchepornyuk commented on src/index.html
> +              data-qa="nav-hover">
fix closing quote in all places
```suggestion
              data-qa="nav-hover"
            >
```

2022-04-11 11:35 UTC, Denchepornyuk commented on src/index.html
> +            </a>
```suggestion
              href="#tablets"
            >
              планшеты
            </a>
```

2022-04-11 14:43 UTC, Denchepornyuk requested changes
<img width="516" alt="Screenshot 2022-04-11 at 17 41 25" src="https://user-images.githubusercontent.com/37452763/162764217-9c572e61-0a4a-44c4-bdf8-003ab7f0a992.png">
the stars are still broken

2022-04-12 08:42 UTC, Denchepornyuk approved these changes

2022-12-21 21:18 UTC, closed without merging