Product catalog
mate-academy/layout_catalog pull request #1483
Opened 2022-04-13 13:17 UTC by Alyona-Pisotska

https://Alyona-Pisotska.github.io/layout_catalog/
https://Alyona-Pisotska.github.io/layout_catalog/report/html_report/

2022-04-13 19:59 UTC, ArturErmolenko requested changes
Нужно убрать лишнюю верстку и добавить файлы со стилями


<img width="800" alt="Screenshot 2022-04-13 at 22 58 59" src="https://user-images.githubusercontent.com/94292654/163260369-834e594c-1d98-4d94-826d-4ba44139d3b9.png">

2022-04-13 19:59 UTC, ArturErmolenko commented on src/index.html
> +              </div>
Тебе это не нужно, по дизайну ты можешь оставить только блок в котором 4 звездочки

2022-04-13 19:59 UTC, ArturErmolenko commented on src/index.html
> +            </div>
```suggestion
              
```

2022-04-14 20:46 UTC, vkryvytskyy requested changes

2022-04-14 20:46 UTC, vkryvytskyy commented on .editorconfig
> +insert_final_newline = false
https://user-images.githubusercontent.com/38065883/163472308-428f31e1-ece9-4b9a-aaf7-e0af326a4171.mov

При наведении на кнопку почему-то скачет контент

2022-04-14 20:46 UTC, vkryvytskyy commented on src/index.html
> +          <h1 class="product-information__name">
```suggestion
          <h2 class="product-information__name">
```
Желательно на странице иметь не больше 1-2 `h1` тегов

2022-04-14 20:48 UTC, marina-tilniak requested changes
- https://www.loom.com/share/cfdc05b4dffa498ca83b012a9baeb4d5
- checklist point 11

2022-04-15 10:01 UTC, marina-tilniak requested changes
did you see checklist? Fix please point 11

2022-04-15 19:39 UTC, ArturErmolenko approved these changes

2025-05-07 14:56 UTC, closed without merging