catalog done
mate-academy/layout_catalog pull request #1511
Opened 2022-05-11 09:53 UTC by vsupruniuk

- [DEMO LINK](https://vsupruniuk.github.io/layout_catalog/)
- [TEST REPORT LINK](https://vsupruniuk.github.io/layout_catalog/report/html_report/)

2022-05-13 20:52 UTC, Galyopa requested changes
Гарна робота, але подивись на рахунок зайвих властивостей.

2022-05-13 20:52 UTC, Galyopa commented on src/styles/blocks/card.scss
> +  &__image-imac {
як на мене назва має бути просто image.

2022-05-13 20:52 UTC, Galyopa commented on src/styles/blocks/card.scss
> +    @include iMacSize($imac-height, $imac-width);
не зрозуміло навіщо, а також назва дивна, у нас інтернет магазин техніки ,а якщо буде картинка блендера?

2022-05-13 20:52 UTC, Galyopa commented on src/styles/blocks/card.scss
> +  }
```suggestion
  &__stars {
    display: flex;
    justify-content: space-between;
    line-height: 16px;
    margin-bottom: 23px;
    height: 16px;
    width: 16px;
    margin-right: 4px;
    background-repeat: no-repeat;
    background-position: top;
    background: url("../images/star.svg");
  }

  &__stars .star-1,
  &__stars .star-2,
  &__stars .star-3,
  &__stars .star-4 {
    background: url("../images/star-active.svg");
  }

  }
```

так уникаєш повторення коду, а також спробуй for loop використати.

2022-05-13 20:52 UTC, Galyopa commented on src/styles/blocks/header.scss
> +    padding: 10px 0;
навіщо цей падінг?

2022-05-13 20:52 UTC, Galyopa commented on src/styles/blocks/card.scss
> +  justify-content: flex-start;
ніби за замовченням flex-start

2022-05-13 20:52 UTC, Galyopa commented on src/styles/blocks/card.scss
> +  align-items: center;
зайва властивість

2022-05-13 20:52 UTC, Galyopa commented on src/styles/blocks/card.scss
> +    align-self: flex-start;
якщо у card убрати align-items: center; то непотрібно буде   &__code {
    align-self: flex-start;

2022-05-16 11:15 UTC, Galyopa approved these changes
Добре попрацював !

2022-05-16 11:15 UTC, Galyopa commented on src/styles/blocks/card.scss
> +    width: $imac-width;
назву змінних забув змінити )

2022-05-17 12:12 UTC, Olexandr6 commented on src/styles/blocks/card.scss
> +  &__image-imac {
@Galyopa is right

2022-05-17 12:12 UTC, Olexandr6 commented on src/styles/blocks/card.scss
> +    @include iMacSize($imac-height, $imac-width);
Agree, сhange this

2022-05-17 12:14 UTC, Olexandr6 approved these changes
Good job👍

2022-05-17 12:14 UTC, Olexandr6 commented on src/styles/blocks/card.scss
> +    width: $imac-width;
Yeah, would be better to change

2024-01-13 13:26 UTC, closed without merging