Add catalog's page
mate-academy/layout_catalog pull request #1530
Opened 2022-05-13 19:39 UTC by ik-web

- [DEMO LINK](https://ik-web.github.io/layout_catalog/)
- [TEST REPORT LINK](https://ik-web.github.io/layout_catalog/report/html_report/)

2022-05-15 17:25 UTC, AKomashchuk requested changes

2022-05-15 17:25 UTC, AKomashchuk commented on src/index.html
> +    >
Не вистачає пробілів , все на одному рівні

2022-05-15 17:25 UTC, AKomashchuk commented on src/index.html
> +          >
Не вистачає пробілів, і нище у всіх img також

2022-05-15 17:25 UTC, AKomashchuk commented on src/styles/blocks/stars.scss
> +}
Подивись уважніше куди ти записав функцію , думаю із цього на demo не видно зірочок

2022-05-15 18:29 UTC, ik-web commented on src/index.html
> +    >
Fixed

2022-05-15 18:29 UTC, ik-web commented on src/index.html
> +          >
Fixed

2022-05-15 18:29 UTC, ik-web commented on src/styles/blocks/stars.scss
> +}
Fixed

2022-05-15 18:30 UTC, ik-web commented
Thank you for review, I've fixed those mistakes.

2022-05-15 18:43 UTC, AKomashchuk commented
Good job!)

2022-05-15 18:46 UTC, AKomashchuk approved these changes

2022-05-16 15:55 UTC, mykola-koval approved these changes

2022-05-16 15:55 UTC, mykola-koval commented on src/styles/blocks/cards.scss
> +  box-sizing: border-box;
Always add `box-sizing: border-box;` on all elements `* {...}`****

2022-05-16 15:55 UTC, mykola-koval commented on src/styles/blocks/product-card.scss
> +  box-sizing: border-box;
Always add `box-sizing: border-box;` on all elements `* {...}`

2022-09-14 14:01 UTC, closed without merging