Made catalog
mate-academy/layout_catalog pull request #1535
Opened 2022-05-14 10:02 UTC by mira1zu

- [DEMO LINK](https://mira1zu.github.io/layout_catalog/)
- [TEST REPORT LINK](https://mira1zu.github.io/layout_catalog/report/html_report/)

2022-05-15 08:15 UTC, DmitriiPirohov requested changes

2022-05-15 08:15 UTC, DmitriiPirohov commented on src/styles/blocks/header.scss
> +  &__logo-image {
Хорошая работа. Я не сильно хорош в этом но перед "&__logo-image" добавил пробел.

2022-05-15 08:15 UTC, DmitriiPirohov commented on src/styles/blocks/page.scss
> +.page {
Сорян, я не уверен но мне кажется это не совсем понятно для человека со стороны. Я бы назвал страничку normalise.
И я бы еще перенес все технические стили в папку utils

2022-05-15 08:15 UTC, DmitriiPirohov commented on src/styles/main.scss
> +
Вот эти пробелы я бы тоже убрал бы

2022-05-15 08:15 UTC, DmitriiPirohov commented on src/styles/utils/_variables.scss
> +
Еще

2022-05-15 17:12 UTC, mira1zu commented on src/styles/blocks/header.scss
> +  &__logo-image {
Пропустил, спасибо

2022-05-15 17:12 UTC, mira1zu commented on src/styles/main.scss
> +
Не согласен. Лично я использую пробелы что бы было легче читать код

2022-05-15 17:20 UTC, DmitriiPirohov commented on src/styles/main.scss
> +
оки

2022-05-15 17:21 UTC, DmitriiPirohov approved these changes

2022-05-17 10:06 UTC, Olexandr6 approved these changes
Good job🔥

2022-05-17 10:06 UTC, Olexandr6 commented on src/index.html
> +      </nav>
[Checklist](https://github.com/mate-academy/layout_catalog/blob/master/checklist.md) 2nd point

2022-12-08 22:08 UTC, closed without merging