product  catalog was created
mate-academy/layout_catalog pull request #1542
Opened 2022-05-15 17:31 UTC by KrisMur

- [DEMO LINK](https://KrisMur.github.io/layout_catalog/)
- [TEST REPORT LINK](https://KrisMur.github.io/layout_catalog/report/html_report/)

2022-05-16 08:45 UTC, olya-yevsieienko approved these changes
Я добавила пару комментариев, но всё здорово, ты молодец! 🔥

2022-05-16 08:45 UTC, olya-yevsieienko commented on src/index.html
> +    <main class="main">
Здесь можно добавить абзац для большей читабельности:)

2022-05-16 08:45 UTC, olya-yevsieienko commented on src/index.html
> +                </div>
Возможно, лучше переделать этот блок отталкиваясь от пункта 6 Checklist.

2022-05-16 08:45 UTC, olya-yevsieienko commented on src/styles/blocks/logo.scss
> +}
Думаю, можно не прописывать logo отдельным блоком, так как это составная часть header.

2022-05-16 16:20 UTC, mykola-koval requested changes

2022-05-16 16:20 UTC, mykola-koval commented on src/index.html
> +                </div>
agree 👍

2022-05-16 16:20 UTC, mykola-koval commented on src/index.html
> +    <main class="main">
agree

2022-05-16 16:20 UTC, mykola-koval commented on src/styles/blocks/logo.scss
> +}
agree

2022-05-16 16:20 UTC, mykola-koval commented on src/styles/blocks/product_card.scss
> +      padding: 11px;
need this?

2022-05-17 12:29 UTC, mykola-koval approved these changes

2022-05-17 12:29 UTC, mykola-koval commented on src/index.html
> +              <h2 class="product-card__title">
add one empty line between same level elements
```suggestion
              >
              
              <h2 class="product-card__title">
```

2022-05-17 12:29 UTC, mykola-koval commented on src/styles/blocks/heder.scss
> +}
use logo as an element of header block

2024-10-19 12:31 UTC, closed without merging