big catalog
mate-academy/layout_catalog pull request #1577
Opened 2022-05-19 10:50 UTC by leonid-levtseniuk

2022-05-19 13:15 UTC, aliceblunt8 requested changes
please get stars task approved and use everything fixed from previous PRs here

2022-05-19 13:15 UTC, aliceblunt8 commented on src/index.html
> +            <a href="#1" class="is-active">Apple
let's make nav a separate block

```suggestion
      <nav class="nav">
        <ul class="nav__list">
          <li class="nav__item">
            <a href="#1" class="nav__link is-active">Apple
```

2022-05-19 13:15 UTC, aliceblunt8 commented on src/index.html
> +            </div>
modifier class? you should reuse stars block from the previous task

2022-05-19 13:54 UTC, leonid-levtseniuk commented
> please get stars task approved and use everything fixed from previous PRs here

Ok, sorry for that

2022-05-20 13:34 UTC, aliceblunt8 approved these changes

2022-05-20 13:40 UTC, closed without merging