first commit
mate-academy/layout_catalog pull request #1609
Opened 2022-06-05 20:29 UTC by pavel-gutsal

https://pavel-gutsal.github.io/layout_catalog/
https://pavel-gutsal.github.io/layout_catalog/report/html_report/

data-qa="card-hover" - responsible for testing hover on link feature ;
it is present on each link elemet 
yet test sometimes passes successfully or fails without any changes to the code 
on hover effect on site itself is operational

2022-06-07 17:51 UTC, ArturErmolenko requested changes
Good job 👍 
just small fix

2022-06-07 17:51 UTC, ArturErmolenko commented on src/index.html
> +            >
```suggestion
            <img 
              src="./images/imac.jpeg" 
              alt="picture" 
              class="main__img"
            >
```

2022-06-07 17:51 UTC, ArturErmolenko commented on src/styles/blocks/stars.scss
> +  }
селекторы с одинаковыми стилями лучше записать через запятую
```
.stars--1 :first-child,
.stars--2 :nth-child(-n + 2),
.stars--3 :nth-child(-n + 3),
.stars--4 :nth-child(-n + 4),
.stars--5 :nth-child(-n + 5) {
   background-image: url("/images/star-active.svg");
 }
```

2022-06-07 18:08 UTC, pavel-gutsal commented
all issues are fixed

2022-06-08 19:37 UTC, vkryvytskyy requested changes

2022-06-08 19:37 UTC, vkryvytskyy commented on src/index.html
> +            >
```suggestion
            <img 
              src="./images/imac.jpeg" 
              alt="picture" 
              class="main__img"
            >
```

2022-06-08 19:37 UTC, vkryvytskyy commented on src/index.html
> +          <div class="main__reviewes main__reviewes--margin_bottom">
```suggestion
          <div class="main__reviews reviews">
```
why do you need separate class to margin-bottom? If you need set margins, set them in main__reviews and set own styles for reviews block in reviews class.
`main__reviews` describes positioning of element in the `main` block
`review` describes own styles for element

2022-06-08 19:37 UTC, vkryvytskyy commented on src/styles/blocks/mainBlock.scss
> +    flex-direction: row;
this is default value for flex-direction, should be ommited

2022-06-10 11:22 UTC, pavel-gutsal commented
https://pavel-gutsal.github.io/layout_catalog/
https://pavel-gutsal.github.io/layout_catalog/report/html_report/
all issues were fixed

2022-06-13 11:35 UTC, Bohdan-Maksymiuk requested changes
<img width="450" alt="Screenshot 2022-06-13 at 14 33 14" src="https://user-images.githubusercontent.com/94289038/173345081-14186f75-5d3b-4fb8-acf7-fbede2d07597.png">

check your demos

2022-06-13 11:35 UTC, Bohdan-Maksymiuk commented on src/index.html
> +            >
```suggestion
            <img 
              src="./images/imac.jpeg" 
              alt="picture" 
              class="main__img"
            >
```
fix everywhere

2022-06-15 12:08 UTC, aliceblunt8 approved these changes

2022-10-07 11:13 UTC, closed without merging