moyo-catalog
mate-academy/layout_catalog pull request #1630
Opened 2022-06-10 07:17 UTC by Kras4iy

- [DEMO LINK](https://Kras4iy.github.io/layout_catalog/)
- [TEST REPORT LINK](https://Kras4iy.github.io/layout_catalog/report/html_report/)

2022-06-10 07:53 UTC, TwoAndMore requested changes

2022-06-10 07:53 UTC, TwoAndMore commented on src/index.html
> +    <main class="catalog">
Краще в main не застосовувати тільки каталог, оскільки можуть бути й інші блоки.

2022-06-10 07:53 UTC, TwoAndMore commented on src/index.html
> +          <a
CHECKLIST: 2. [CODE STYLE] - Add empty lines between multiline sibling blocks of HTML. But don't add empty lines between parent and child elements
Більше  відступів між елементами, як у хедері.

2022-06-10 07:53 UTC, TwoAndMore commented on src/index.html
> +          </a>
Зайвий відступ

2022-06-10 07:53 UTC, TwoAndMore commented on src/styles/blocks/stars.scss
> +.stars__star {
Використовуй &
```suggestion
&__star {
```
та внеси у .stars

2022-06-10 07:53 UTC, TwoAndMore commented on src/styles/blocks/stars.scss
> +}
Спробуй згенерувати правилом. Використовуй &.

2022-06-10 07:53 UTC, TwoAndMore commented on src/index.html
> +          <h1 class="card__title">
h1 Може бути лише один на сторінці

2022-06-10 07:53 UTC, TwoAndMore commented on src/styles/blocks/catalog.scss
> +    + $distanceBetweenCards * ($cardsAmountInRow - 1));
У тебе є **_variables.scss**, можна ширину винести у зміну.

2022-06-10 07:53 UTC, TwoAndMore commented on src/styles/blocks/catalog.scss
> +}
У тебе є **card.scss**,  і там **.card**  і тут. Також не використовуй зовнішні відступи для бем-блоків.

2022-06-10 07:53 UTC, TwoAndMore commented on src/styles/blocks/header.scss
> +  &__nav {
Окремий бем блок

2022-06-10 13:59 UTC, VETALEK requested changes
Good stary 💪

2022-06-10 13:59 UTC, VETALEK commented on src/styles/blocks/card.scss
> +  font-family: "Roboto", sans-serif;
you may move this to `html{}`, cause `header` also uses this font 😉

2022-06-10 13:59 UTC, VETALEK commented on src/styles/blocks/card.scss
> +  font-family: "Roboto", sans-serif;
oh, you already have it, so no need to set it again 😉

2022-06-10 13:59 UTC, VETALEK commented on src/styles/blocks/card.scss
> +  font-family: "Roboto", sans-serif;
```suggestion
```

2022-06-10 13:59 UTC, VETALEK commented on src/styles/blocks/card.scss
> +    margin: auto;
```suggestion
    margin: 0 auto;
```

that'll happen if the card become higher 🥲

<img width="218" alt="image" src="https://user-images.githubusercontent.com/55802630/173081650-23860443-07eb-424a-b215-ca59f4bb4818.png">

2022-06-10 13:59 UTC, VETALEK commented on src/styles/blocks/main.scss
> +    width: ( $cardWidth * $cardsAmountInRow +
you need `min-width`

<img width="585" alt="image" src="https://user-images.githubusercontent.com/55802630/173081889-dd02adfb-44f7-46b6-b302-c347e60f0d84.png">


<img width="419" alt="image" src="https://user-images.githubusercontent.com/55802630/173081929-20dcffe6-740b-4593-8e8a-e26e8228ebf9.png">

2022-06-14 06:56 UTC, ivan-kadykalo requested changes

2022-06-14 06:56 UTC, ivan-kadykalo commented on src/index.html
> +      </a>
Don't forget about code style.
Checklist #2

2022-06-14 06:56 UTC, ivan-kadykalo commented on src/styles/blocks/main.scss
> +    display: flex;
Why do you need min-width twice?

2022-06-14 06:56 UTC, ivan-kadykalo commented on src/styles/blocks/main.scss
> +      &:not(:nth-child(#{$cardsAmountInRow}n)) {
Something wrong here, it should work without # 
`($cardsAmountInRow * n)`

2022-06-14 08:56 UTC, ivan-kadykalo approved these changes

2026-04-07 16:39 UTC, closed without merging