added catalog
mate-academy/layout_catalog pull request #1643
Opened 2022-06-11 21:25 UTC by silchyn

- [DEMO LINK](https://silchyn.github.io/layout_catalog/)
- [TEST REPORT LINK](https://silchyn.github.io/layout_catalog/report/html_report/)

2022-06-12 09:15 UTC, chernobrovin requested changes
трохи тобі понаписував, соррі))

Тести в тебе не б'ють скоріш за все через те, що в тебе забагато `flex `  на каталозі накидано. Він там не всюди потрібен.

2022-06-12 09:15 UTC, chernobrovin commented on src/styles/blocks/card.scss
> +    font: 500 12px/18px "Roboto", sans-serif;
немає сенсу так постійно прописувати шрифт: він єдиний для всього проекту. 
по необідності достатньо уточнювати `font-weight` та `font-size`

2022-06-12 09:15 UTC, chernobrovin commented on src/styles/blocks/header.scss
> +
всюди трохи э проблеми з 
check-list №12[CODE STYLE] - Remember about styles properties order - ([css order](https://codeguide.academy/html-css.html#css-order))

2022-06-12 10:51 UTC, silchyn commented on src/index.html
> +        <h1 class="card__title">
Не зовсім розумію з яких міркувань.

2022-06-12 10:51 UTC, silchyn commented on src/styles/blocks/header.scss
> +
А які саме проблеми?

2022-06-12 14:40 UTC, chernobrovin commented on src/index.html
> +        <h1 class="card__title">
з міркувань СЕО оптимізації. в даному випадку це вважається помилкою.

2022-06-12 14:42 UTC, chernobrovin commented on src/styles/blocks/header.scss
> +
ну ось наприклад саме тут ти спочатку пишеш шрифт, а потім flex-елементи, а треба навпаки

Порядок свойств
Объявления логически связанных свойств сгруппированы в следующем порядке:

Позиционирование
Блочная модель
Типографика
Оформление
Анимация
Разное

```
.declaration-order {
  /* Позиционирование */
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  z-index: 100;

  /* Блочная модель */
  display: block;
  float: right;
  width: 100px;
  height: 100px;
  margin: 10px;
  padding: 10px;

  /* Типографика */
  font-family: "Arial", sans-serif;
  font-style: normal;
  font-size: 13px;
  line-height: 20px;
  font-weight: 700;
  text-align: center;
  color: #333333;

  /* Оформление */
  background-color: #f5f5f5;
  border: 1px solid #e5e5e5;
  border-radius: 3px;
  opacity: 1;

  /* Анимация */
  transition: color 1s;

  /* Разное */
  will-change: auto;
}
```

2022-06-12 14:45 UTC, silchyn commented on src/styles/blocks/header.scss
> +
Мені здавалось що justify-content та align-items відносяться до "різне", бо це позиціювання дітей, а не самого елементу. Хіба ні?

2022-06-12 14:47 UTC, silchyn commented on src/index.html
> +        <h1 class="card__title">
А в яких випадках це не вважається помилкою?

2022-06-12 15:00 UTC, chernobrovin commented on src/index.html
> +        <h1 class="card__title">
коли `h1` тільки один на сторінці. наприклад коли в минулому завданні ти робив 1 картку то і заголовок в тебе був 1. А зараз в тебе їх вийшло 8.

2022-06-12 15:03 UTC, chernobrovin commented on src/styles/blocks/header.scss
> +
так діти ж поіціонуються за рахунок властивостей даного блоку. Цы властивості, навіть якщо вони впливають на дітей, застосовуються до батьківського блоку

2022-06-12 15:12 UTC, chernobrovin commented on src/styles/blocks/card.scss
> +      margin-top: 16px;
```suggestion

```
навіщо тобі це? подивись: в тебе при наведенні на кнопку самої першої карки підстрибує нижній ряд

2022-06-13 15:06 UTC, chernobrovin approved these changes

2022-06-14 07:10 UTC, ivan-kadykalo commented on src/styles/blocks/card.scss
> +      margin-top: 16px;
You haven't fixed this bug yeat

2022-06-14 07:16 UTC, ivan-kadykalo requested changes
Fix your bug with jumping rows on button hover

2022-06-14 07:16 UTC, ivan-kadykalo commented on src/index.html
> +          </h4>
Don't use `h` tags everywhere, you have also `p` 🙂
Find what is primary info and use for them `h`

2022-06-14 07:16 UTC, ivan-kadykalo commented on src/index.html
> +        <h3 class="card__code">
Will be better to use `p`

2022-06-14 08:23 UTC, ivan-kadykalo approved these changes

2023-02-10 20:19 UTC, closed without merging