fixed
mate-academy/layout_catalog pull request #1664
Opened 2022-06-14 09:35 UTC by blcts

- [DEMO LINK](https://blcts.github.io/layout_catalog/)
- [TEST REPORT LINK](https://blcts.github.io/layout_catalog/report/html_report/)

2022-06-14 11:29 UTC, denys-danyliuk commented on src/styles/blocks/card.scss
> +  margin-bottom: 46px;
можеш прибрати для останніх 4 елементів цей відступ, і всюди задаєш margin-top, а тут margin-bottom, але думаю це не критично

2022-06-14 11:32 UTC, denys-danyliuk commented on src/index.html
> +      <a href="home" class="logo">
ти створюєш окремий бем блок, і стилізуєш його в файлі nav. 9 правило чекліста

2022-06-14 11:34 UTC, denys-danyliuk commented on src/styles/blocks/catalog.scss
> +  margin: 50px auto;
відступи для бем блоку

2022-06-14 11:34 UTC, denys-danyliuk commented on src/styles/blocks/nav.scss
> +  margin: 0;
відступи для бем блоку

2022-06-14 11:35 UTC, denys-danyliuk commented on src/styles/blocks/nav.scss
> +  margin: 5px 45px;
відступи для бем блоку

2022-06-14 11:35 UTC, denys-danyliuk commented on src/styles/blocks/catalog.scss
> +.catalogMoyo {
фактично в тебе два різних бем блока стилізується в одному файлі

2022-06-14 11:36 UTC, denys-danyliuk commented on src/styles/blocks/nav.scss
> +.nav__list {
можеш вкласти його всередину там де стилі для навігації з використанням &. 10 правило чекліста

2022-06-15 07:15 UTC, ivan-kadykalo requested changes
Almost done.
Don't use gap in this task, use margins and nth:child
+ Checklist p13, fix it
![image](https://user-images.githubusercontent.com/57747481/173766018-aded3b03-f96c-4c57-a401-fe0e4c256be3.png)

2022-06-16 12:07 UTC, ivan-kadykalo approved these changes
💪

2023-04-19 13:50 UTC, closed without merging