Develop
mate-academy/layout_catalog pull request #1688
Opened 2022-06-16 12:35 UTC by Glebatikot

- [DEMO LINK](https://Glebatikot.github.io/layout_catalog/)
- [TEST REPORT LINK](https://Glebatikot.github.io/layout_catalog/report/html_report/)

2022-06-16 15:29 UTC, budanov20 commented
it is a problem with height or margin/padding

2022-06-17 07:21 UTC, ivan-kadykalo requested changes
You should add some padding on the bottom of your page, your content is glued to the bottom of the screen.
And fix that problem with fonts in navigation. They still don't have needed weight

2022-06-17 15:23 UTC, Ihor-Karpyn approved these changes

2022-06-17 15:23 UTC, Ihor-Karpyn commented on src/styles/_normalize.scss
> +  padding: 0;
don't use `*` to reset something, just for `box-sizing`. To reset something list all tags

2022-06-30 07:19 UTC, closed without merging