Catalog
mate-academy/layout_catalog pull request #1689
Opened 2022-06-16 15:38 UTC by p-omogit-e

- [DEMO LINK](https://p-omogit-e.github.io/layout_catalog/)
- [TEST REPORT LINK](https://p-omogit-e.github.io/layout_catalog/report/html_report/)

2022-06-17 15:06 UTC, aliceblunt8 requested changes
all cards should be in one container (use flex)

2022-06-25 12:15 UTC, marina-tilniak requested changes
https://www.loom.com/share/16bae410747c416aae43bd6e69552c91

- посилання в header не повинні переходити на 404

- не пройшов жоден тест, це потрібно виправити

2022-06-25 12:15 UTC, marina-tilniak commented on src/styles/blocks/rating.scss
> +  height: 16px;
delete it

2022-06-25 12:15 UTC, marina-tilniak commented on src/styles/blocks/rating.scss
> +  display: inline-flex;
and it

2022-06-25 12:15 UTC, marina-tilniak commented on src/styles/blocks/rating.scss
> +.stars--4 :nth-child(4) {
```suggestion
..stars--1 :nth-child(1),
.stars--2 :nth-child(-n + 2),
.stars--5 :nth-child(-n + 5),
.stars--3 :nth-child(-n + 3),
.stars--4 :nth-child(-n + 4) {
```

2022-06-29 06:45 UTC, p-omogit-e commented on src/styles/blocks/rating.scss
> +.stars--4 :nth-child(4) {
I'm sorry, but I have no idea why test falls:( What can I fix?

2022-06-30 12:32 UTC, Bohdan-Maksymiuk requested changes
did you deploy changes?
ask in fe_chat and we will help you
now nothing is fixed from prev comments

2022-07-02 08:03 UTC, Bohdan-Maksymiuk requested changes
fix color of text on your cards
and position of `.rating__stars` and '.rating__responses' in your card

2022-07-02 08:03 UTC, Bohdan-Maksymiuk commented on src/styles/normalize.scss
> +}
```suggestion
}

* {
  box-sizing: border-box;
}
try this

```

2022-07-02 09:10 UTC, p-omogit-e commented on src/styles/blocks/header.scss
> +  bottom: -20px;
![image](https://user-images.githubusercontent.com/102521367/176994188-82c14b67-4b0c-4618-a61c-4d6a55f86fa5.png)
It looks like this if I change bottom, so I didn't

2022-07-02 09:16 UTC, p-omogit-e commented on src/styles/normalize.scss
> +}
4 test is passed, thank you!!

2022-07-05 14:12 UTC, ArturErmolenko approved these changes

2025-12-17 21:22 UTC, closed without merging