task Catalog
mate-academy/layout_catalog pull request #1755
Opened 2022-07-17 16:24 UTC by vladgusakovskiy

- [DEMO LINK](https://vladgusakovskiy.github.io/layout_catalog/)
- [TEST REPORT LINK](https://vladgusakovskiy.github.io/layout_catalog/report/html_report/)

2022-07-20 13:30 UTC, adrqq commented
great job)

2022-07-21 07:36 UTC, dellachaise requested changes
Great start 👍

Please, add fixes according to comments.

2022-07-21 07:36 UTC, dellachaise commented on src/index.html
> +        <section class="card" data-qa="card">
I see no styles for `main` class. You could delete it. Better name for `card-container` - `catalog`. And you could use mix. 
 More detail in video.
[video, timing 4:15](https://mate.academy/learn/css-advanced/bem#/video/911)

```suggestion
    <main>
      <div class="catalog">
        <section class="card catalog__card" data-qa="card">
```

2022-07-21 07:36 UTC, dellachaise commented on src/styles/blocks/cards.scss
> +    width: 944px;
Do not hardcode width, calculate it.

2022-07-21 07:36 UTC, dellachaise commented on src/styles/blocks/cards.scss
> +
it's not `card` element or modifier. It's a separate block witch use `-` in name consisted from 2 words.
Move this code to a separate file.
Rewatch info about naming in [this video](https://mate.academy/learn/css-advanced/bem#/video/920)

2022-07-21 16:36 UTC, dellachaise requested changes
Great progress 👍 

Please, add fixes according to last for this task comments.

2022-07-21 16:36 UTC, dellachaise commented on src/styles/blocks/catalog.scss
> +  margin: 0 auto;
You can't set margin to block, only for elements. You can use mix(set `page` class for body and add class `page__catalog` and move margin there.

 More details in video.
[video, timing 4:15] (https://mate.academy/learn/css-advanced/bem#/video/911)
![Screenshot 2022-07-21 at 19 28 44](https://user-images.githubusercontent.com/17098736/180265806-696f5c6e-b0db-4579-946c-0d4280919cca.png)
(https://mate.academy/learn/css-advanced/bem#/video/911)

2022-07-21 16:36 UTC, dellachaise commented on src/styles/blocks/header.scss
> +  margin: 0 auto;
Also, move margin to `.page__header`. More details in previous comment.

2022-07-21 16:36 UTC, dellachaise commented on src/styles/blocks/stars.scss
> +}
You should have possibility to change amount of active stars by changing a modifier. You could use code from `stars` task. 

And try to use cycle for
more detail in [video](https://mate.academy/learn/css-advanced/sass#/video/926)

2022-07-21 18:56 UTC, dellachaise approved these changes
Well done 👍  🔥

2024-01-15 20:09 UTC, closed without merging