created catalog
mate-academy/layout_catalog pull request #1917
Opened 2022-08-21 13:42 UTC by ihorandrianov

- [DEMO LINK](https://ihorandrianov.github.io/layout_catalog/)
- [TEST REPORT LINK](https://ihorandrianov.github.io/layout_catalog/report/html_report/)

2022-08-22 08:25 UTC, Anna-Borodaienko reviewed
Deleted so many folders for blocks, please. You need 1 folder - Blocks with all these files

2022-08-22 08:25 UTC, Anna-Borodaienko commented on src/index.html
> +          <a
```suggestion
          </div>

          <a
```

2022-08-22 08:25 UTC, Anna-Borodaienko commented on src/index.html
> +        <div class="card">
```suggestion
        </div>

        <div class="card">
```

2022-08-22 08:25 UTC, Anna-Borodaienko commented on src/styles/blocks/card/_card.scss
> +  display: flex;
```suggestion
.product-list {
  display: flex;
  justify-content: center;


  &__container {
    display: flex;
  
}
```

2022-08-22 08:25 UTC, Anna-Borodaienko commented on src/styles/blocks/card/_card.scss
> +    padding: 0 16px 24px;
```suggestion
    width: 100%;
    padding: 0 16px 24px;
```

2022-08-22 08:25 UTC, Anna-Borodaienko commented on src/styles/utils/_mixins.scss
> +  font-family: "Roboto", Helvetica, sans-serif;
We have this font-family on all our page. I'd add this line not to mixin, but to tag html

2022-08-22 08:25 UTC, Anna-Borodaienko commented on src/styles/blocks/card/_card.scss
> +}
```suggestion
  }
}
```

2022-08-22 08:25 UTC, Anna-Borodaienko commented on src/styles/blocks/card/_card.scss
> +}
Why do you add margin-top to last 4 elements? You have to add them margin-bottom 0px, as I understand the task.

2022-08-22 11:16 UTC, MaksimusCRS requested changes
I removed 2 cards and something went wrong 🥲 
<img width="1401" alt="image" src="https://user-images.githubusercontent.com/92159085/185908574-201dde12-5bb7-488c-90f9-6c2bc08b0ca0.png">

2022-08-22 11:55 UTC, Anna-Borodaienko commented
Of course! Because you add an additional margin-top to last 4 elements. Try to set all margins and paddings to the whole card. Your card's  elements must have only margin-bottom.

2022-08-22 14:39 UTC, MaksimusCRS requested changes
Still doesn't working 
<img width="1389" alt="image" src="https://user-images.githubusercontent.com/92159085/185948552-3d502e6b-7893-4b92-a140-f03205e31725.png">

2022-08-22 16:02 UTC, ihorandrianov commented
> Still doesn't working
> <img alt="image" width="1389" src="https://user-images.githubusercontent.com/92159085/185948552-3d502e6b-7893-4b92-a140-f03205e31725.png">

forget to deploy. Now should work

2022-08-23 13:39 UTC, MaksimusCRS requested changes

2022-08-23 13:39 UTC, MaksimusCRS commented on src/index.html
> +          </li>
Checklist #2

2022-08-23 13:39 UTC, MaksimusCRS commented on src/styles/blocks/card/_card.scss
> +  }
Checklist #10

2022-08-25 08:02 UTC, MaksimusCRS approved these changes

2022-08-25 08:02 UTC, MaksimusCRS commented on src/styles/utils/_variables.scss
> +$section-width: $card-width * 4 + $card-margin * 3;
Add variables for 4 and 3, i don't know why you use them

2023-10-31 12:07 UTC, closed without merging