need help
mate-academy/layout_catalog pull request #2051
Opened 2022-09-13 12:22 UTC by yurii-filiushkin

- [DEMO LINK](https://yurii-filiushkin.github.io/layout_catalog/)
- [TEST REPORT LINK](https://yurii-filiushkin.github.io/layout_catalog/report/html_report/)

Привіт.
Деякі тести не проходять.
І не зміг підключити файли через @use, лише @import (відразу все ламалось). І не зміг підключити змінні і плейсхолдери, в браузері писало що не може знайти змінну.
Завчасно дякую!

2022-09-14 13:40 UTC, stanislav-topikha requested changes
Limit container width
![image](https://user-images.githubusercontent.com/99331793/190168054-0ee09b5d-c4f1-4702-92cc-67cd09544979.png)

recheck ALL checklist points
https://github.com/mate-academy/layout_catalog/blob/master/checklist.md

move vars to other separate file
if you have any questions ask them in chat or on QnA

2022-09-14 13:40 UTC, stanislav-topikha commented on src/styles/main.scss
> +  font-family: Roboto, sans-serif;
only `box-sizing` is allowed inside `*` selector

2022-09-14 13:40 UTC, stanislav-topikha commented on src/styles/utils/_extends.scss
> +}
what the purpose of this?

2022-09-14 14:11 UTC, yurii-filiushkin commented on src/styles/utils/_extends.scss
> +}
Лише пробував підключати плейсхолдери, для тренування.
Практичної мети не мало.

2022-09-16 18:23 UTC, ivanchuk-yurii commented on src/index.html
> +          class="logo__image">
`>` should be on the new line under `<`

2022-09-16 18:28 UTC, ivanchuk-yurii commented on src/index.html
> +            <a href="Apple" class="nav__link is-active">Apple</a>
`is-active` is not correct, use BEM modifier

2022-09-16 18:28 UTC, ivanchuk-yurii commented on src/index.html
> +          <li class="nav__item"><a href="Video" class="nav__link">Video</a></li>
move `a` to new line

2022-09-16 18:29 UTC, ivanchuk-yurii commented on src/index.html
> +            <section class="card__price-value">$2,199</section>
why do you use `section` here? entire card as `section` has more sense

2022-09-16 18:32 UTC, ivanchuk-yurii commented on src/index.html
> +          <div class="card__name">
use `h` here

2022-09-17 06:46 UTC, yurii-filiushkin commented on src/index.html
> +          class="logo__image">
Виправив

2022-09-17 06:48 UTC, yurii-filiushkin commented on src/index.html
> +            <a href="Apple" class="nav__link is-active">Apple</a>
Додав як модифікатор, але залишив додатково `is-active`, тому що це умова задачі, без нього не проходять тести

2022-09-17 06:49 UTC, yurii-filiushkin commented on src/index.html
> +          <li class="nav__item"><a href="Video" class="nav__link">Video</a></li>
Ок

2022-09-17 06:50 UTC, yurii-filiushkin commented on src/index.html
> +            <section class="card__price-value">$2,199</section>
Я б зробив, але там різні шрифти. Як їх стилізувати, якщо в один блок покласти?

2022-09-17 06:50 UTC, yurii-filiushkin commented on src/index.html
> +          <div class="card__name">
Тут не зрозумів

2022-09-17 11:46 UTC, ivanchuk-yurii requested changes

2022-09-17 11:46 UTC, ivanchuk-yurii commented on src/index.html
> +          <div class="card__name">
tag `h1-6`

2022-09-17 11:46 UTC, ivanchuk-yurii commented on src/index.html
> +            <a href="Apple" class="nav__link is-active">Apple</a>
sorry for that)

2022-09-17 11:46 UTC, ivanchuk-yurii commented on src/index.html
> +            <section class="card__price-value">$2,199</section>
you can use `div` or `p`, not `section`

2022-09-17 15:20 UTC, yurii-filiushkin commented on src/index.html
> +          <div class="card__name">
Вибач, щось не можу зрозуміти що тут саме зробити.
Інші зауваження виправив.

2022-09-17 19:50 UTC, ivanchuk-yurii commented on src/index.html
> +          <div class="card__name">
`<h2 class"card__name">`

2022-09-18 11:03 UTC, ivanchuk-yurii approved these changes

2024-03-13 06:48 UTC, closed without merging