Catalog completed
mate-academy/layout_catalog pull request #2140
Opened 2022-10-05 15:25 UTC by Largoxoxo

- [DEMO LINK](https://Largoxoxo.github.io/layout_catalog/)
- [TEST REPORT LINK](https://Largoxoxo.github.io/layout_catalog/report/html_report/)

2022-10-05 15:36 UTC, Viiktorrr commented on src/styles/blocks/pr-card.scss
> +;
move the semicolon

2022-10-05 15:38 UTC, Viiktorrr approved these changes
good work beautiful code!!!

2022-10-06 15:37 UTC, mkyloa requested changes
i see no problems with border color, your container lacks paddings, that's why tests fail
check out qna channel, the problem was discussed there

2022-10-06 16:01 UTC, Largoxoxo commented
UPD
Fixed all issues. Initially I though it was a bad idea to specify width with @media, since you can simply add auto margins and the content will always be centered properly for bigger resolution. Eventually that was a solution. All tests passed.

2022-10-11 07:06 UTC, denys-danyliuk approved these changes

2022-10-11 07:06 UTC, denys-danyliuk commented on src/index.html
> +        >Buy
```suggestion
        >
          Buy
```

2022-10-11 07:06 UTC, denys-danyliuk commented on src/styles/utils/_normalize.scss
> +  font-style: normal;
you could add this styles to html, there is no need to add the to every tag

2022-10-11 07:06 UTC, denys-danyliuk commented on src/styles/blocks/pr-card.scss
> +  padding: 32px 16px 16px;
8 point in checklist

2022-10-11 07:06 UTC, denys-danyliuk commented on src/styles/blocks/pr-card.scss
> +  margin: 0 auto;
8 point in checklist

2022-10-11 07:06 UTC, denys-danyliuk commented on src/styles/blocks/pr-card.scss
> +.price {
9 point in checklist

2022-10-11 07:06 UTC, denys-danyliuk commented on src/styles/blocks/pr-card.scss
> +.card {
9 point in checklist

2022-10-11 08:57 UTC, Largoxoxo commented on src/styles/blocks/pr-card.scss
> +.card {
Fixed all issues.

2026-04-05 11:42 UTC, closed without merging