develop
mate-academy/layout_catalog pull request #215
Opened 2019-10-23 11:20 UTC by Igorskiy

- [DEMO LINK](https://igorskiy.github.io/layout_catalog/)
- [TEST REPORT LINK](https://igorskiy.github.io/layout_catalog/report/html_report/)

2019-10-23 14:59 UTC, vkryvytskyi requested changes
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/38065883/67406337-9d1c9c00-f5be-11e9-914a-6be05d0df53e.png">
Что-то все куда-то уехало

2019-10-23 14:59 UTC, vkryvytskyy commented on src/index.html
> +      <nav class="nav__content">
Семантически правильная структура nav'бара:
```
<nav>
  <ul>
    <li>
      <a>
```

2019-10-23 14:59 UTC, vkryvytskyy commented on src/styles/navbar.scss
> +  .nav__content {
Используй `&__content` вместо `.nav__content`

2019-10-24 15:21 UTC, vkryvytskyi approved these changes

2026-03-03 10:07 UTC, closed without merging