catalog
mate-academy/layout_catalog pull request #2183
Opened 2022-10-21 19:53 UTC by ruslan-kasinets

2022-10-23 10:12 UTC, polosanya requested changes
DEMO and TEST links are absent. Please fix it so we can check your work properly.
Also please check my comments.

2022-10-23 10:12 UTC, polosanya commented on src/index.html
> +            >
```suggestion
            <a 
              href="Laptops & computers"
              class="nav__link"
              data-qa="nav-hover"
            >
```

2022-10-23 10:12 UTC, polosanya commented on src/styles/blocks/stars.scss
> +    // height: 16px;
Delete useless comments

2022-10-23 10:12 UTC, polosanya commented on src/styles/blocks/card.scss
> +  display: flex;
```suggestion
.card {
  display: flex;
```

2022-10-23 10:12 UTC, polosanya commented on src/styles/blocks/card.scss
> +  border: 1px solid #f3f3f3;
Add variables for every color on page

2022-10-23 10:12 UTC, polosanya commented on src/styles/blocks/card.scss
> +    text-align: center;
Pay attention to css properties order
https://9elements.com/css-rule-order/

2022-10-24 10:53 UTC, ruslan-kasinets commented on src/styles/blocks/card.scss
> +    text-align: center;
DEMO and TEST links are absent.Не знаю чого так,ссилки виправив,коміт зробив,запушив.

2022-10-25 06:54 UTC, polosanya approved these changes
Well done! I'm approving your work, just please add variable for one more color)

2022-10-25 06:54 UTC, polosanya commented on src/styles/blocks/card.scss
> +  border: 1px solid #f3f3f3;
Border color is still without variable

2022-10-25 08:01 UTC, ruslan-kasinets commented
Ok.Tnx ) Just in the checklist is said: 11.[SASS] - use variables for the main values so that you'll be able to reuse them and give them descriptive names. But don't overuse them, **don't create variable for the value that's used just once.** .This color is only used once )

2022-10-25 18:44 UTC, polosanya commented
> Ok.Tnx ) Just in the checklist is said: 11.[SASS] - use variables for the main values so that you'll be able to reuse them and give them descriptive names. But don't overuse them, **don't create variable for the value that's used just once.** .This color is only used once )

It is better to always use variables for colors. If someone later wants to change the colors on the page, he will not need to search for them in all files, it is enough to change them in one place.

2025-06-27 16:03 UTC, closed without merging