tasks were implemented
mate-academy/layout_catalog pull request #2199
Opened 2022-10-27 09:10 UTC by Serhii-Soloshych

- [DEMO LINK](https://Serhii-Soloshych.github.io/layout_catalog/)
- [TEST REPORT LINK](https://Serhii-Soloshych.github.io/layout_catalog/report/html_report/)

2022-10-28 09:38 UTC, stanislav-topikha requested changes
add paddings 
![image](https://user-images.githubusercontent.com/99331793/198556402-8a856d86-bbff-41be-8908-4bd930c22590.png)

![image](https://user-images.githubusercontent.com/99331793/198556484-c32858d7-d7d2-487d-8add-4b0e4af6d6d5.png)

2022-10-29 07:20 UTC, SanyaBratashchuk requested changes
Linsk are broken

2022-10-29 07:31 UTC, Serhii-Soloshych commented
> Linsk are broken

Hi, I think that because i did some mess in my git branches. Could you help me to fix them? 
<img width="752" alt="image" src="https://user-images.githubusercontent.com/115535911/198819705-4ca1d1f9-67fd-4570-8e24-0a887eb6c2a9.png">

2022-10-29 10:35 UTC, closed without merging

2022-10-29 19:01 UTC, ivanchuk-yurii commented on src/styles/blocks/product-card.scss
> +    color: #060b35;
move all colors into variables

2022-10-29 19:01 UTC, ivanchuk-yurii commented
don't close your prs

2022-10-30 01:54 UTC, Serhii-Soloshych commented
> don't close your prs

I know. But there was unexpectable problem. I made some mess in my branches, and I couldn't fix it. I asked another mentor to help me, but the easiest way was to remove my pull request.