catalog
mate-academy/layout_catalog pull request #2229
Opened 2022-11-02 20:49 UTC by anastasia-radchencko

https://anastasia-radchencko.github.io/layout_catalog/
https://anastasia-radchencko.github.io/layout_catalog/report/html_report/

2022-11-04 15:07 UTC, DarkMistyRoom requested changes
Good, but pay attention to this point 
![image](https://user-images.githubusercontent.com/98764641/200006941-aa26e962-d596-47a9-b0b4-4ad04192dd03.png)
![image](https://user-images.githubusercontent.com/98764641/200007042-9a34aa8d-6d17-420e-a8dd-813b8db8e3b2.png)

and it should look like this when you add a new item
![image](https://user-images.githubusercontent.com/98764641/200008276-271baa51-cabf-427b-8fc5-3e2dcd30f136.png)

2022-11-06 11:22 UTC, SanyaBratashchuk requested changes
Nothing should be broken if I add more cards 
![image](https://user-images.githubusercontent.com/97547824/200167721-79c2c9dd-d175-4b34-b02f-6a01433e7969.png)

2022-11-07 09:47 UTC, stanislav-topikha requested changes

2022-11-07 09:47 UTC, stanislav-topikha commented on src/styles/normalize.scss
> +  font-family: "Roboto", sans-serif;
add fallback font

2022-11-07 09:47 UTC, stanislav-topikha commented on src/styles/blocks/card.scss
> +  }
No external positioning for BEM blocks, event through modifiers, move to element and mix to card

2022-11-07 09:47 UTC, stanislav-topikha commented on src/styles/blocks/card.scss
> +  &-container {
what is this? BEM? 
![image](https://user-images.githubusercontent.com/99331793/200279245-74e2f0e8-81f7-4ae2-8232-4eb393b5e1d4.png)
why does it located outside of block?

2022-11-09 08:51 UTC, closed without merging