Add catalog
mate-academy/layout_catalog pull request #2278
Opened 2022-11-08 16:32 UTC by Ruslan-Pashkov

[DEMO LINK](https://ruslan-pashkov.github.io/layout_catalog/)
[TEST REPORT LINK](https://ruslan-pashkov.github.io/layout_catalog/report/html_report/)

2022-11-08 18:12 UTC, AntonMartynes approved these changes
I have no comments on this work

2022-11-09 13:53 UTC, solaryasha requested changes

2022-11-09 13:53 UTC, solaryasha commented on src/index.html
> +            alt="iMac image"
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/32794096/200847836-2fbe8e89-0b99-4b1f-97f3-7d0a3052408e.png">

2022-11-09 14:25 UTC, solaryasha approved these changes
Good job!

2023-02-20 15:03 UTC, closed without merging