fixed bugs
mate-academy/layout_catalog pull request #2281
Opened 2022-11-08 17:42 UTC by batstolya

- [DEMO LINK](https://batstolya.github.io/layout_catalog/)
- [TEST REPORT LINK](https://batstolya.github.io/layout_catalog/report/html_report/)

2022-11-08 20:07 UTC, romanblyashuk94 requested changes

2022-11-08 20:07 UTC, romanblyashuk94 commented on src/styles/blocks/nav.scss
> +    color: #000;
Nav links color is not black any more
```suggestion
    color: $color-regular;
```

2022-11-08 20:07 UTC, romanblyashuk94 commented on src/styles/utils/_reset.scss
> +  font-family: "Roboto", sans-serif;
you duplicated this in normalize file.
need to remove from here.

2022-11-09 11:55 UTC, solaryasha approved these changes
Good job !

2022-11-09 11:55 UTC, solaryasha commented on src/index.html
> +          alt="logo"
```suggestion
          alt="logo of the Moyo website"
```

2022-11-09 11:55 UTC, solaryasha commented on src/index.html
> +          </a>
I agree with Roman

2022-11-09 11:55 UTC, solaryasha commented on src/styles/blocks/catalog.scss
> +    width: 944px;
It's better to calculate this value using variables/function

2022-11-09 11:55 UTC, solaryasha commented on src/styles/blocks/header.scss
> +  .logo {
```suggestion
  &__logo {
```

2022-11-09 11:55 UTC, solaryasha commented on src/styles/blocks/nav.scss
> +.is-active {
Let's create a separate file for this BEM block

2022-11-09 11:55 UTC, solaryasha commented on src/styles/blocks/stars.scss
> +  @for $starCount from 1 through 5 {
🔥

2026-07-13 23:09 UTC, closed without merging