base bild
mate-academy/layout_catalog pull request #2306
Opened 2022-11-09 16:57 UTC by oksanatytanych

- [DEMO LINK](https://oksanatytanich.github.io/layout_catalog/)
- [TEST REPORT LINK](https://oksanatytanich.github.io/layout_catalog/report/html_report/)

2022-11-11 14:55 UTC, oksanatytanych commented
- [DEMO LINK](https://oksanatytanych.github.io/layout_catalog/)
- [TEST REPORT LINK](https://oksanatytanych.github.io/layout_catalog/report/html_report/)

2022-11-11 15:51 UTC, Andrey-Ivanov999 approved these changes
I Think thats good:)

2022-11-11 16:33 UTC, ivan-kadykalo requested changes

2022-11-11 16:33 UTC, ivan-kadykalo commented on src/index.html
> +      <a class="header__logo" href="#home">
Checlist

2022-11-11 16:33 UTC, ivan-kadykalo commented on src/index.html
> +        Buy
Keep indentation

2022-11-14 16:08 UTC, Ihor-Karpyn approved these changes

2022-12-08 09:24 UTC, closed without merging