styling adjusted
mate-academy/layout_catalog pull request #2343
Opened 2022-11-15 15:21 UTC by Sergei-Nikolaienko

https://Sergei-Nikolaienko>.github.io/layout_catalog/
https://Sergei-Nikolaienko>.github.io/layout_catalog/report/html_report/

2022-11-15 15:22 UTC, Sergei-Nikolaienko commented
NPM won't run for some reason - was asked to create a pull request anyway to check the finished task.

2022-11-16 17:59 UTC, Viktor-Kost requested changes
Well done!
Just apply some recommendations to improve your code

2022-11-16 17:59 UTC, Viktor-Kost commented on readme.md
> +- [DEMO LINK](https://Sergei-Nikolaienko>.github.io/layout_catalog/)
Here you have typos. Use Sergei-Nikolaienko instead of Sergei-Nikolaienko>

2022-11-16 17:59 UTC, Viktor-Kost commented on src/styles/utils/normalize.scss
> +  list-style: none;
This rule is for `ul`, so then you will need to use this rule again for example here 
```
.nav {
  margin: 0;
  padding: 0;
  display: flex;
  list-style: none;
}
```

2022-11-16 17:59 UTC, Viktor-Kost commented on src/styles/blocks/stars.scss
> +.stars--1 div:nth-child(-n+1),
Here, just as recommendation, we can use a sass loop [link](https://sass-lang.com/documentation/at-rules/control/for)

2022-11-16 17:59 UTC, Viktor-Kost commented on src/styles/blocks/header.scss
> +.nav a:hover {
Please, use style selectors instead of tag one

2022-11-22 11:49 UTC, Sergei-Nikolaienko commented
> 
![image](https://user-images.githubusercontent.com/116793918/203306821-544fe072-c47b-435f-945e-331c9ebfd031.png)
have deployed, not sure why it won't show up

2022-11-22 16:41 UTC, Viktor-Kost requested changes
Good job!

And, please, check your test report, cause you have some diffs there

2022-11-22 18:05 UTC, Viktor-Kost reviewed
Have you updated a link for tests, cause there is still a link with failed test?

2022-11-26 10:59 UTC, OlEzhA0 requested changes
Good job! Let's resolve issues and take a look why some tests failed

2022-11-26 10:59 UTC, OlEzhA0 commented on src/index.html
> +            <a class="nav__item nav__item--is--active is-active" href="#">Apple</a>
you don't use class `is-active`.

also with BEM convention we should give name for modifier with one dash
```suggestion
            <a class="nav__item nav__item--is-active" href="#">Apple</a>
```

use this rule for future
`block-name__elem-name--mod-name--mod-val`

2022-11-26 10:59 UTC, OlEzhA0 commented on src/index.html
> +          <li class="nav__list">
I'm not sure that is good class name for element
each tag `li` is item, not a list

you can use class `nav__list` for `ul` tag

2022-11-26 10:59 UTC, OlEzhA0 commented on src/index.html
> +            </a>
```suggestion
            <a 
              class="nav__item" 
              data-qa="nav-hover" 
              href="#"
            >
              Laptops & Computers
            </a>
```

2022-11-26 10:59 UTC, OlEzhA0 commented on src/index.html
> +            <p class="card__reviews-no">Reviews: 5</p>
what do you mean `card__reviews-no`?

2022-11-26 10:59 UTC, OlEzhA0 commented on src/index.html
> +          </a>
```suggestion
          <a 
            class="card__buy-cta" 
            href="#" 
            data-qa="card-hover"
          >
            Buy
          </a>
```

2022-11-26 10:59 UTC, OlEzhA0 commented on src/styles/blocks/card.scss
> +  border: 1px solid #f3f3f3;
add this color to variables

2022-11-26 10:59 UTC, OlEzhA0 commented on src/styles/blocks/card.scss
> +  background: white;
use the sixteen Named colors `#fff` and you can also put it to vars

2022-11-26 10:59 UTC, OlEzhA0 commented on src/styles/blocks/card.scss
> +  }
you can try to use `mixins` to create some typography styles, put there color, font-size, line-height, font-weight

2022-11-26 10:59 UTC, OlEzhA0 commented on src/styles/blocks/header.scss
> +}
add class for header

2022-11-26 10:59 UTC, OlEzhA0 commented on src/styles/blocks/header.scss
> +}
it can be `header__logo` etc

2022-11-26 10:59 UTC, OlEzhA0 commented on src/styles/blocks/header.scss
> +    padding-left: 20px;
add spaces for other elements with margin

2022-11-26 10:59 UTC, OlEzhA0 commented on src/styles/utils/_variables.scss
> +$catalog-width: 4 * $cards-width + 3 * $cards-gap;
what is 4 and 3? mb create constants for them

2022-11-26 10:59 UTC, OlEzhA0 commented on src/styles/utils/_variables.scss
> +}
👍🏼

2022-11-26 10:59 UTC, OlEzhA0 commented on src/styles/blocks/header.scss
> +    text-decoration: none;
you reseted this style for all tags `a`

2022-11-28 13:19 UTC, Virass approved these changes

2023-01-12 09:56 UTC, closed without merging