First commit - Done with some errors
mate-academy/layout_catalog pull request #2344
Opened 2022-11-16 20:13 UTC by RVDotsenko

- [DEMO LINK](https://RVDotsenko.github.io/layout_catalog/)
- [TEST REPORT LINK](https://RVDotsenko.github.io/layout_catalog/report/html_report/)

2022-11-17 17:37 UTC, polosanya requested changes
You need to refresh your knowledge of BEM methodology because your BEM structure is incorrect for now. Please check these links:
https://css-tricks.com/bem-101/
https://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/

2022-11-17 17:37 UTC, polosanya commented on src/index.html
> +            >
You can leave it in one line if there are fewer than 3 attributes and they don't take too much width
```suggestion
            <a class="is-active" href="#Apple">
```

2022-11-17 17:37 UTC, polosanya commented on src/index.html
> +                class="product-image__image"
```suggestion
          <div class="card">
            <div class="card__image-container">
              <img
                class="card__image"
```
Please check your BEM structure
It is not correct now
https://mate-academy.github.io/style-guides/htmlcss.html#oocss-and-bem

2022-11-19 15:58 UTC, AlisaVlasova requested changes

2022-11-19 15:58 UTC, AlisaVlasova commented on src/index.html
> +        <a href="#" class="logo__link">
```suggestion
    <header class="header">
      <div class="header__logo logo">
        <a href="#" class="logo__link">
```

2022-11-19 15:58 UTC, AlisaVlasova commented on src/index.html
> +            <a class="is-active" href="#Apple">
```suggestion
        <ul class="nav__list">
          <li class="nav__value">
            <a class="nav__link is-active" href="#Apple">
```

2022-11-19 15:58 UTC, AlisaVlasova commented on src/styles/main.scss
> +@import "./blocks/page.scss";
++

2022-11-19 22:40 UTC, ivanchuk-yurii requested changes
it doesn't display correctly
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/53611910/202874314-02936609-f8b9-49ad-b802-67ea0f6320a0.png">

2022-11-19 22:40 UTC, ivanchuk-yurii commented on src/styles/blocks/header/_logo.scss
> +.header__logo {
should be in `header.scss`

2022-11-19 22:40 UTC, ivanchuk-yurii commented on src/styles/blocks/header/_navigation.scss
> +    cursor: pointer;
link is pointer by default

2022-11-19 22:40 UTC, ivanchuk-yurii commented on src/styles/blocks/header/_navigation.scss
> +    top: 19px;
```suggestion
    bottom: 0;
```

2022-11-19 22:40 UTC, ivanchuk-yurii commented on src/styles/blocks/main/card/_button.scss
> +    cursor: pointer;
link is pointer by default

2022-11-19 22:40 UTC, ivanchuk-yurii commented on src/styles/blocks/main/card/_button.scss
> +    width: 166px;
don't hardcode width here

2022-11-19 22:40 UTC, ivanchuk-yurii commented on src/styles/blocks/main/card/_card.scss
> +  letter-spacing: normal;
do you need this?

2022-11-19 22:40 UTC, ivanchuk-yurii commented on src/styles/blocks/main/card/_price.scss
> +    font-weight: 400;
it's default value

2022-11-19 22:40 UTC, ivanchuk-yurii commented on src/styles/blocks/main/card/_rating.scss
> +.stars--4 > :nth-child(-n + 4) {
should work for others numbers of stars

2022-11-19 22:40 UTC, ivanchuk-yurii commented on src/styles/blocks/main/card/_rating.scss
> +  background-image: url(../images/star.svg);
combine into `background` property

2022-11-19 22:40 UTC, ivanchuk-yurii commented on src/styles/blocks/main/card/_text.scss
> +    font-weight: 400;
it's default value

2022-11-19 22:40 UTC, ivanchuk-yurii commented on src/styles/blocks/page.scss
> +  letter-spacing: -0.36em;
do you need this?

2022-11-19 22:40 UTC, ivanchuk-yurii commented on src/styles/utils/_variables.scss
> +$colorMain: #060b35;
use kebab-case for variable naming
```suggestion
$color-main: #060b35;
```

2022-11-19 22:40 UTC, ivanchuk-yurii commented on src/index.html
> +      <div class="logo">
do you need this block?

2022-11-19 22:40 UTC, ivanchuk-yurii commented on src/index.html
> +            <a class="is-active" href="#Apple">
not fixed

2022-11-19 22:40 UTC, ivanchuk-yurii commented on src/index.html
> +              apple
```suggestion
              Apple
```
it's better to uppercase first letter

2022-11-19 22:40 UTC, ivanchuk-yurii commented on src/index.html
> +          <div class="card__container card__container--image">
these `card__container`s are redundant

2022-11-20 16:10 UTC, SanyaBratashchuk requested changes

2022-11-20 16:10 UTC, SanyaBratashchuk commented on src/styles/blocks/main/card/_image.scss
> +}
move all elements of Card BEM blok to the card.scss

2022-11-20 16:10 UTC, SanyaBratashchuk commented on src/index.html
> +              <div class="stars-star"></div>
```suggestion
              <div class="stars__star"></div>
              <div class="stars-star"></div>
              <div class="stars-star"></div>
              <div class="stars-star"></div>
              <div class="stars-star"></div>
```

2022-11-20 16:10 UTC, SanyaBratashchuk commented on src/styles/blocks/main/card/_rating.scss
> +}
Reuse all styles from task with stars and move each BEM block to the separate file.

2022-11-23 11:51 UTC, DarkMistyRoom requested changes
The catalog shouldn't go over the left side.
![image](https://user-images.githubusercontent.com/98764641/203538226-ba01a4ae-e34a-4d83-bb32-07d69175ddcd.png)

2022-11-23 11:51 UTC, DarkMistyRoom commented on src/styles/blocks/main/_star.scss
> +.stars__star {
Where is stars block? You should have `stars `selector

2022-11-23 11:51 UTC, DarkMistyRoom commented on src/styles/blocks/header/_header.scss
> +.header__logo {
Use nesting

2022-11-23 11:51 UTC, DarkMistyRoom commented on src/styles/blocks/header/_navigation.scss
> +.nav__list {
Where is nav block? I see only elements, but they can't exist without a block, according to BEM

2022-11-23 11:51 UTC, DarkMistyRoom commented on src/styles/blocks/main/_star.scss
> +@for $index from 1 through $active-stars {
Same comment. You should reuse stars block from the previous task
![image](https://user-images.githubusercontent.com/98764641/203539825-515bb46f-de96-4648-a531-808437c8c101.png)

2023-11-02 17:58 UTC, closed without merging