Catalog
mate-academy/layout_catalog pull request #2372
Opened 2022-11-26 12:46 UTC by mdm-21

- [DEMO LINK](https://mdm-21.github.io/layout_catalog/)
- [TEST REPORT LINK](https://mdm-21.github.io/layout_catalog/report/html_report/)

2022-11-27 09:28 UTC, SanyaBratashchuk requested changes
Text disappears on hover 
![image](https://user-images.githubusercontent.com/97547824/204127454-e0ba2e03-2aa0-4bb1-9f03-817e4592c7eb.png)

2022-11-27 09:28 UTC, SanyaBratashchuk commented on src/styles/blocks/card.scss
> +  }
BEM. Do not set external geometry directly to the BEM block

2022-11-27 09:28 UTC, SanyaBratashchuk commented on src/index.html
> +      <nav class="header__nav">
nav should be different BEM block

2022-11-27 17:45 UTC, closed without merging

2022-11-28 00:54 UTC, ivanchuk-yurii commented
don't close prs