Catalog was created
mate-academy/layout_catalog pull request #2422
Opened 2022-12-07 14:35 UTC by NazariiAlieksieiev

2022-12-07 14:36 UTC, NazariiAlieksieiev commented
- [DEMO LINK](https://NazariiAlieksieiev.github.io/layout_catalog/)
- [TEST REPORT LINK](https://NazariiAlieksieiev.github.io/layout_catalog/report/html_report/)

2022-12-07 16:58 UTC, Viktor-Kost requested changes

2022-12-07 16:58 UTC, Viktor-Kost commented on src/styles/utils/_reset.scss
> +  color: $main-text-color;
to body selector
```suggestion

```

2022-12-08 16:25 UTC, Viktor-Kost approved these changes
GJ!

2024-07-27 11:24 UTC, closed without merging