beta version
mate-academy/layout_catalog pull request #2468
Opened 2022-12-13 06:44 UTC by Anton-Zhytonbaiev

- [DEMO LINK](https://Anton-Zhytonbaiev.github.io/layout_catalog/)
- [TEST REPORT LINK](https://Anton-Zhytonbaiev.github.io/layout_catalog/report/html_report/)

2022-12-13 13:53 UTC, vanst1 approved these changes
Good job:)
Check comments)

2022-12-13 13:53 UTC, vanst1 commented on src/index.html
> +      <div class="cards">
move class="cards" to the main tag

2022-12-13 13:53 UTC, vanst1 commented on src/styles/main.scss
> +}
create `_reset.scss` file for this

2022-12-13 13:53 UTC, vanst1 commented on src/styles/main.scss
> +}
create `_normalize.scss` file for this

2022-12-13 13:53 UTC, vanst1 commented on src/styles/blocks/cards.scss
> +}
checklist 10, use `&` :

```
.cards {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  margin: 0 auto;
  padding-top: 50px;
  width: getCountWidth($width-card, $space);


  &__card {
  margin-right: 48px;
  margin-bottom: 46px;
}

  &__card:nth-child(4n) {
  margin-right: 0;
}
}
```

2022-12-13 13:53 UTC, vanst1 commented on src/styles/blocks/header.scss
> +
create `_reset.scss` file for this

2022-12-13 13:53 UTC, vanst1 commented on src/styles/blocks/header.scss
> +}
create `_normalize.scss` file for this

2022-12-13 14:23 UTC, Denchepornyuk requested changes

2022-12-13 14:23 UTC, Denchepornyuk commented on src/index.html
> +          <li class="header__item">
nav should be a separate bem block, create `nav` block and elements from this block

2022-12-13 14:23 UTC, Denchepornyuk commented on src/index.html
> +      <div class="cards">
```suggestion
      <div class="catalog">
```

2022-12-13 14:23 UTC, Denchepornyuk commented on src/index.html
> +          </p>
do you need `name` and `code` separated classes?

2022-12-13 14:23 UTC, Denchepornyuk commented on src/styles/blocks/card.scss
> +}
you scss nesting with `&`

2022-12-13 14:23 UTC, Denchepornyuk commented on src/styles/blocks/card.scss
> +}
remove class `name` and move this code to  `card__name`
you can add margins for bem elements, you can't add margins only for bem blocks

2022-12-13 14:23 UTC, Denchepornyuk commented on src/styles/blocks/card.scss
> +}
each bem block should be in separate file

2022-12-13 14:23 UTC, Denchepornyuk commented on src/styles/blocks/header.scss
> +
agree, let's create _reset file

2022-12-14 12:46 UTC, Denchepornyuk requested changes

2022-12-14 12:46 UTC, Denchepornyuk commented on src/index.html
> +      <nav>
nav should be a separate bem block

2022-12-14 14:22 UTC, Denchepornyuk approved these changes

2024-01-05 10:10 UTC, closed without merging