create catalog
mate-academy/layout_catalog pull request #2507
Opened 2022-12-22 10:50 UTC by andrewchornobai

2022-12-22 17:10 UTC, tetiana-ivanchenko requested changes
add your demo and test-report links, please

2022-12-22 19:22 UTC, andrewchornobai commented
Links in readme file didn't works or what?

2022-12-22 19:25 UTC, andrewchornobai commented
Links in readme file didn't works or what?

2022-12-27 09:06 UTC, andrewchornobai commented
demo - https://andrewchornobai.github.io/layout_catalog/
 test-report - https://andrewchornobai.github.io/layout_catalog/report/html_report/

2023-01-03 11:37 UTC, andrewchornobai commented
i think the link don't work, maybe it's wrong path in README file by DEMO LINK and TEST REPORT LINK

2023-01-03 18:30 UTC, andrewchornobai commented
PR - https://github.com/mate-academy/layout_catalog/compare/master...andrewchornobai:layout_catalog:develop

2023-01-05 19:06 UTC, SanyaBratashchuk requested changes
Nothing should be broken if I add more cards 
![image](https://user-images.githubusercontent.com/97547824/210860676-9492949c-b764-4a16-8131-d5d44be6b630.png)

2023-01-06 18:56 UTC, SanyaBratashchuk requested changes

2023-01-06 18:56 UTC, SanyaBratashchuk commented on src/styles/main.scss
> +  padding: 0;
Do not apply any rules to the `*` selector except `box-sizing`

2023-01-06 18:56 UTC, SanyaBratashchuk commented on src/styles/main.scss
> +.header {
move each BEM block to the separate file

2023-01-06 18:56 UTC, SanyaBratashchuk commented on src/styles/main.scss
> +.header {
FIx it everywhere

2023-01-06 18:56 UTC, SanyaBratashchuk commented on src/styles/main.scss
> +  }
use scss loop

2023-01-07 09:54 UTC, ViktorHavryliuk requested changes
Add some separation between sibling html tags (checklist p.2):
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/118751034/211144598-af245817-f422-482f-9635-1df7ee362ba8.png">

2023-01-07 09:54 UTC, ViktorHavryliuk commented on src/index.html
> +        >
```suggestion
        <img 
          class="header__moyoLogo" 
          src="images/logo.png" 
          alt="moyo_logo"
        >
```

2023-01-07 09:54 UTC, ViktorHavryliuk commented on src/index.html
> +            >Apple</a>
```suggestion
            <a 
              class="header__links is-active" 
              href="#"
            >
              Apple
            </a>
```

2023-01-07 09:54 UTC, ViktorHavryliuk commented on src/styles/blocks/card.scss
> +    color: #060b35;
move commonly used colors to variables

2023-01-10 10:18 UTC, DarkMistyRoom requested changes

2023-01-10 10:18 UTC, DarkMistyRoom commented on src/index.html
> +      <nav class="header__nav">
Add empty lines between multiline sibling blocks of HTML

2023-01-10 10:18 UTC, DarkMistyRoom commented on src/index.html
> +            </a>
```suggestion
            >
              Apple
            </a>
```

2023-01-10 10:18 UTC, DarkMistyRoom commented on src/index.html
> +            </div>
you shouldn't make it an element of `card`. just reuse the whole block

2023-01-10 10:18 UTC, DarkMistyRoom commented on src/index.html
> +            <div class="card__text-revies">Reviews: 5</div>
fix it for all text elements

2023-03-12 16:17 UTC, andrewchornobai commented on src/index.html
> +            </div>
![image](https://user-images.githubusercontent.com/61494193/224557659-33aa0c22-b7d6-4064-9fdd-24fc259ddb71.png)
![image](https://user-images.githubusercontent.com/61494193/224557694-88989e54-aca0-4e19-b233-837a5a77553c.png)

2023-03-12 16:54 UTC, Volodymyr-Melnyk-Fron10der requested changes
fix previous comments plz, and if you have questions - ask them in the chat

2023-03-12 17:11 UTC, andrewchornobai commented
> fix previous comments plz, and if you have questions - ask them in t

2023-03-12 17:11 UTC, closed without merging