Develop
mate-academy/layout_catalog pull request #2559
Opened 2023-01-10 21:48 UTC by maxonshev

- [DEMO LINK](https://maxonshev.github.io/layout_catalog/)
- [TEST REPORT LINK](https://maxonshev.github.io/layout_catalog/report/html_report/)

2023-01-11 19:24 UTC, SanyaBratashchuk requested changes
Nothing should be broken if I add more cards 
![image](https://user-images.githubusercontent.com/97547824/211899023-96e67ad5-2210-435f-b10e-510fdec4f43c.png)

2023-01-13 10:54 UTC, Bohdan-Maksymiuk requested changes
Good job, lets fix comments

2023-01-13 10:54 UTC, Bohdan-Maksymiuk commented on src/index.html
> +      <div class="header__logo">
```suggestion
    <header class="page__header header">
      <div class="header__logo">
```

2023-01-13 10:54 UTC, Bohdan-Maksymiuk commented on src/index.html
> +          src="images/imac.jpeg"
```suggestion
      </div>
      
      <div class="catalog__card card">
        <img 
          src="images/imac.jpeg" 
```
add empty lines only between siblings

2023-01-13 10:54 UTC, Bohdan-Maksymiuk commented on src/styles/blocks/nav.scss
> +    padding: 22.5px 0;
do not use non-integer values for px

2023-01-14 11:58 UTC, SanyaBratashchuk approved these changes

2025-03-07 10:52 UTC, closed without merging