created catalog
mate-academy/layout_catalog pull request #2642
Opened 2023-01-31 07:52 UTC by Nordexz

- [DEMO LINK](https://Nordexz.github.io/layout_catalog/)
- [TEST REPORT LINK](https://Nordexz.github.io/layout_catalog/report/html_report/)

2023-01-31 20:21 UTC, VadKol commented on src/index.html
> +          APPLE A1419 iMac 27" Retina 5K Monoblock (MNED2UA/A)
use &quot; for having double-quotes " (change it in all of cards)

2023-01-31 20:25 UTC, VadKol commented on src/index.html
> +          buy
use 2 spaces (or 1 tab (if your tab in IDE settings is 2 spaces)) (do it in all of links in cards)

2023-01-31 20:34 UTC, VadKol requested changes
Fix changes

2023-01-31 20:57 UTC, VadKol commented
GJ!

2023-01-31 20:58 UTC, VadKol approved these changes

2023-02-03 13:31 UTC, Andr1yK approved these changes

2025-09-29 20:14 UTC, closed without merging