catalog
mate-academy/layout_catalog pull request #2657
Opened 2023-02-01 14:13 UTC by SergeyShapovalenko

- [DEMO LINK](https://SergeyShapovalenko.github.io/layout_catalog/)
- [TEST REPORT LINK](https://SergeyShapovalenko.github.io/layout_catalog/report/html_report/)

2023-02-01 18:57 UTC, ViktorHavryliuk requested changes
Good work, but there are some small suggestions, please fix those

2023-02-01 18:57 UTC, ViktorHavryliuk commented on src/index.html
> +            href="BUY"
If you click on link now it sends user to non-existing page 
```suggestion
            href="#" 
```

2023-02-01 18:57 UTC, ViktorHavryliuk commented on src/index.html
> +        >
```suggestion
          <img 
             class="card__logo" 
             src="images/imac.jpeg" 
             alt="APPLE A1419 iMac 27 Retina 5K Monoblock (MNED2UA/A)"
           >
```

2023-02-01 18:57 UTC, ViktorHavryliuk commented on src/styles/blocks/card.scss
> +  max-width: $card-windth;
Also fix typo in variable's name
```suggestion
  width: $card-width;
```

2023-02-01 18:57 UTC, ViktorHavryliuk commented on src/styles/blocks/catalog.scss
> +
remove second empty line

2023-02-01 18:57 UTC, ViktorHavryliuk commented on src/styles/blocks/header.scss
> +
Remove empty line before closing bracket

2023-02-03 08:10 UTC, tetiana-ivanchenko requested changes

2023-02-03 08:10 UTC, tetiana-ivanchenko commented on src/styles/blocks/card.scss
> +  &:nth-child(8) {
```suggestion
  &:nth-child(4),
  &:nth-child(8) {
```

2023-02-04 09:52 UTC, SanyaBratashchuk approved these changes

2023-11-15 11:48 UTC, closed without merging