catalog was added
mate-academy/layout_catalog pull request #2667
Opened 2023-02-02 15:52 UTC by Vo7kov

https://vo7kov.github.io/layout_catalog/
https://vo7kov.github.io/layout_catalog/report/html_report/

2023-02-03 08:21 UTC, vlad-demchuk requested changes
Looks good! Just small fixes

2023-02-03 08:21 UTC, vlad-demchuk commented on src/index.html
> +            </li>
check this checklist point
<img width="945" alt="image" src="https://user-images.githubusercontent.com/102411130/216546757-f0891472-f6c1-44f8-a3da-5c2c51db68f9.png">

2023-02-03 08:21 UTC, vlad-demchuk commented on src/styles/blocks/card.scss
> +  margin-right: 48px;
<img width="910" alt="image" src="https://user-images.githubusercontent.com/102411130/216547297-d0947853-617e-428e-8cf5-55178bbc9eed.png">

2023-02-03 08:21 UTC, vlad-demchuk commented on src/styles/blocks/card.scss
> +    font-weight: 400;
400 is a default `font-weight`. no need to set it

2023-02-03 08:21 UTC, vlad-demchuk commented on src/styles/blocks/header.scss
> +.nav {
create a separate file for each bem block

2023-02-03 13:22 UTC, Vo7kov commented
https://vo7kov.github.io/layout_catalog/
https://vo7kov.github.io/layout_catalog/report/html_report/

2023-02-04 10:56 UTC, nazarmatsevych approved these changes

2025-07-07 14:22 UTC, closed without merging