completed layout_catalog
mate-academy/layout_catalog pull request #2711
Opened 2023-02-14 12:09 UTC by romahawk

Completed **"Layout catalog"** task from Mate Academy HTML + CSS Advanced / SASS Module

- [DEMO LINK](https://romahawk.github.io/layout_catalog/)
- [TEST REPORT LINK](https://romahawk.github.io/layout_catalog/report/html_report/)

2023-02-14 15:57 UTC, slavanosatskyi requested changes
![Screenshot 2023-02-14 at 17 53 04](https://user-images.githubusercontent.com/6526149/218789559-9c122ca2-273c-4c38-824a-47e613e85f3d.png)
Seems that your layout is broken is amount of items is less than 8. Regardless of the items amount the grid should stay solid

2023-02-15 11:34 UTC, romahawk commented
Could you please advise how to fix this issue? I have no idea to be honest...

2023-02-15 16:35 UTC, etojeDenys requested changes
please, fix prev comment, if you don't know how to do it, feel free to ask about it in the slack chat

2023-02-16 14:39 UTC, IvanFesenko approved these changes

2023-02-16 14:39 UTC, IvanFesenko commented on src/styles/blocks/container.scss
> +  // justify-content: center;
don't forget clean code from comments

2026-02-08 11:04 UTC, closed without merging