help
mate-academy/layout_catalog pull request #2753
Opened 2023-02-25 13:45 UTC by edgarlokys

https://edgarlokys.github.io/layout_catalog/
https://edgarlokys.github.io/layout_catalog/report/html_report/

2023-02-25 15:10 UTC, VitaliyBondarenko1982 requested changes

2023-02-25 15:10 UTC, VitaliyBondarenko1982 commented on src/index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,500;1,700&display=swap" rel="stylesheet">
Looks like incorrect link
```suggestion
 <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
```

2023-02-25 15:10 UTC, VitaliyBondarenko1982 commented on src/index.html
> +      <div class="cataloge">
```suggestion
      <div class="catalog">
```

2023-02-25 15:10 UTC, VitaliyBondarenko1982 commented on src/styles/blocks/cataloge.scss
> +.card {
Move styles fo card in separate file

2023-02-25 15:10 UTC, VitaliyBondarenko1982 commented on src/styles/blocks/cataloge.scss
> +    font-family: "Roboto-Regular", sans-serif;
Where did it come from font-family Roboto-Regular?
```suggestion
    font-family: "Roboto", sans-serif;
```

2023-02-25 15:10 UTC, VitaliyBondarenko1982 commented on src/styles/blocks/cataloge.scss
> +    font-family: "Roboto-Bold", sans-serif;
Where did it come from font-family Roboto-Regular?
```suggestion
    font-family: "Roboto", sans-serif;
```

2023-02-25 15:10 UTC, VitaliyBondarenko1982 commented on src/styles/blocks/cataloge.scss
> +  }
use scss syntax. heck other places
```suggestion
    &:hover {
      border: 1px solid $main-blue-accent;
      background-color: #fff;
      color: $main-blue-accent;
      transition: 0.3s;
    }
  }
```

2023-02-25 15:10 UTC, VitaliyBondarenko1982 commented on src/styles/blocks/cataloge.scss
> +    border: 1px solid rgba(255, 255, 255, 0);
```suggestion
    border: 1px solid #fff;
```

2023-02-25 15:10 UTC, VitaliyBondarenko1982 commented on src/styles/blocks/cataloge.scss
> +    border: 1px solid rgba(255, 255, 255, 0);
Move all colors to variables

2023-02-25 16:20 UTC, VitaliyBondarenko1982 approved these changes

2023-03-01 16:19 UTC, closed without merging

2023-03-01 16:27 UTC, mykhalenych approved these changes