create catalog
mate-academy/layout_catalog pull request #2800
Opened 2023-02-28 15:11 UTC by Goto-Jesus

- [DEMO LINK](https://Goto-Jesus.github.io/layout_catalog/)
- [TEST REPORT LINK](https://Goto-Jesus.github.io/layout_catalog/report/html_report/)

2023-03-02 08:57 UTC, jstmpelowycz requested changes
let's fix failing tests (font issue)
![Screenshot 2023-03-02 at 10 56 39](https://user-images.githubusercontent.com/75496546/222380049-d17da35c-348a-425a-8ef8-223b21100aed.png)

take care of your code, see the comments 👇

2023-03-02 08:57 UTC, jstmpelowycz commented on src/styles/utils/container.scss
> +  // border: 1px solid black;
remove commented code

2023-03-02 08:57 UTC, jstmpelowycz commented on src/index.html
> +        <a href="#home" class="logo"></a>
should link be a separate BEM-block?

2023-03-02 08:57 UTC, jstmpelowycz commented on src/index.html
> +          </div>
```suggestion
          <div class="card__price">
            <p class="card__price-label">Price:</p>
  
            <p class="card__price-value">$2,199</p>
          </div>
```

2023-03-02 08:57 UTC, jstmpelowycz commented on src/styles/blocks/header.scss
> +    margin: 0 0 0 20px;
better to reset it in `reset.scss`, what do you think? 🤔

2023-03-02 08:57 UTC, jstmpelowycz commented on src/styles/blocks/header.scss
> +  }
let's use `:not()`

2023-03-02 08:57 UTC, jstmpelowycz commented on src/styles/blocks/header.scss
> +}
make it a BEM-element and use nesting to assign to `header`

2023-03-02 08:57 UTC, jstmpelowycz commented on src/styles/blocks/header.scss
> +.header {
```suggestion
.header {
```

2023-03-02 08:57 UTC, jstmpelowycz commented on src/styles/blocks/card.scss
> +    padding-top: 50px;
```suggestion
    padding: 50px 40px 0;
```

2023-03-02 08:57 UTC, jstmpelowycz commented on src/styles/blocks/card.scss
> +    max-width: 1024px;
the checklist, p.13

2023-03-02 08:57 UTC, jstmpelowycz commented on src/styles/blocks/card.scss
> +.main {
too many BEM-blocks per file

2023-03-02 08:58 UTC, jstmpelowycz requested changes
testing table sync

2023-03-02 09:57 UTC, jstmpelowycz reviewed
let's add header box-shadow as in the mockup
![Screenshot 2023-03-02 at 11 57 29](https://user-images.githubusercontent.com/75496546/222395172-dfefb8cf-74f8-49fa-aa31-d343bdc73cb6.png)

2023-03-06 10:52 UTC, Goto-Jesus commented on src/styles/utils/container.scss
> +  // border: 1px solid black;
+

2023-03-06 13:05 UTC, Goto-Jesus commented on src/styles/blocks/header.scss
> +  }
done thx

2023-03-06 13:10 UTC, Goto-Jesus commented on src/styles/blocks/card.scss
> +  }
done

2023-03-06 13:18 UTC, closed without merging

2023-03-07 07:50 UTC, liliia-livandovskaya approved these changes