first draft
mate-academy/layout_catalog pull request #2872
Opened 2023-03-14 14:11 UTC by kq333

[DEMO LINK](https://kq333.github.io/layout_catalog/)
[TEST REPORT LINK](https://kq333.github.io/layout_catalog/report/html_report/)

2023-03-15 12:00 UTC, PufAnimalsDev commented
if you delete one product card, the grid is not saved, Volodymyr talked about it in class

2023-03-15 12:10 UTC, PufAnimalsDev commented on src/styles/header.scss
> +    color: var(--color-txt-primary);
try using scss variables not css variables

2023-03-15 12:12 UTC, PufAnimalsDev commented on src/styles/header.scss
> +    font-family: "Roboto", sans-serif;
repeating, you use this on an html tag

2023-03-15 12:16 UTC, PufAnimalsDev commented on src/styles/product-card.scss
> +  height: 40px;
use padding insted of height

2023-03-15 12:16 UTC, PufAnimalsDev commented on src/styles/stars.scss
> +.stars--1 :nth-child(-n + 1),
checklist number 12

2023-03-15 12:17 UTC, PufAnimalsDev commented on src/styles/colors.scss
> +  --color-link: #00acdc;
```suggestion
  $color-link: #00acdc;
```

2023-03-15 12:19 UTC, PufAnimalsDev commented on src/styles/product-card.scss
> +html {
repeating, you have these styles in the file: main-page.scss

2023-03-15 13:04 UTC, PufAnimalsDev commented on src/styles/header.scss
> +    height: 60px;
it could be a mistake, if you leave the height, that might be good too

2023-03-16 13:59 UTC, PufAnimalsDev approved these changes
one comment, I don't see any changes in stars.scss where the for loop should be, it's in checklist, it may not pass, I would suggest a change

2023-03-16 14:23 UTC, kq333 commented
> one comment, I don't see any changes in stars.scss where the for loop should be, it's in checklist, it may not pass, I would suggest a change

done.

2023-03-17 08:46 UTC, d-wasilewski requested changes

2023-03-17 08:46 UTC, d-wasilewski commented on src/styles/colors.css
> +:root {
That's true, but I see you have the scss file with variables already. You can delete this one then

2023-03-17 08:46 UTC, d-wasilewski commented on src/styles/colors.scss
again, this file might be removed, you have it it _colors if im not mistaken

2023-03-17 08:46 UTC, d-wasilewski commented on src/styles/main.css
remove this file

2023-03-17 08:46 UTC, d-wasilewski commented on src/styles/main.css.map
you can remove it too

2023-03-17 08:46 UTC, d-wasilewski commented on src/styles/product-card.scss
> +    padding-top: 32px;
margin

2023-03-17 08:46 UTC, d-wasilewski commented on src/styles/product-card.scss
> +    height: 36px;
this shouldnt be fixed

2023-03-17 08:46 UTC, d-wasilewski commented on src/styles/product-card.scss
> +    margin: 40px 16px 4px;
use either top or bottom margins to be consistent

2023-03-17 08:46 UTC, d-wasilewski commented on src/styles/product-card.scss
> +    height: 36px;
Here and in other places

2023-03-17 08:46 UTC, d-wasilewski commented on src/styles/product-card.scss
> +    margin: 16px;
you shouldnt give a margin to each element here, you can just set padding on the container to create this space

2023-03-17 08:46 UTC, d-wasilewski commented on src/styles/product-card.scss
> +  padding-bottom: 39px;
It's different on figma, and it should be margin not padding

2023-03-17 14:46 UTC, d-wasilewski commented on src/styles/product-card.scss
> +    margin: 40px 16px 4px;
Please fix

2023-03-17 14:49 UTC, d-wasilewski commented on src/styles/product-card.scss
> +  padding-bottom: 49px;
This should be margin. In general, you should use padding when you want to add space within an element and use margin when you want to add space outside an element.

2023-03-20 15:51 UTC, michalcywka requested changes
See comments

2023-03-20 15:51 UTC, michalcywka commented on src/styles/header.scss
> +  padding: 0 50px;
+1

2023-03-21 16:12 UTC, michalcywka requested changes
Please have a look at all the comments, not all of the issues are fixed

2023-03-27 07:34 UTC, michalcywka approved these changes

2023-10-03 20:27 UTC, closed without merging