add catalog
mate-academy/layout_catalog pull request #2932
Opened 2023-03-27 12:06 UTC by MartaChobaniuk

[DEMO LINK](https://martachobaniuk.github.io/layout_catalog/)
- [TEST REPORT LINK](https://martachobaniuk.github.io/layout_catalog/report/html_report/)

2023-03-27 15:03 UTC, Viktor-Kost requested changes
Oh! Good job!

Some comments left

2023-03-28 15:39 UTC, slavanosatskyi requested changes
Almost there! fix some comments from prev review + one additional comment from me

2023-03-28 15:39 UTC, slavanosatskyi commented on src/styles/blocks/cards.scss
> +  margin-bottom: $card-margin-bottom;
do not use external geometry (margins in your case) on a block level elements

2023-03-28 15:39 UTC, slavanosatskyi commented on src/styles/reset.scss
> +}
> it's allowed to use only `box-sizing: border-box for` `*` selector

this comment is not fixed yet

2023-03-28 22:21 UTC, YegorKorenkov approved these changes
Nice work! Please dont forget re-deploy your demo, because now it's looks
![image](https://user-images.githubusercontent.com/54936044/228379665-f545b4f1-e1cc-4327-9ba9-9113358bf582.png)

2023-03-28 22:21 UTC, YegorKorenkov commented on src/styles/blocks/cards.scss
> +    @include fonts (10px, 14px, 400);
font-weight 400 by default, redundant

2023-03-28 22:21 UTC, YegorKorenkov commented on src/styles/blocks/cards.scss
> +    @include fonts (10px, 14px, 400);
same

2023-05-27 12:41 UTC, closed without merging