solution 1
mate-academy/layout_catalog pull request #2935
Opened 2023-03-29 13:59 UTC by pr1syazhniy

[DEMO LINK](https://pr1syazhniy.github.io/layout_catalog/)
[TEST REPORT LINK](https://pr1syazhniy.github.io/layout_catalog/report/html_report/)

2023-03-29 14:51 UTC, slavanosatskyi requested changes
looks nice, but code has to be polished

2023-03-29 14:51 UTC, slavanosatskyi commented on src/styles/blocks/header.scss
> +    color: #060b35;
move reused colors into separate variable

2023-03-29 14:51 UTC, slavanosatskyi commented on src/styles/blocks/card.scss
> +html {
you already defined it in another file. Delete it or move to main.scss

2023-03-29 14:51 UTC, slavanosatskyi commented on src/styles/blocks/page.scss
> +  font-family: Roboto, sans-serif;
you have already defined it in html selector, so you can remove it from here

2023-03-29 14:51 UTC, slavanosatskyi commented on src/styles/blocks/page.scss
> +    margin: 0;
your margins are reseted in normalize.scss. And I'm not sure where do you use this class. The same goes to page.scss. Seems to be redundant file

2023-03-30 07:48 UTC, OleziO requested changes
Make links more meaningful.

2023-03-30 07:48 UTC, OleziO commented on src/styles/blocks/card.scss
> +  box-sizing: content-box;
Declare it only in `*` selector and remove it from all other places.

2023-03-30 07:48 UTC, OleziO commented on src/styles/blocks/card.scss
> +$background-color: #fff;
Declare variables in a separate file.

2023-03-30 14:13 UTC, slavanosatskyi approved these changes

2024-03-27 13:10 UTC, closed without merging