- [DEMO LINK](https://Sleptco.github.io/layout_catalog/) - [TEST REPORT LINK](https://Sleptco.github.io/layout_catalog/report/html_report/)
mate-academy/layout_catalog pull request #2940
Opened 2023-03-31 11:05 UTC by Sleptco

2023-03-31 11:14 UTC, SerhiiKirik requested changes
Great 🔥 
Try to pass test 🧑‍💻

2023-04-01 07:22 UTC, Sleptco commented
не проходить тест по :hover в чаті задавав питання виправи згідно рекомендацій, проблема не зникла. Help

2023-04-01 09:49 UTC, Sleptco commented
Ура . Тести пройшли. На Q&A допомогли, був зайвий запис по data-qa , вписав випадково не тільки в першу card.

2023-04-01 11:06 UTC, Anastasiia-Svintsova requested changes
Hey! Check your code style and BEM one more time, please

2023-04-01 11:06 UTC, Anastasiia-Svintsova commented on src/index.html
> +      <nav class="nav">
Check it everywhere
```suggestion
      </a>
      
      <nav class="nav">
```

2023-04-01 11:06 UTC, Anastasiia-Svintsova commented on src/index.html
> +               data-qa="nav-hover">
Same. Check it everywhere
```suggestion
            <a 
              href="#laptops&computers"
              class="nav__link"
              data-qa="nav-hover"
            >
```

2023-04-01 11:06 UTC, Anastasiia-Svintsova commented on src/index.html
> +        </ul>
```suggestion
          </li>
        </ul>
```

2023-04-01 11:06 UTC, Anastasiia-Svintsova commented on src/index.html
> +               alt="APPLE A1419 iMac 27 Retina 5K Monoblock (MNED2UA/A)">
Here the same comment

2023-04-01 11:06 UTC, Anastasiia-Svintsova commented on src/index.html
> +            data-qa="card-hover">
Same

2023-04-01 11:06 UTC, Anastasiia-Svintsova commented on src/styles/blocks/card.scss
> +@import "./stars.scss";
```suggestion
@import "./stars.scss";
```

2023-04-01 11:06 UTC, Anastasiia-Svintsova commented on src/styles/blocks/card.scss
> +  margin: auto;
Follow the checklist, please 
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/99403198/229285034-4bd2ba4e-0908-401f-9e01-9ee0bf03ec2e.png">

2023-04-01 11:06 UTC, Anastasiia-Svintsova commented on src/styles/blocks/card.scss
> +  margin-right: 48px;
Same here

2023-04-01 11:06 UTC, Anastasiia-Svintsova commented on src/styles/blocks/card.scss
> +    color: #060b35;
Create variables for repeatable values (for colors, for example)

2023-04-01 11:06 UTC, Anastasiia-Svintsova commented on src/styles/blocks/header.scss
> +}
Don't use tags for styling. Use classes

2023-04-03 11:12 UTC, Sleptco commented
correctod the comments, please check

2023-04-03 13:59 UTC, IvanFesenko approved these changes

2025-03-13 16:43 UTC, closed without merging