task solution
mate-academy/layout_catalog pull request #2969
Opened 2023-04-08 20:00 UTC by vpanch2

[DEMO LINK] https://vpanch2.github.io/layout_catalog/

[TEST REPORT LINK] https://vpanch2.github.io/layout_catalog/report/html_report/

2023-04-09 08:16 UTC, Volodymyr-Melnyk-Fron10der requested changes
1. Layout shouldn't be broken if I add more cards
![image](https://user-images.githubusercontent.com/122989585/230761804-410995e1-e244-45ed-b0d6-6354dba023aa.png)

2023-04-09 08:16 UTC, Volodymyr-Melnyk-Fron10der commented on src/styles/card.scss
> +$secondary-text-color: #616070;
move variables into separated file

2023-04-09 08:16 UTC, Volodymyr-Melnyk-Fron10der commented on src/styles/card.scss
> +}
move into normalize.scss

2023-04-09 08:16 UTC, Volodymyr-Melnyk-Fron10der commented on src/styles/header.scss
> +$main-link-color: #00acdc;
move into variables.scss

2023-04-09 08:16 UTC, Volodymyr-Melnyk-Fron10der commented on src/styles/header.scss
> +}
why do you need font-face if you haven't loaded any custom font files?

2023-04-09 08:16 UTC, Volodymyr-Melnyk-Fron10der commented on src/styles/header.scss
> +}
remove, it already presents in normalize file

2023-04-09 08:16 UTC, Volodymyr-Melnyk-Fron10der commented on src/styles/header.scss
> +    font-style: normal;
remove redundant default properties

2023-04-09 08:16 UTC, Volodymyr-Melnyk-Fron10der commented on src/styles/stars.scss
> +$size: 16px;
into variables file

2023-04-10 12:40 UTC, qoa11a requested changes
<img width="1582" alt="image" src="https://user-images.githubusercontent.com/102293862/230902863-26f59c4c-0e92-4184-96a8-5ab083362794.png">
The layout is still broken if I add more cards.

2023-04-14 19:54 UTC, closed without merging