for Bratashchuk
mate-academy/layout_catalog pull request #3016
Opened 2023-04-23 15:52 UTC by MayerLansky

2023-04-24 07:25 UTC, OleziO requested changes
Add demo link to PR description.

2023-04-24 07:25 UTC, OleziO commented on src/index.html
> +            <a href="#laptops" class="links__link_a">Laptops & Computers</a>
Divide by a few lines.

2023-04-24 07:25 UTC, OleziO commented on src/index.html
> +        <h2 class="card__title">APPLE A1419 iMac 27" Retina 5K Monoblock (MNED2UA/A)</h2>
Divide by a few lines. Check other similar cases.

2023-04-24 07:25 UTC, OleziO commented on src/index.html
> +        data-qa="card-hover"
Add 2 spaces before.

2023-04-24 07:25 UTC, OleziO commented on src/styles/main.scss
> +    color: #060b35;
Move to the variable.

2023-04-24 07:25 UTC, OleziO commented on src/styles/main.scss
> +  flex-direction: row;  //????????
You don't need to use this, cause the row is the default value.

2023-04-24 07:25 UTC, OleziO commented on src/styles/main.scss
> +  // padding: 50px;
Remove all comments from the code.

2023-04-24 07:25 UTC, OleziO commented on src/styles/main.scss
> +.stars--1 .stars__star:first-child,
Replace with -n + 1 to make the code the same style.

2023-04-27 03:35 UTC, MayerLansky commented
[DEMO LINK](https://MayerLansky.github.io/layout_catalog/)
[TEST REPORT LINK](https://MayerLansky.github.io/layout_catalog/report/html_report/)

2023-05-02 01:56 UTC, MayerLansky commented
[DEMO LINK](https://MayerLansky.github.io/layout_catalog/)
[TEST REPORT LINK](https://MayerLansky.github.io/layout_catalog/report/html_report/)

2023-05-04 01:49 UTC, closed without merging