add task solution
mate-academy/layout_catalog pull request #3033
Opened 2023-04-25 16:22 UTC by bohdan-mykhailenko

- [DEMO LINK](https://bohdan-mykhailenko.github.io/layout_catalog/)
- [TEST REPORT LINK](https://bohdan-mykhailenko.github.io/layout_catalog/report/html_report/)

2023-04-25 20:24 UTC, amashutikov approved these changes
Great job, everything looks good to me.

2023-04-25 20:24 UTC, amashutikov commented on src/styles/blocks/logo.scss
> +//so I decided to separate that in special block
On my opinion we dont need to create separate block for icon. Because icon is a single element of block.

2023-04-25 20:24 UTC, amashutikov commented on src/index.html
> +            data-qa="nav-hover"
Missed indentation.

2023-04-25 20:24 UTC, amashutikov commented on src/styles/blocks/card.scss
> +    border: 1px solid $color-active;
In card task we needed to set default border color to (transparent) and change it on :hover.

2023-04-27 06:53 UTC, silchyn requested changes
Fix comments above

2023-04-27 07:36 UTC, bohdan-mykhailenko commented
> Fix comments above

2023-04-28 05:00 UTC, Dima-Petrov requested changes
GJ Mate 😃 All i want to add is nesting in card__price el. Small adding, check it

2023-04-28 09:22 UTC, silchyn approved these changes

2023-04-28 09:22 UTC, silchyn commented on src/styles/utils/reset.scss
> +  font-weight: 400;
this should be in `normalize.scss`

2024-08-02 21:52 UTC, closed without merging