add layout_catalog task solution
mate-academy/layout_catalog pull request #3035
Opened 2023-04-25 18:22 UTC by maksym-bobryk

[DEMO LINK](https://maksym-bobryk.github.io/layout_catalog/)
[TEST REPORT LINK](https://maksym-bobryk.github.io/layout_catalog/report/html_report/)

2023-04-26 13:02 UTC, julshvets requested changes
Great job, but I have some suggestions and recommendations.

2023-04-26 13:07 UTC, amashutikov approved these changes
Great job, added small improvments.

2023-04-26 13:07 UTC, amashutikov commented on src/styles/blocks/card.scss
> +    border: 1px solid $blue-color;
In previous task 'card' we should do transparent border and change its color on hover.

2023-04-26 13:07 UTC, amashutikov commented on src/styles/blocks/stars.scss
> +
Checklist item 12 we should try to use @for loop for this.

2023-04-26 13:07 UTC, amashutikov commented on src/styles/main.scss
>  }
I think we should move this to reset.scss

2023-04-27 11:02 UTC, Anna-Tkachenko requested changes
Well Done!
Just check some suggestions for HTML structure

2023-04-27 11:02 UTC, Anna-Tkachenko commented on src/index.html
> +        >
Check correct indents for attribtues

2023-04-27 11:02 UTC, Anna-Tkachenko commented on src/index.html
> +              APPLE
Let's transform text with css property instead of do it directly in HTML

2023-04-27 11:02 UTC, Anna-Tkachenko commented on src/index.html
> +            <a href="." class="nav__link">SAMSUNG</a>
Add corresponding href according to the content for each link
```suggestion
            <a href="#samsung" class="nav__link">SAMSUNG</a>
```

2023-04-27 11:02 UTC, Anna-Tkachenko commented on src/index.html
> +        <div class="catalog__container">
Do you need 2 wrappers for catalog? Let's get rid one of them

2023-04-27 19:23 UTC, Anna-Tkachenko approved these changes
Good job! ⭐️

2023-04-27 19:23 UTC, Anna-Tkachenko commented on src/styles/blocks/catalog.scss
> +  margin: 0 auto;
You can't set margins to BEM block

2024-03-14 18:33 UTC, closed without merging