add task solution
mate-academy/layout_catalog pull request #3059
Opened 2023-04-26 20:16 UTC by PanyaPrimal

- [DEMO LINK](https://PanyaPrimal.github.io/layout_catalog/)
- [TEST REPORT LINK](https://PanyaPrimal.github.io/layout_catalog/report/html_report/)

2023-04-28 09:08 UTC, silchyn requested changes

2023-04-28 09:08 UTC, silchyn commented on src/styles/blocks/card.scss
> +  &__buy-btn:hover {
```suggestion
    &:hover {
```

2023-04-28 09:08 UTC, silchyn commented on src/styles/blocks/nav.scss
> +    text-align: center;
```suggestion
    @include flex-center-center;
    
    text-align: center;
```

2023-04-28 09:08 UTC, silchyn commented on src/styles/blocks/nav.scss
> +  &__item:not(:last-child) {
```suggestion
    &:not(:last-child) {
```

2023-04-28 09:08 UTC, silchyn commented on src/styles/utils/normalize.scss
> +body * {
?

2023-04-28 09:08 UTC, silchyn commented on src/styles/utils/normalize.scss
> +  display: block;
???

2023-04-28 09:08 UTC, silchyn commented on src/styles/utils/reset.scss
> +body * {
again

2023-04-28 09:08 UTC, silchyn commented on src/styles/utils/vars.scss
> +}
these are mixins, not variables

2023-05-02 07:39 UTC, naziamoff approved these changes
looks good to me 👍

2023-05-02 07:39 UTC, naziamoff commented on src/styles/blocks/card.scss
> +  border: 1px solid #f3f3f3;
Would be good to create a variable for this color as well

2025-12-18 12:03 UTC, closed without merging