implemented catalog
mate-academy/layout_catalog pull request #3082
Opened 2023-04-30 15:52 UTC by sheva10barca

- [DEMO LINK](https://sheva10barca.github.io/layout_catalog/)
- [TEST REPORT LINK](https://sheva10barca.github.io/layout_catalog/report/html_report/)

2023-04-30 16:02 UTC, VitaliyBondarenko1982 requested changes
with cards less than 4 in row layout become little broken
![Screenshot from 2023-04-30 18-59-10](https://user-images.githubusercontent.com/33029864/235363412-de12346d-8b1c-439b-b53c-0b38d45afb0e.png)

2023-04-30 16:02 UTC, VitaliyBondarenko1982 commented on src/index.html
> +            </a>
```suggestion
            <a
              href="#apple"
              class="nav__link is-active"
            >
              Apple
            </a>
```
indentation. check all similar cases

2023-04-30 16:02 UTC, VitaliyBondarenko1982 commented on src/styles/blocks/card.scss
> +  margin: 0 $cardMarginRight 46px 0;
bem block shouldn't have margins. instead create bem element

2023-05-01 07:20 UTC, etojeDenys approved these changes
lgtm

2025-02-09 17:54 UTC, closed without merging