Develop
mate-academy/layout_catalog pull request #3096
Opened 2023-05-04 15:01 UTC by VladyslavKolisnyk

2023-05-04 15:28 UTC, slavanosatskyi requested changes
please, fix demo and test report links. They lead to 404 
https://VladyslavKolisnyk.github.io/layout_catalog/

2023-05-07 07:03 UTC, Volodymyr-Melnyk-Fron10der requested changes
1. layout shouldn't be broken if I add some more cards
![image](https://user-images.githubusercontent.com/122989585/236662852-bf60e40d-67be-4482-b93e-ccc4b8de4f36.png)

2023-05-07 07:03 UTC, Volodymyr-Melnyk-Fron10der commented on src/styles/blocks/cards.scss
> +    font-weight: 400;
remove redundant default properties

2023-05-07 07:03 UTC, Volodymyr-Melnyk-Fron10der commented on src/styles/blocks/cards.scss
> +    color: #fff;
move colors into a constants

2023-05-08 06:51 UTC, OleziO approved these changes

2023-06-27 23:11 UTC, closed without merging