catalog
mate-academy/layout_catalog pull request #3103
Opened 2023-05-06 14:00 UTC by Oleksandr-liakhov

https://Oleksandr-liakhov.github.io/layout_catalog/
https://Oleksandr-liakhov.github.io/layout_catalog/report/html_report/

2023-05-07 07:56 UTC, OleziO requested changes
Make header full-screen width
![image](https://user-images.githubusercontent.com/56752562/236664830-939a5bcd-28a3-4596-9578-a4e0afad8bec.png)

Fix the button hover, they should not change the size of the card when hovering

2023-05-07 07:56 UTC, OleziO commented on src/index.html
> +              href="#home"
Make all links more meaningful

2023-05-07 07:56 UTC, OleziO commented on src/index.html
> +            </a>
```
Fix formatting.

 <a
  class="card__button"
  href="buy"
  data-qa="card-hover"
>
  buy
</a>
```

Check all similar cases

2023-05-08 18:08 UTC, Viktor-Kost commented on src/index.html
> +            </a>
isn't fixed

2023-05-08 18:11 UTC, Viktor-Kost requested changes
Hello!)
Please check previous mentor's remarks

2023-05-08 18:11 UTC, Viktor-Kost commented on src/styles/main.scss
> +@import "./utils/normalize";
please add other scss files to remote repository

2023-05-11 17:22 UTC, Viktor-Kost approved these changes

2023-06-13 20:39 UTC, closed without merging