Chudin_Pavlo
mate-academy/layout_catalog pull request #3115
Opened 2023-05-09 21:57 UTC by Pashahu1

[DEMO LINK](https://Pashahu1.github.io/layout_catalog/)
[TEST REPORT LINK](https://Pashahu1.github.io/layout_catalog/report/html_report/)

I changed almost everything in the mini theory, it is necessary to set the value so that there is some symmetry with the header, that is, the sensitivity must match

2023-05-10 07:33 UTC, vlad-demchuk requested changes
Fix demo and test report link

If you don't understand something or need some help, please, ask it in fe_chat and you will get answers to all questions

2023-05-11 06:52 UTC, vlad-demchuk requested changes

2023-05-11 06:52 UTC, vlad-demchuk commented on src/index.html
> +            </a>
```suggestion
            >
                Laptops & Computers
            </a>
```

2023-05-11 06:52 UTC, vlad-demchuk commented on src/index.html
> +        <div class="card-cost">
no need to create a separate bem block here

2023-05-11 06:52 UTC, vlad-demchuk commented on src/reseat/reseat.scss
> +* {
typo in the file name

reset.css

2023-05-11 06:52 UTC, vlad-demchuk commented on src/reseat/reseat.scss
> +  margin: 0;
html doesn't have paddings or margins

specify elements you need to reset

2023-05-11 06:52 UTC, vlad-demchuk commented on src/styles/blocks/cards.scss
> +  margin: 0 auto;
<img width="899" alt="image" src="https://github.com/mate-academy/layout_catalog/assets/102411130/fc65c12d-a7ff-48bd-bff4-1f938e475dff">

2023-05-11 06:52 UTC, vlad-demchuk commented on src/styles/blocks/cards.scss
> +  .page-catalog {
no need to create a separate block here

2023-05-11 06:52 UTC, vlad-demchuk commented on src/styles/blocks/cards.scss
> +    height: 406px;
do not hardcode height

let card content dictate this value

2023-05-11 06:52 UTC, vlad-demchuk commented on src/styles/blocks/cards.scss
> +    color: $blue-dark-color;
css properties order
http://codeguide.academy/html-css.html#css-order

2023-05-11 06:52 UTC, vlad-demchuk commented on src/styles/blocks/cards.scss
> +    color: $arial-color;
you can use nesting for hover in the class above

```
&__card-link {
some styles

  &:hover {
     background-color: $white-color;
     color: $arial-color;
  }
}

2023-05-11 06:52 UTC, vlad-demchuk commented on src/styles/blocks/header.scss
> +  min-width: 0;
why do you need `min-width: 0;`?

2023-05-11 06:52 UTC, vlad-demchuk commented on src/styles/blocks/header.scss
> +  height: 60px;
do not hardcode height

2023-05-11 06:52 UTC, vlad-demchuk commented on src/styles/blocks/header.scss
> +  &__nav-item:last-of-type {
can we use `last-child` or `not` for `&__nav-item`?

2023-05-12 07:32 UTC, vlad-demchuk requested changes
Looks better🙂
let's improve your code a bit

center the catalog
<img width="1511" alt="image" src="https://github.com/mate-academy/layout_catalog/assets/102411130/b5a9b117-04a4-494d-af27-f281af2c9e9e">

2023-05-12 07:32 UTC, vlad-demchuk commented on src/index.html
> +      <article class="cards__card" data-qa="card">
also, let's create a separate bem block for card, it will make our code more reusable

2023-05-12 07:32 UTC, vlad-demchuk commented on src/reseat/reset.css
> +  padding: 0;
body doesn't have paddings

2023-05-12 12:17 UTC, volodymyr-soltys97 approved these changes
Good job 👍

2023-05-25 19:18 UTC, closed without merging