add task solution
mate-academy/layout_catalog pull request #3148
Opened 2023-05-17 17:07 UTC by Platon-jun

- [DEMO LINK](https://platon-jun.github.io/layout_catalog/)
- [TEST REPORT LINK](https://platon-jun.github.io/layout_catalog/report/html_report/)

2023-05-18 07:35 UTC, vlad-demchuk requested changes
nothing should be broken when I add one more card
<img width="1048" alt="image" src="https://github.com/mate-academy/layout_catalog/assets/102411130/7a2169ee-bb1e-4848-ac2c-bcb6c8a7ee81">

2023-05-18 07:35 UTC, vlad-demchuk commented on src/index.html
> +    <header class="header header--margins">
```suggestion
    <header class="header">
```
do not set margins with the help of bem modifiers

just use mix for it (make this block bem element of `body` and apply external styles for it)

2023-05-18 07:35 UTC, vlad-demchuk commented on src/index.html
> +      <nav class="header__nav">
make it a separate bem block `nav`

2023-05-18 07:35 UTC, vlad-demchuk commented on src/index.html
> +            >Laptops & Computers</a>
check your code style
```suggestion
            <a
              class="header__link"
              data-qa="nav-hover"
              href="#lap&Comp"
            >
              Laptops & Computers
            </a>
```

2023-05-18 07:35 UTC, vlad-demchuk commented on src/index.html
> +        <div class="product-card" data-qa="card">
it doesn't match bem naming convention

`product-card, product-card-image... and so on`

fix all such cases according to bem

2023-05-18 07:35 UTC, vlad-demchuk commented on src/index.html
> +          <div class="product-card-container-code">
redundant wrapper

2023-05-18 07:35 UTC, vlad-demchuk commented on src/index.html
> +          </a>
```suggestion
          <a
            class="product-card-button"
            href="/"
            data-qa="card-hover"
          > 
            BUY
          </a>
```

2023-05-18 07:35 UTC, vlad-demchuk commented on src/styles/blocks/header.scss
> +  font-family: Roboto, sans-serif;
do not use `*` for `margins` or `font-family`

leave only `box-sizing` here

reset margin for some special tags, elements
move `font-family` to `html` selector

2023-05-18 07:35 UTC, vlad-demchuk commented on src/styles/blocks/header.scss
> +  font-family: Roboto, sans-serif;
move  it to a separate file like `reset.scss`

2023-05-18 07:35 UTC, vlad-demchuk commented on src/styles/blocks/header.scss
> +    display: flex;
redundant `font-family`

2023-05-18 07:35 UTC, vlad-demchuk commented on src/styles/blocks/header.scss
> +      align-items: center;
check css properties order
http://codeguide.academy/html-css.html#css-order

2023-05-18 07:35 UTC, vlad-demchuk commented on src/styles/blocks/header.scss
> +    &:last-child {
you can use `:not(:last-child)`

2023-05-18 07:35 UTC, vlad-demchuk commented on src/styles/blocks/header.scss
> +    padding-bottom: 23px;
use padding shorthand property

2023-05-19 07:00 UTC, vlad-demchuk requested changes

2023-05-19 10:58 UTC, nazarmatsevych requested changes
1. According to the task description
![image](https://github.com/mate-academy/layout_catalog/assets/80700247/e756a917-fe07-4a89-acb6-973190fbd5aa)

So you need to use width instead of max-width for your card container

2023-07-09 14:41 UTC, closed without merging