Develop
mate-academy/layout_catalog pull request #324
Opened 2020-03-03 11:05 UTC by FaychakA

- [DEMO LINK](https://FaychakA.github.io/layout_catalog/)
- [TEST REPORT LINK](https://FaychakA.github.io/layout_catalog/report/html_report/)

2020-03-03 11:46 UTC, denys-cheporniuk approved these changes
Крута робота)

2020-03-03 11:49 UTC, FaychakA commented
Дякую. Але то після всіх фіксів. Просто прийшлось репу перезаписати щоб git не вимахувався.

2020-03-05 08:14 UTC, denys-cheporniuk approved these changes

2020-03-05 09:22 UTC, denys-cheporniuk requested changes

2020-03-05 09:22 UTC, Denchepornyuk commented on src/index.html
> +          <section class="catalog__item__card card" data-qa="card">
не пиши тройну вкладеність в BEM
https://ru.bem.info/methodology/naming-convention/

2020-03-05 09:22 UTC, Denchepornyuk commented on src/index.html
> +              <a class="card__code__link" href="/">
тут аналогічно

2020-03-05 10:14 UTC, denys-cheporniuk requested changes

2020-03-05 10:14 UTC, Denchepornyuk commented on src/styles/catalog.scss
> +    margin: $card-margin-top $card-gapX 0 0;
це дублює максимальну ширину, краще розставити елементи флексом

2020-03-05 10:14 UTC, Denchepornyuk commented on src/styles/header.scss
> +  flex-wrap: nowrap;
це значення по дефолту

2020-03-05 10:14 UTC, Denchepornyuk commented on src/styles/header.scss
> +    & {
навіщо тут селектор?

2020-03-05 10:14 UTC, Denchepornyuk commented on src/styles/header.scss
> +    height: $header-img-height;
чим допомагають ці змінні?

2020-03-05 10:14 UTC, Denchepornyuk commented on src/styles/link.scss
> +  width: 100%;
а це навіщо?

2020-03-05 10:14 UTC, Denchepornyuk commented on src/styles/main.scss
> +}
тут повинен бути лише шрифт

2020-03-05 10:14 UTC, Denchepornyuk commented on src/styles/nav.scss
> +    padding: 0;
a ти ж робив reset??

2020-03-05 10:14 UTC, Denchepornyuk commented on src/styles/nav.scss
> +    line-height: 60px;
а чому не mixin?
і навіщо одночасно і flex i line-hight?
а якщо дизайнер попросить збільшити header?

2020-03-05 10:14 UTC, Denchepornyuk commented on src/styles/stars.scss
> +}
зроби по бему!!

2020-03-05 11:59 UTC, FaychakA commented on src/styles/header.scss
> +  flex-wrap: nowrap;
> це значення по дефолту

+

2020-03-05 11:59 UTC, FaychakA commented on src/styles/header.scss
> +  flex-wrap: nowrap;
> це значення по дефолту

++++++

2020-03-05 11:59 UTC, FaychakA commented on src/styles/stars.scss
> +}
> зроби по бему!!

++++++

2020-03-05 12:00 UTC, FaychakA commented on src/styles/nav.scss
> +    padding: 0;
> a ти ж робив reset??

++++++

2020-03-05 12:09 UTC, FaychakA commented on src/index.html
> +            <p class="card__price-title">
> тут було б добре додати порожній рядок

++++++

2020-03-05 12:09 UTC, FaychakA commented on src/index.html
> +                <span class="star"></span>
> а в тебе є незалежний блок star?

++++++

2020-03-05 12:10 UTC, FaychakA commented on src/index.html
> +              <div class="card__stars stars-4">
> stars-4 що це за блок?

++++++

2020-03-05 12:10 UTC, FaychakA commented on src/index.html
> +            <div class="card__photo"></div>
> смислові картинки маю бути в тегу img

++++++

2020-03-05 12:11 UTC, FaychakA commented on src/index.html
> +      <h2 class="catalog__visually-hidden"></h2>
> назва класу схожа на стан, а не на елемент

++++++

2020-03-05 12:13 UTC, FaychakA commented on src/index.html
> +
> краще пустим рядком розділяти лише елементи на одному рівні

++++++

2020-03-05 12:15 UTC, FaychakA commented on src/index.html
> +    <h1 class="catalog__visually-hidden"></h1>
> для google краще не залишати пусті заголовки

++++++

2020-03-05 12:18 UTC, FaychakA commented on src/index.html
> +              <a class="card__code__link" href="/">
> це елемент елемента?

++++++

2020-03-05 12:18 UTC, FaychakA commented on src/index.html
> +          <section class="catalog__item__card card" data-qa="card">
> не пиши тройну вкладеність в BEM
> https://ru.bem.info/methodology/naming-convention/

++++++

2020-03-05 12:19 UTC, FaychakA commented on src/index.html
> +          <a class="nav__link nav__link__is-active is-active" href="#">
> а що таке __is-active?

++++++

2020-03-05 12:23 UTC, FaychakA commented on src/index.html
> +              </span>
> а навіщо цей span?

++++++

2020-03-05 12:26 UTC, FaychakA commented on src/index.html
> +            </p>
> який шматок інформації зберігаєьтся в цьому абзаці?

++++++

2020-03-05 12:27 UTC, FaychakA commented on src/styles/card.scss
> +    background-image: url("../images/imac.jpeg");
> в кожного товара повинна бути своя картинка

++++++

2020-03-05 12:28 UTC, FaychakA commented on src/styles/card.scss
> +    }
> а що це елемент елемента?

++++++

2020-03-05 12:29 UTC, FaychakA commented on src/styles/header.scss
> +    & {
> навіщо тут селектор?

++++++

2020-03-05 13:19 UTC, FaychakA commented on src/styles/catalog.scss
> +  &__visually-hidden {
> а якщо ти захочеш в іншому блоці сховати елемент?

++++++

2020-03-05 13:25 UTC, FaychakA commented on src/styles/card.scss
> +    padding-bottom: 20px;
> а якщо забрати верхнього чи нижнього сусіда чи мають залишитись ці відступи?

++++++

2020-03-05 13:26 UTC, FaychakA commented on src/styles/card.scss
> +    padding-bottom: 20px;
> це можна об'єднати?

++++++

2020-03-05 13:27 UTC, FaychakA commented on src/styles/card.scss
> +    padding-bottom: 20px;
> зазвичай наступні блоки відсовуються марджинами

++++++

2020-03-05 13:32 UTC, FaychakA commented on src/styles/catalog.scss
> +    margin: 0 auto;
> тести не проходять через цей 0

++++++

2020-03-05 15:58 UTC, Denchepornyuk commented on src/index.html
> +              </p>
краще видалити тег p і всі стилі перекинути на тег а
тег p тут лишній

2020-03-05 15:58 UTC, Denchepornyuk commented on src/index.html
> +              <div class="review__stars stars stars-4">
якщо stats-4 це модифікатор то краще написати stars--4

2020-03-05 15:58 UTC, Denchepornyuk commented on src/index.html
> +              <a class="code--link" href="/">
code--link це модифікатор?
в тебе немає класу code щоб додавати до нього модифікатор --link

2020-03-05 15:58 UTC, Denchepornyuk commented on src/styles/card.scss
> +  }*/
видаляй коментарі

2020-03-05 15:58 UTC, Denchepornyuk commented on src/styles/link.scss
> +  width: 100%;
прибери width

2020-03-05 16:01 UTC, denys-cheporniuk requested changes
повнось останні зміни і завдання буде зроблено на всі 100)

2020-03-06 15:42 UTC, FaychakA reviewed
> повнось останні зміни і завдання буде зроблено на всі 100)

Все виправив!

2020-03-06 16:49 UTC, denys-cheporniuk approved these changes

2026-01-12 10:01 UTC, closed without merging