catalog_sky
mate-academy/layout_catalog pull request #3255
Opened 2023-06-05 13:31 UTC by RuslanSky23

- [DEMO LINK](https://RuslanSky23.github.io/layout_catalog/)
- [TEST REPORT LINK](https://RuslanSky23.github.io/layout_catalog/report/html_report/)

2023-06-05 13:48 UTC, volodymyr-soltys97 requested changes
Good job 👍 
But let's make your code more perfect

2023-06-05 13:48 UTC, volodymyr-soltys97 commented on src/styles/blocks/header.scss
> +  padding: 0 50px;
To maintain consistency, use the variable `$padding-horizontal` instead of hardcoding the padding value.

2023-06-05 13:48 UTC, volodymyr-soltys97 commented on src/styles/blocks/nav.scss
> +.collor_one:hover {
The class name 'collor_one' is not following the BEM naming convention. Consider changing it to 'nav__link--hover' or another appropriate name.

2023-06-05 13:48 UTC, volodymyr-soltys97 commented on src/styles/blocks/stars.scss
> +  // padding: 16px 16px 0;
Remove the commented-out padding property if it's not needed in the .stars class.

2023-06-05 13:48 UTC, volodymyr-soltys97 commented on src/styles/utils/_variables.scss
> +$blue-accent: #00acdc;
The $blue-accent variable has the same value as the $header-accent variable. Consider reusing the $header-accent variable instead, or remove the duplicate if it's not necessary.

2023-06-05 13:48 UTC, volodymyr-soltys97 commented on src/styles/blocks/container.scss
> +  flex-wrap: wrap;
Remove 'flex-wrap: wrap;' and replace it with 'grid-template-columns: repeat(4, 1fr);' and 'grid-gap: 16px;' to create a grid with 4 columns.

2023-06-05 13:48 UTC, volodymyr-soltys97 commented on src/styles/blocks/card.scss
> +  &:nth-child(#{$cards-row}n) {
The variable $cards-row is not defined in this file, make sure to define it or import it from another file.

2023-06-06 11:12 UTC, RuslanSky23 commented on src/styles/blocks/card.scss
> +    padding: 12px 70px 12px 69px;
The indentation is the same as in the example :)

2023-06-06 11:13 UTC, RuslanSky23 commented on src/index.html
> +        >
gives an error when I remove indents

2023-06-06 13:59 UTC, volodymyr-soltys97 requested changes
Let's to fix some moments. 
Your links don't work. Please check it

2023-06-06 13:59 UTC, volodymyr-soltys97 commented on src/index.html
> +      </a>
```suggestion
      <a class="page-header__link-logo" href="#home">
        <img
          src="./images/logo.png"
          alt="LogoMoyo"
          class="page-header__link-images"
        >
      </a>
```

2023-06-06 13:59 UTC, volodymyr-soltys97 commented on src/styles/utils/_normalize.scss
> +
```suggestion
```

2023-06-12 12:05 UTC, closed without merging