add task solution
mate-academy/layout_catalog pull request #3493
Opened 2023-07-27 15:21 UTC by SmartSergiZ

[DEMO LINK](https://SmartSergiZ.github.io/layout_catalog/)
[TEST REPORT LINK](https://SmartSergiZ.github.io/layout_catalog/report/html_report/)

2023-07-27 15:49 UTC, alexander-ignatow commented on src/styles/blocks/card.scss
> +    background-image: url(../images/star-active.svg);
You were supposed to reuse the stars block from the old stars task

For now, it is no easy way to switch stars to show any rating you want
Please fix it

2023-07-27 15:50 UTC, alexander-ignatow commented on src/styles/blocks/card.scss
> +    height: 40px;
Are you sure you need to hardcode the button's width and height?

2023-07-27 15:52 UTC, alexander-ignatow commented on src/styles/blocks/container.scss
> +}
If you are using grid - please implement as it is described in the [task](https://github.com/mate-academy/layout_catalog/blob/master/grid.md)

2023-07-27 15:54 UTC, alexander-ignatow commented on src/styles/normalize.scss
> +  box-sizing: border-box;
If you are setting box-sizing do it using *, because it is _not_ inhereted

2023-07-27 15:55 UTC, alexander-ignatow commented on src/index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
Do you really need all these fonts? Please import only the ones you are using

2023-07-28 09:01 UTC, Moroz-Dmytro requested changes
Have you deployed your changes?
I don't see changes regarding this

<img width="573" alt="image" src="https://github.com/mate-academy/layout_catalog/assets/86789161/5f25ff53-085d-4cf0-b593-087ee0f1b7f4">

When I hover on "Buy" button content of the page is jumping, please fix this

2023-07-28 09:01 UTC, Moroz-Dmytro commented on src/styles/blocks/header.scss
> +.header__list-item-link.is-active::after {
Don't increase specificity if no needed and use nesting with `is-active` class styles

2023-07-28 09:01 UTC, Moroz-Dmytro commented on src/styles/blocks/header.scss
> +.header {
Use nesting for all styles in this file

2023-07-28 15:15 UTC, BudnikOleksii requested changes
Great job👍
Just forgot to move stars to a separate block, this block can be reusable.

2023-07-28 15:15 UTC, BudnikOleksii commented on src/styles/blocks/card.scss
> +  &__stars {
Still not fixed. Stars is a separate BEM block, let's move it from the card, in the future, you can reuse it in other places if needed.

2023-07-28 15:15 UTC, BudnikOleksii commented on src/index.html
> +            LAPTOPS & COMPUTERS
The formatting is not fixed yet, check the previous comments.

2023-07-28 16:45 UTC, roman-mirzoian requested changes
Good job, but there is quite a bit of work to be done.
Do not forget to process comments from mentors.
Also, your header is now visually slightly different from the design.
Design:
![image](https://github.com/mate-academy/layout_catalog/assets/54860641/6efdb528-cfe2-4712-a1f1-c01d340bcec8)
Your app:
![image](https://github.com/mate-academy/layout_catalog/assets/54860641/d0a2fb57-c01a-489b-9c40-bbf9ade2a00a)

2023-07-28 16:45 UTC, roman-mirzoian commented on src/index.html
> +        </div>
@SmartSergiZ Maybe you forgot to fix it?

2023-07-31 18:20 UTC, Anna-Tkachenko approved these changes
Good job!

2023-09-22 12:31 UTC, closed without merging