add task solution
mate-academy/layout_catalog pull request #3711
Opened 2023-10-09 11:50 UTC by ApheliosGM

[DEMO LINK](https://ApheliosGM.github.io/layout_catalog/)
[TEST REPORT LINK](https://ApheliosGM.github.io/layout_catalog/report/html_report/)

2023-10-09 12:48 UTC, denys-danyliuk requested changes

2023-10-09 12:48 UTC, denys-danyliuk commented on src/styles/blocks/card.scss
> +.info {
it's a different bem block, you should move it to separate file

2023-10-09 12:48 UTC, denys-danyliuk commented on src/styles/main.scss
> +  }
don't increase specificity when it's not necessary

2023-10-09 12:48 UTC, denys-danyliuk commented on src/index.html
> +        class="header__logo">
```suggestion
      <a 
        href="#home"
        class="header__logo"
      >
```
check code style - attributes

2023-10-09 12:48 UTC, denys-danyliuk commented on src/index.html
> +          alt="header__logo"
try to come up with better alt text, check examples in a code style - seo

2023-10-10 16:20 UTC, Andriy-Shymkiv approved these changes

2025-08-08 14:43 UTC, closed without merging