add task solution
mate-academy/layout_catalog pull request #3843
Opened 2023-11-18 12:06 UTC by Vlad4567

- [DEMO LINK](https://Vlad4567.github.io/layout_catalog/)
- [TEST REPORT LINK](https://Vlad4567.github.io/layout_catalog/report/html_report/)

- [x] All component follow BEM and use SCSS
- [x] repaeted sizes and special colors are put to variables
- [x] Grid is used for the columns
- [x] cards are shown in 1, 2, 3 or 4 columns based on screen resolution
- [x] All changes on `:hover` are smooth
- [x] Code follows all the [Code Style Rules ❗️](https://mate-academy.github.io/layout_task-guideline/html-css-code-style-rules)

2023-11-18 15:46 UTC, VitaliyBondarenko1982 requested changes
Looks good.
Let's try to fix failed tests. 
Please check comments.

2023-11-18 15:46 UTC, VitaliyBondarenko1982 commented on src/styles/utils/normalize.scss
> +}
in general * selector only for box-sixing: border-box property
reset margin and set transition only for elements which need it.

```suggestion
* {
  box-sizing: border-box;
}
```

2023-11-18 15:46 UTC, VitaliyBondarenko1982 commented on src/styles/blocks/card.scss
> +  padding: 33px 17px 17px;
```suggestion
  padding: 32px 16px 16px;
```
with setting box-sizing fix paddings can help to fix failed tests.

2023-11-19 09:29 UTC, loralevitska approved these changes
Well done)

2026-08-06 08:05 UTC, closed without merging