add solution
mate-academy/layout_catalog pull request #3880
Opened 2023-12-04 12:36 UTC by ssaviak

- [DEMO LINK](https://ssaviak.github.io/layout_catalog/)
- [TEST REPORT LINK](https://ssaviak.github.io/layout_catalog/report/html_report/)

- [x] All component follow BEM and use SCSS
- [x] repaeted sizes and special colors are put to variables
- [x]  Grid is used for the columns
- [x] cards are shown in 1, 2, 3 or 4 columns based on screen resolution
- [x] All changes on :hover are smooth
- [x] Code follows all the [Code Style Rules ❗️](https://mate-academy.github.io/layout_task-guideline/html-css-code-style-rules)

2023-12-04 16:49 UTC, dinaminahi commented on src/index.html
> +            </a>
```suggestion
            <a 
               href="#Laptops&Computers"
               class="nav__link"
            >
              Laptops & Computers
            </a>
```

![image](https://github.com/mate-academy/layout_catalog/assets/46566190/e2805cba-608b-40d9-9ae5-d945fd89638e)

2023-12-05 16:41 UTC, SerhiiKirik requested changes
Let's redeploy your page 🧑‍💻 
![image](https://github.com/mate-academy/layout_catalog/assets/91411692/12f6728f-0cef-4279-98ae-e675f443e446)

2023-12-05 16:41 UTC, SerhiiKirik commented on src/styles/blocks/card.scss
> +  box-sizing: border-box;
would be better to move it to the `*`
```suggestion
```

2023-12-05 16:41 UTC, SerhiiKirik commented on src/styles/blocks/card.scss
> +  font-family: Roboto, Arial, Helvetica, sans-serif;
move it to the `html` & remove in all cases
```suggestion
```

2023-12-05 16:41 UTC, SerhiiKirik commented on src/styles/blocks/card.scss
> +  }
```suggestion
  &__info {
    display: flex;
    flex-direction: column;
    justify-content: space-between;
  }
```

2023-12-05 16:41 UTC, SerhiiKirik commented on src/styles/blocks/card.scss
> +    color:$white-color;
```suggestion
    color: $white-color;
```

2023-12-05 16:41 UTC, SerhiiKirik commented on src/styles/blocks/stars.scss
> +
```suggestion
```

2023-12-05 16:41 UTC, SerhiiKirik commented on src/index.html
> +        <img
```suggestion
    </header>
    
    <main class = "catalog">
      <div class="card" data-qa="card">
        <img
```

2023-12-05 16:41 UTC, SerhiiKirik commented on src/index.html
> +          class="card__image"
```suggestion
          </button>
        </div>
      </div>
      
      <div class="card" data-qa="card">
        <img
          class="card__image"
```

2023-12-05 16:41 UTC, SerhiiKirik commented on src/index.html
> +            <a href="#Apple" class="nav__link is-active">Apple</a>
```suggestion
        <img src="images/logo.png" alt="logo">
      </a>
      
      <nav class="nav">
        <ul class="nav__list">
          <li class="nav__item">
            <a href="#Apple" class="nav__link is-active">Apple</a>
```

2023-12-06 13:40 UTC, YegorKorenkov approved these changes
Good job!

2024-05-13 11:33 UTC, closed without merging