add task solution
mate-academy/layout_catalog pull request #3911
Opened 2023-12-11 16:19 UTC by sophiasph

2023-12-11 16:59 UTC, Esceype requested changes
GJ!
Read the following comments

2023-12-11 16:59 UTC, Esceype commented on src/styles/cards.scss
> +
Rename this file, if you card block inside so this file should call `card`.

2023-12-11 16:59 UTC, Esceype commented on src/styles/header.scss
> +.nav {
This is separate block so move it to separate file.

2023-12-11 16:59 UTC, Esceype commented on src/styles/stars.scss
> +.card__rating-stars {
It looks like card element and if you create it to use BEM mix methodology then you need to keep this class in card file but make it separate from stars block

2023-12-11 16:59 UTC, Esceype commented on src/index.html
> +          alt="Imac"
Provide better naming for alt attribute

2023-12-11 19:44 UTC, sophiasph commented on src/index.html
> +          alt="Imac"
why is it alt attribute name bad?

2023-12-13 07:37 UTC, maxim2310 requested changes
something went wrong with your demo link, plz fix it 
![image](https://github.com/mate-academy/layout_catalog/assets/96265844/73c91b87-c7ca-41b4-acf8-1af94f4b80aa)

2023-12-13 16:43 UTC, closed without merging