implemented solution
mate-academy/layout_catalog pull request #3924
Opened 2023-12-17 17:14 UTC by willwildred

- [DEMO LINK](https://willwildred.github.io/layout_catalog/)
- [TEST REPORT LINK](https://willwildred.github.io/layout_catalog/report/html_report/)

- [x] All component follow BEM and use SCSS
- [x] repaeted sizes and special colors are put to variables
- [x] Grid is used for the columns
- [x] cards are shown in 1, 2, 3 or 4 columns based on screen resolution
- [x] All changes on `:hover` are smooth
- [x] Code follows all the [Code Style Rules ❗️](https://mate-academy.github.io/layout_task-guideline/html-css-code-style-rules)

2023-12-17 17:55 UTC, volodymyr-soltys97 requested changes
Good job 👍 
Let's improve your code

2023-12-17 17:55 UTC, volodymyr-soltys97 commented on src/index.html
> +    <!-- #region header -->
Comment is redundant here
```suggestion
```

2023-12-17 17:55 UTC, volodymyr-soltys97 commented on src/index.html
> +          </li>
Fix classes everywhere
```suggestion
          <li class="nav__item">
            <a href="#" class="nav__link is-active">
              Apple
            </a>
          </li>
```

2023-12-17 17:55 UTC, volodymyr-soltys97 commented on src/index.html
> +        <ul class="nav-menu">
```suggestion
      <nav class="nav">
        <ul class="nav__list">
```

2023-12-17 17:55 UTC, volodymyr-soltys97 commented on src/index.html
> +            >
```suggestion
            <a
              href="#"
              class="nav-menu__links"
              data-qa="nav-hover"
            >
```

2023-12-17 17:55 UTC, volodymyr-soltys97 commented on src/index.html
> +      <section class="card">
It will be better
```suggestion
      <article class="card">
```

2023-12-18 15:03 UTC, anastasiiavorobiova requested changes
Great work! Almost done: 
<img width="205" alt="Screenshot 2023-12-18 at 17 00 30" src="https://github.com/mate-academy/layout_catalog/assets/135232001/9a140d52-be42-42c7-8d9b-ae2d7f2a92ab">
<img width="202" alt="Screenshot 2023-12-18 at 17 00 38" src="https://github.com/mate-academy/layout_catalog/assets/135232001/13dd5032-5f3b-467a-9e27-62d1d7be4176">
Consider fixing font styles here

2023-12-18 15:03 UTC, anastasiiavorobiova commented on src/styles/blocks/card.scss
> +    width: 166px;
```suggestion
    width: 100%;
```

2023-12-19 10:33 UTC, volodymyr-soltys97 approved these changes
Good job 👍

2024-06-05 08:38 UTC, closed without merging