Develop
mate-academy/layout_catalog pull request #3948
Opened 2023-12-26 14:24 UTC by dmitruz

- [DEMO LINK](https://dmitruz.github.io/layout_catalog/)
- [TEST REPORT LINK](https://dmitruz.github.io/layout_catalog/report/html_report/)

2023-12-26 14:32 UTC, l4st1m0za requested changes
Run the test so that mentors can see your tests, it's importan't for reviewing your home task!

2023-12-27 17:16 UTC, Andriy-Shymkiv approved these changes
lgtm

2023-12-27 17:16 UTC, Andriy-Shymkiv commented on src/styles/blocks/stars.scss
> +  }
please use scss nesting

2023-12-27 17:48 UTC, dmitruz commented on src/styles/blocks/stars.scss
> +  }
fix it

2024-05-16 20:04 UTC, closed without merging