Develop
mate-academy/layout_catalog pull request #4060
Opened 2024-02-04 13:17 UTC by YehorHeiko

- [DEMO LINK](https://YehorHeiko.github.io/layout_catalog/)
- [TEST REPORT LINK](https://YehorHeiko.github.io/layout_catalog/report/html_report/)

2024-02-04 16:32 UTC, volodymyr-soltys97 requested changes
Good job!
This part of the task is in complete
<img width="348" alt="image" src="https://github.com/mate-academy/layout_catalog/assets/64750958/f51ba2a0-0a62-4c27-af99-eccf75d2b6fe">

2024-02-04 16:32 UTC, volodymyr-soltys97 commented on src/index.html
> +    >
```suggestion
    <link rel="stylesheet" href="./styles/main.scss">
```

2024-02-04 16:32 UTC, volodymyr-soltys97 commented on src/index.html
> +              <div class="card__reviews-label">Reviews: 5</div>
Use the semantic tag for text everywhere

2024-02-04 16:32 UTC, volodymyr-soltys97 commented on src/styles/blocks/card.scss
> +  }
Fix it everywhere
```suggestion
  &__reviews {
    display: flex;
    justify-content: space-between;
    
    &-label {
      display: flex;
      justify-content: center;
      align-items: center;
    }
  }
```

2024-02-04 16:32 UTC, volodymyr-soltys97 commented on src/styles/main.scss
> +  font-weight: 400;
Default value, so you can just remove it
```suggestion
```

2024-02-04 16:32 UTC, volodymyr-soltys97 commented on src/styles/main.scss
> +  font-family: Roboto, Cinzel, sans-serif;
Move font family to the html selector

2024-02-05 09:32 UTC, OleziO requested changes
![image](https://github.com/mate-academy/layout_catalog/assets/56752562/c1d85be3-3afa-4d11-9d1b-762bf449d1e7)
Make the effect of hovering over the button only when hovering over it, not over the entire card

2024-02-05 09:32 UTC, OleziO commented on src/index.html
> +              >
```suggestion
            <a
              href="#laptops&computers"
              class="nav__link"
              data-qa="nav-hover"
            >
```

2024-02-05 09:32 UTC, OleziO commented on src/styles/main.scss
> +}
```suggestion
}
```

2024-02-05 09:50 UTC, YehorHeiko commented
Не обязательно при наведении на кнопку увеличивать карту. Этого нет в задании!

2024-02-05 09:59 UTC, etojeDenys requested changes
1. about hover effect:
<img width="807" alt="image" src="https://github.com/mate-academy/layout_catalog/assets/70220667/14b5e6c2-3cc7-4b04-8b86-ebb255650802">


2. try to fix your demo link
<img width="1071" alt="image" src="https://github.com/mate-academy/layout_catalog/assets/70220667/f1d91767-c5ba-43fe-b0c0-f3b9774ea933">

2024-07-30 19:58 UTC, closed without merging