add task solution
mate-academy/layout_catalog pull request #4133
Opened 2024-02-16 13:25 UTC by GrigorovaY

- [DEMO LINK](https://GrigorovaY.github.io/layout_catalog/)
- [TEST REPORT LINK](https://GrigorovaY.github.io/layout_catalog/report/html_report/)

- [ ] All component follow BEM and use SCSS
- [ ] repaeted sizes and special colors are put to variables
- [ ] Grid is used for the columns
- [ ] cards are shown in 1, 2, 3 or 4 columns based on screen resolution
- [ ] All changes on `:hover` are smooth
- [ ] Code follows all the [Code Style Rules ❗️](https://mate-academy.github.io/layout_task-guideline/html-css-code-style-rules)

2024-02-16 14:13 UTC, anastasiiavorobiova requested changes
Great work! Almost done!

2024-02-16 14:13 UTC, anastasiiavorobiova commented on src/index.html
> +          >
```suggestion
        >
```

2024-02-16 14:13 UTC, anastasiiavorobiova commented on src/index.html
> +          >
```suggestion
        >
```

2024-02-16 14:13 UTC, anastasiiavorobiova commented on src/index.html
> +          <div class="stars">
```suggestion
          <div class="stars stars--4">
```

2024-02-16 14:13 UTC, anastasiiavorobiova commented on src/index.html
> +        </a>
```suggestion
        <a
          href="#"
          class="product-card__button"
          data-qa="card-hover"
        >
          buy
        </a>
```

2024-02-16 14:13 UTC, anastasiiavorobiova commented on src/styles/_header.scss
> +    top: 56;
```suggestion
    bottom: 0;
```

2024-02-16 14:13 UTC, anastasiiavorobiova commented on src/styles/_header.scss
> +    width: 37px;
```suggestion
    width: 100%;
```

2024-02-16 14:13 UTC, anastasiiavorobiova commented on src/styles/_product-card.scss
> +
```suggestion
```

2024-02-16 14:13 UTC, anastasiiavorobiova commented on src/styles/_stars.scss
> +  &__star:nth-child(-n+4) {
Consider using styles from the previous task

2024-02-17 15:48 UTC, VitaliyBondarenko1982 approved these changes
Well done

2025-01-24 11:58 UTC, closed without merging