Develop
mate-academy/layout_catalog pull request #4176
Opened 2024-03-02 11:00 UTC by hannasavka

- [DEMO LINK](https://hannasavka.github.io/layout_catalog/)
- [TEST REPORT LINK](https://hannasavka.github.io/layout_catalog/report/html_report/)

- [ ] All component follow BEM and use SCSS
- [ ] repaeted sizes and special colors are put to variables
- [ ] Grid is used for the columns
- [ ] cards are shown in 1, 2, 3 or 4 columns based on screen resolution
- [ ] All changes on `:hover` are smooth
- [ ] Code follows all the [Code Style Rules ❗️](https://mate-academy.github.io/layout_task-guideline/html-css-code-style-rules)

2024-03-02 13:44 UTC, volodymyr-soltys97 requested changes
Hi, your styles don't working, we communicate with this in the fe_chat
<img width="1219" alt="image" src="https://github.com/mate-academy/layout_catalog/assets/64750958/174eac66-4dd7-4da5-8209-81b3f35bac80">

2024-03-02 17:26 UTC, volodymyr-soltys97 requested changes
Good job 👍 
Let's improve your code

2024-03-02 17:26 UTC, volodymyr-soltys97 commented on src/index.html
> +          <li>
Maybe you need classes to the tag li?
```suggestion
          <li class="nav__item">
```

2024-03-02 17:26 UTC, volodymyr-soltys97 commented on src/index.html
> +            <a class="nav__item is-active" href="#apple">apple</a>
Fix it everywhere
```suggestion
            <a class="nav__link is-active" href="#apple">apple</a>
```

2024-03-02 17:26 UTC, volodymyr-soltys97 commented on src/index.html
> +      <div class="card" data-qa="card">
Consider will be better it you use the article tag here for the card
```suggestion
      <article class="card" data-qa="card">
```

2024-03-02 17:26 UTC, volodymyr-soltys97 commented on src/styles/blocks/card.scss
> +  perspective: 400px;
```suggestion
```

2024-03-02 17:26 UTC, volodymyr-soltys97 commented on src/styles/blocks/card.scss
> +    font-weight: 400;
Default value, so you can just remove it everywhere
```suggestion
```

2024-03-02 17:26 UTC, volodymyr-soltys97 commented on src/styles/utils/variables.scss
> +$color-header: #00ACDC;
Why did you create two variables with the same values?
```suggestion
$background-color-card: #FFF;
$color-blue: #00ACDC;
```

2024-03-03 20:13 UTC, closed without merging

2024-03-04 16:59 UTC, hannasavka commented
.

2024-03-04 16:59 UTC, hannasavka commented
.