add task solution
mate-academy/layout_catalog pull request #4459
Opened 2024-06-20 06:36 UTC by hatevadym

2024-06-20 08:20 UTC, DarkMistyRoom requested changes

2024-06-20 08:20 UTC, DarkMistyRoom commented on readme.md
> +- [TEST REPORT LINK](https://<hatevadym>.github.io/layout_catalog/report/html_report/)
```suggestion
- [DEMO LINK](https://hatevadym.github.io/layout_catalog/)
- [TEST REPORT LINK](https://hatevadym.github.io/layout_catalog/report/html_report/)
```

2024-06-20 08:20 UTC, DarkMistyRoom commented on readme.md
> +- [TEST REPORT LINK](https://<hatevadym>.github.io/layout_catalog/report/html_report/)
Your demo links don't work. Please, fix them and provide into the PR description

2024-06-20 08:20 UTC, DarkMistyRoom commented on src/styles/main.scss
> +}
create a separate file for this block

2024-06-20 08:20 UTC, DarkMistyRoom commented on src/styles/main.scss
> +}
```suggestion
.container {
  padding: 50px 40px;
  display: grid;
  grid-template-columns: repeat(1, 200px);
  gap: 46px 48px;
  justify-content: center;
  
  @media (min-width: 488px) {
    grid-template-columns: repeat(2, 200px);
  }
}
```

2024-06-20 08:20 UTC, DarkMistyRoom commented on src/styles/main.scss
> +}
you can do it this way

2024-06-20 08:20 UTC, DarkMistyRoom commented on src/styles/blocks/card.scss
> +}
```suggestion
&:hover &__name {
  color: $cardtexthover;
}
```

2024-06-20 08:20 UTC, DarkMistyRoom commented on src/styles/blocks/card.scss
> +}
move it into the block

2024-08-28 12:11 UTC, lerastarynets requested changes
Pls fix prev comments
Pls ask for help in **fe_chat** if you don't understand something

2024-08-30 11:13 UTC, volodymyr-soltys97 requested changes
Hi, the demo link hasn't styles, need to fix it 
<img width="1017" alt="image" src="https://github.com/user-attachments/assets/4cc61bef-0a61-43b9-b975-81e1d5a5fe74">

2024-08-30 11:13 UTC, volodymyr-soltys97 commented on src/index.html
> +    <main class="container">
```suggestion
    </header>
    
    <main class="container">
```

2024-08-30 11:13 UTC, volodymyr-soltys97 commented on src/index.html
> +        <div class="card__pic"></div>
This image isn't background, so you need to add image with the `img` tag

2024-08-30 11:13 UTC, volodymyr-soltys97 commented on src/index.html
> +        <div class="card__code">Product code: 195434</div>
You need to use the semantic tag for text, fix it everywhere
```suggestion
        <h2 class="card__name">
          APPLE A1419 iMac 27" Retina 5K Monoblock (MNED2UA/A)
        </h2>
        
        <p class="card__code">Product code: 195434</p>
```

2024-12-28 15:00 UTC, closed without merging