solution
mate-academy/layout_catalog pull request #452
Opened 2020-07-08 11:36 UTC by DolgKreker

- [DEMO LINK](https://DolgKreker.github.io/layout_catalog/)
- [TEST REPORT LINK](https://DolgKreker.github.io/layout_catalog/report/html_report/)

2020-07-08 15:43 UTC, vkryvytskyi requested changes

2020-07-08 15:43 UTC, vkryvytskyy commented on src/index.html
> +        </a>
nav > ul > li a
this is the structure of naviagation

2020-07-08 15:43 UTC, vkryvytskyy commented on src/styles/main.scss
> +      border: 1px solid $moyo-color;
don't add border on hover

2020-07-08 15:43 UTC, vkryvytskyy commented on src/styles/main.scss
> +      border-radius: 5px;
your card already has border-radius

2020-07-08 15:43 UTC, vkryvytskyy commented on src/styles/main.scss
> +      box-sizing: border-box;
this should be added to all elements using `*` selector

2020-07-10 12:44 UTC, mgrinko requested changes

2020-07-10 12:44 UTC, mgrinko commented on src/index.html
> +              <div class="star"></div>
Читай в чате

2020-07-10 12:44 UTC, mgrinko commented on src/index.html
> +            <span class="product__price">69 999 грн</span>
Почему для описания цены ты используешь 3 разных элементы которые судя по названиям никак не связаны??? (value, caption, price) - это всё относится к описанию цены (price-container, price-label, price)

2020-07-10 12:45 UTC, mgrinko commented on src/styles/main.scss
> +  line-height: 13px;
а почему не сделать это шрифтом всей страницы по умолчанию

2020-07-13 13:10 UTC, denys-cheporniuk approved these changes

2024-12-24 21:24 UTC, closed without merging