Develop
mate-academy/layout_catalog pull request #4654
Opened 2024-09-04 13:10 UTC by vladyslava4

- [DEMO LINK](https://vladyslava4.github.io/layout_catalog/)
- [TEST REPORT LINK](https://vladyslava4.github.io/layout_catalog/report/html_report/)

2024-09-04 13:21 UTC, anastasiiavorobiova requested changes
Great work! Make sure to deploy your solution

2024-09-04 13:21 UTC, anastasiiavorobiova commented on src/index.html
> +              <div class="rating__stars stars">
```suggestion
              <div class="rating__stars stars stars--4">
```

2024-09-04 13:21 UTC, anastasiiavorobiova commented on src/index.html
> +                <div class="stars__star stars__star--active"></div>
```suggestion
                <div class="stars__star"></div>
                <div class="stars__star"></div>
                <div class="stars__star"></div>
                <div class="stars__star"></div>
```
Consider using classes from the previous task

2024-09-04 13:21 UTC, anastasiiavorobiova commented on src/index.html
> +              <div class="rating__reviews">Reviews: 5</div>
```suggestion
              <p class="rating__reviews">Reviews: 5</p>
```

2024-09-04 13:21 UTC, anastasiiavorobiova commented on src/index.html
> +            </h1>
```suggestion
            <h2 class="card__title">
              APPLE A1419 iMac 27" Retina 5K Monoblock (MNED2UA/A)
            </h2>
```
the h1 could be used once per page

2024-09-04 13:21 UTC, anastasiiavorobiova commented on src/index.html
> +            </div>
```suggestion
            <p class="card__price price">
              <span class="price__text">Price:</span>
              <span class="price__amount">$2,199</span>
            </p>
```
Consider leveraging semantic tags for the text

2024-09-04 13:21 UTC, anastasiiavorobiova commented on src/styles/index.scss
> +}
Consider moving general styles to a separate file

2024-09-04 13:21 UTC, anastasiiavorobiova commented on src/styles/index.scss
> +.card__image {
Consider leveraging scss features
```
.card {
    ...

  &__image {
    ...
  }
}
```

2024-09-04 13:21 UTC, anastasiiavorobiova commented on src/styles/index.scss
> +  color: #fff;
Consider using variables for repeating colors

2024-09-04 13:21 UTC, anastasiiavorobiova commented on src/styles/index.scss
> +.stars__star--active {
The number of active stars should depend on the class with modifier

2024-09-04 14:16 UTC, anastasiiavorobiova requested changes
Consider fixing previous comments and deploying your solution

2024-09-04 14:21 UTC, anastasiiavorobiova requested changes
Feel free to ask for help in the chat to fix comments and deploy your solution

2024-09-04 14:39 UTC, vladyslava4 commented on src/index.html
> +              <div class="rating__stars stars">
@anastasiiavorobiova  я исправила что не так ?

2024-09-04 14:47 UTC, anastasiiavorobiova requested changes
<img width="774" alt="Screenshot 2024-09-04 at 17 44 07" src="https://github.com/user-attachments/assets/936bc317-7746-440d-bc5f-5a26134c72cf">

The demo link leads to the 404 page 
Previous comments are not fixed 
Please, ask for help in the chat or welcome to the Q&A session for help

2024-09-04 14:47 UTC, anastasiiavorobiova commented on src/index.html
> +            </div>
```suggestion
            <div class="card__rating rating">
              <div class="rating__stars stars stars--4">
                <div class="stars__star"></div>
                <div class="stars__star"></div>
                <div class="stars__star"></div>
                <div class="stars__star"></div>
                <div class="stars__star"></div>
              </div>
              <p class="rating__reviews">Reviews: 5</p>
            </div>
            <p class="card__price price">
              <span class="price__text">Price:</span>
              <span class="price__amount">$2,199</span>
            </p>
```
Consider fixing same issues for your blocks

2024-09-04 14:47 UTC, anastasiiavorobiova commented on src/index.html
> +            </h1>
Also not fixed

2024-09-04 14:47 UTC, anastasiiavorobiova commented on src/styles/index.scss
> +}
Not fixed

2024-09-04 14:47 UTC, anastasiiavorobiova commented on src/styles/index.scss
> +.card__image {
Not fixed

2024-09-04 14:47 UTC, anastasiiavorobiova commented on src/styles/index.scss
> +.stars__star--active {
Not fixed

2024-09-04 14:59 UTC, etojeDenys requested changes
pls, don't hesitate to ask for some help with deploy in the chat

2024-09-04 15:10 UTC, vladyslava4 commented
> пожалуйста, не стесняйтесь обращаться за помощью в развертывании в чате

<img width="759" alt="Знімок екрана 2024-09-04 о 17 52 42" src="https://github.com/user-attachments/assets/def18f4e-1342-4b5d-bbfb-63732601ce75">
я зверталась мені не відповіли

2024-09-05 06:14 UTC, volodymyr-soltys97 requested changes
Hi, there is no styles on the demo link 
<img width="854" alt="image" src="https://github.com/user-attachments/assets/63ff7184-0c80-4f3c-8130-70ed316a6d3a">

2024-09-05 06:14 UTC, volodymyr-soltys97 commented on src/index.html
> +        <div class="header-content">
Redundant
```suggestion
```

2024-09-05 06:14 UTC, volodymyr-soltys97 commented on src/index.html
> +        <div class="catalog__content">
Redundant
```suggestion
```

2024-09-05 06:51 UTC, closed without merging