Develop
mate-academy/layout_catalog pull request #524
Opened 2020-09-01 11:23 UTC by andlap24

[DEMO LINK](https://andlap24.github.io/layout_catalog/)
[TEST REPORT LINK](https://andlap24.github.io/layout_catalog/report/html_report/)

2020-09-01 21:49 UTC, AndriiManyak requested changes

2020-09-01 21:49 UTC, AndriiManyak commented on src/styles/reset.css
> +html,
Росширення має бути .scss, а не .css
І reset файл краще імпортувати у main.scss, а не додавати в html

2020-09-01 21:49 UTC, AndriiManyak commented on src/styles/main.scss
> +}
Стилі для кожного з BEM елементів краще записувати у окремий файл з розширенням .scss і такою ж назвою як і назва самого елементу, а потім імпортувати в main.scss

2020-09-01 21:49 UTC, AndriiManyak commented on src/index.html
> +        <ul class="nav_list">
Назва елементу має бути відділена від назви блоку подвійним нижнім підкресленням __

2020-09-01 21:49 UTC, AndriiManyak commented on src/styles/main.scss
> +      margin-right: 20px;
Не треба збільшувати вкладеність коду і специфічніть селекторів

2020-09-01 21:49 UTC, AndriiManyak commented on src/styles/main.scss
> +$black-moyo-text: black;
змінні також краще винести в окремий scss файл та імпортувати в main.scss

2020-09-01 21:49 UTC, AndriiManyak commented on src/styles/main.scss
> +$black-moyo-text: black;
рекомендую в першу чергу імпортувати змінні та міксини

2020-09-01 21:49 UTC, AndriiManyak commented on src/styles/main.scss
> +          background-position: center;
```suggestion
          background: url(../images/star.svg) no-repeat center;
```

2020-09-02 08:48 UTC, andlap24 commented on src/styles/main.scss
> +      margin-right: 20px;
Тобто не стилізувати <li class="nav__item>, а тільки <a class="nav__link">?

2020-09-02 09:20 UTC, AndriiManyak commented on src/styles/main.scss
> +      margin-right: 20px;
Я мав на увазі, що в scss файлі, наприклад, .nav__item має бути вкладений у .nav, а не у .nav__list
Про це писалося у чеклисті https://github.com/mate-academy/layout_catalog/blob/master/checklist.md
Тобто, якщо в тебе селестор починається на .nav__, то він має бути вкладений конкретно у .nav

2020-09-02 09:29 UTC, andlap24 commented on src/styles/main.scss
> +      margin-right: 20px;
Зрозумів, все підправлю і перевірю ще раз. Дякую

2020-09-02 12:53 UTC, AndriiManyak approved these changes

2020-09-03 18:16 UTC, danheim requested changes

2020-09-03 18:16 UTC, danheim commented on src/styles/global-var.scss
> +$font-moyo: "Roboto", sans-serif;
font-family roboto а называется moyo? а если завтра поменяем название сайта на dojo?

2020-09-03 18:16 UTC, danheim commented on src/styles/global-var.scss
> +$black-moyo-text: black;
не привязывайся к названию moyo
писать $black-moyo-text намного дольше чем слово black, в чем смысл переменной

2020-09-03 18:16 UTC, danheim commented on src/styles/main.scss
> +    column-gap: 48px;
`gap: 50px 48px;`

2020-09-03 18:16 UTC, danheim commented on src/styles/main.scss
> +  .catalog {
это не часть блока main, вынеси

2020-09-03 18:16 UTC, danheim commented on src/styles/main.scss
> +  .card {
и это тоже, вынеси из main

2020-09-03 18:16 UTC, danheim commented on src/styles/main.scss
> +    .card__image {
используй амперсанд, исправь везде

2020-09-03 18:16 UTC, danheim commented on src/styles/main.scss
> +      }
это незасимый блок, вынеси из card

2020-09-04 07:51 UTC, andlap24 commented on src/styles/main.scss
> +      }
card > card__opinion > stars
мне точно выносить такие блоки?

2020-09-04 07:53 UTC, andlap24 commented on src/styles/global-var.scss
> +$black-moyo-text: black;
Да, глупые названия. Изменил.

2020-09-08 09:48 UTC, solaryasha requested changes

2020-09-08 09:48 UTC, solaryasha commented on src/styles/global-var.scss
> +$blue-color: #00acdc;
Назву змінної краще зробити астрактною, щоб не залежати від кольору.

2020-09-08 09:48 UTC, solaryasha commented on src/styles/header.scss
> +}
Навіщо тут вкладеність, якщо можна використати BEM ?
Або винеси його, якщо це блок по БЕМ-у.

2020-09-08 09:48 UTC, solaryasha commented on src/styles/header.scss
> +    &.is-active {
Зроби це модифікатором

2020-09-08 09:48 UTC, solaryasha commented on src/styles/main.scss
> +    .img {
Запиши це за допогою BEM методології.

2020-09-08 09:48 UTC, solaryasha commented on src/styles/main.scss
> +    .opinion__text {
Запиши це по BEM-у

2020-09-08 09:48 UTC, solaryasha commented on src/styles/main.scss
> +    }
BEM і тільки він.

2020-09-08 09:48 UTC, solaryasha commented on src/styles/main.scss
> +    .btn:hover {
Тут також запиши по BEM-у

2020-09-08 11:39 UTC, solaryasha requested changes

2020-09-08 11:39 UTC, solaryasha commented on src/index.html
> +            <a class="nav__link_is-active" href="#">Apple</a>
Модифікатор елемента без самого елемента.

2020-09-08 11:39 UTC, solaryasha commented on src/index.html
> +              >
```suggestion
            <a
              class="nav__link"
              data-qa="nav-hover"
              href="#"
            >
```

2020-09-08 11:39 UTC, solaryasha commented on src/index.html
> +              <div class="stars__item"></div>
Зроби так само як в завданні `Stars`, щоб в HTML-і можна змінювати кількість активних зірок.

2020-09-08 11:39 UTC, solaryasha commented on src/index.html
> +            <div class="card__opinion_text">
Якщо назва складається з двох або більше слів, давай їх писати через `-`.
Це для того щоб не плутати з модифікаторами

2020-09-08 12:54 UTC, andlap24 commented on src/index.html
> +            <div class="card__opinion_text">
Щось я намутив тут, надіюсь зараз мені вдалось все поправити.

2020-09-08 15:25 UTC, Vladimir-Beliy commented on src/styles/card.scss
> +  }
```suggestion
  &__price {
    display: flex;
    margin-top: 20px;
    justify-content: space-between;
    vertical-align: text-bottom;

      &__price-text {
      display: inline-block;
      margin-top: 5px;
      font-size: 11px;
    }
    
    &__price-price {
      font-size: 16px;
      font-weight: 500;
    }
не нужно делать двойную вложенность
```

2020-09-08 15:25 UTC, Vladimir-Beliy commented on src/styles/header.scss
> +    list-style: none;
в отдельный файл, каждый блок в отдельном файле

2020-09-08 17:02 UTC, andlap24 commented on src/styles/card.scss
> +  }
поправил везде

2020-09-08 17:03 UTC, andlap24 commented on src/styles/header.scss
> +    list-style: none;
вынес блок nav отдельно

2020-09-08 17:17 UTC, solaryasha approved these changes
Well done !

2026-02-15 13:12 UTC, closed without merging