Lesson 8, task 1 'Catalog' - Done!
mate-academy/layout_catalog pull request #552
Opened 2020-09-04 10:33 UTC by Atteroot

- [DEMO LINK](https://Atteroot.github.io/layout_catalog/)
- [TEST REPORT LINK](https://Atteroot.github.io/layout_catalog/report/html_report/)

2020-09-04 10:38 UTC, Atteroot commented
Локально тесты проходятся, на гите нет - странно

2020-09-04 13:48 UTC, Andrii1996 requested changes

2020-09-04 13:48 UTC, Andrii1996 commented on src/styles/card.scss
> +@import "variables.scss";
Я б казав імпортувати все в один файл

2020-09-04 13:48 UTC, Andrii1996 commented on src/styles/variables.scss
> +$padding: 50px;
називати коректніше зміну , типу paddingSmall як нижче , або paddingBig

2020-09-04 13:56 UTC, Atteroot commented on src/styles/card.scss
> +@import "variables.scss";
Ты имеешь ввиду импортировать все scss файлы сюда? Если да, то какой в этом смысл, если мне тут нужны только переменные?

2020-09-04 14:10 UTC, Atteroot commented on src/styles/variables.scss
> +$padding: 50px;
Удалил их совсем - нигде не использовались

2020-09-04 14:11 UTC, Andrii1996 commented on src/styles/card.scss
> +@import "variables.scss";
а якщо потім треба буде ще десь використати зміну , то будеш знов там імпортувати файл?

2020-09-04 14:20 UTC, Andrii1996 approved these changes

2020-09-04 14:22 UTC, Atteroot commented on src/styles/card.scss
> +@import "variables.scss";
Решено!

2020-09-08 10:36 UTC, solaryasha requested changes

2020-09-08 10:36 UTC, solaryasha commented on src/index.html
> +          class="header_icon"
Якщо це елемент, то `header__icon`

2020-09-08 10:36 UTC, solaryasha commented on src/index.html
> +            <div class="stars_star"></div>
Це елемент, тому `stars__star`

2020-09-08 10:36 UTC, solaryasha commented on src/styles/card.scss
> +  margin: 0 auto;
У BEM блока не може бути зовнішніх відступів.

2020-09-08 10:36 UTC, solaryasha commented on src/styles/header.scss
> +  &__link.is-active::after {
Зроби це модифікатором

2020-09-08 11:40 UTC, Atteroot commented on src/index.html
> +          class="header_icon"
Fixed!

2020-09-08 11:40 UTC, Atteroot commented on src/index.html
> +            <div class="stars_star"></div>
Fixed!

2020-09-08 11:40 UTC, Atteroot commented on src/styles/card.scss
> +  margin: 0 auto;
Fixed? (not sure)

2020-09-08 11:40 UTC, Atteroot commented on src/styles/header.scss
> +  &__link.is-active::after {
Fixed!

2020-09-08 11:44 UTC, Atteroot commented
https://prnt.sc/udlmlr
NPM тестам как-то совсем плохо, с третьего раза проходятся.

2020-09-08 15:31 UTC, solaryasha approved these changes

2020-09-08 15:31 UTC, solaryasha commented on src/styles/card.scss
> +    background-color: #00acdc;
Винеси колір в окрему змінну.

2020-09-08 15:31 UTC, solaryasha commented on src/styles/card.scss
> +    background-color: #fff;
Також краще винести в окрему змінну.

2020-09-08 15:31 UTC, solaryasha commented on src/styles/header.scss
> +    color: #000;
В окрему змінну.

2021-03-23 18:58 UTC, closed without merging