catalog transitions
mate-academy/layout_catalog pull request #562
Opened 2020-09-04 17:10 UTC by Andrii1996

[DEMO LINK](https://Andrii1996.github.io/layout_catalog/)
[TEST REPORT LINK](https://Andrii1996.github.io/layout_catalog/report/html_report/)

2020-09-04 18:03 UTC, yazheviks requested changes

2020-09-04 18:03 UTC, yazheviks commented on src/styles/card.scss
> +  }
у тебя картинка "прыгает" при наведении, попробуй убрать это

и бордеры не достают до бордеров карточки, поиграйся с паддингами

2020-09-05 18:56 UTC, Andrii1996 commented on src/styles/card.scss
> +  }
моє грання призводить до краху:)

2020-09-06 10:39 UTC, yazheviks commented on src/styles/card.scss
> +  }
ну смотри, картинка резко уменьшается, потому что у тебя стоит бордер-бокс, и ты резко добавляешь бордер 3px, то есть она резко уменьшается

без hover у самой картинки стоят только марджины, можно заменить их на падинги, но сделать так, чтобы при hover и без него сама картинка оставалась одного размера

играйся больше))

2020-09-06 11:56 UTC, yazheviks approved these changes
Cool!

2020-09-08 17:55 UTC, solaryasha requested changes
https://mateacademy.slack.com/archives/G018RCJTGH2/p1599576569209700

2020-09-08 18:40 UTC, closed without merging