added Catalog
mate-academy/layout_catalog pull request #599
Opened 2020-11-16 12:25 UTC by MarchD

- [DEMO LINK](https://MarchD.github.io/layout_catalog/)
- [TEST REPORT LINK](https://MarchD.github.io/layout_catalog/report/html_report/)

2020-11-18 13:47 UTC, troospieler requested changes
все отлично! я правда нигде не смог найти переменную $color. и в целом замечания по BEM и пустым строкам это уже к менторам)

2020-11-18 13:47 UTC, troospieler commented on src/index.html
> +
мне всегда говорили удалять комменты из кода, но в этом доке они смысловые, по этому думаю что все ок. решил все же указать).

2020-11-18 13:47 UTC, troospieler commented on src/index.html
> +          <li class="nav__item">
по BEM - я не знаю как точно, но мне кажется, что раз у нас nav внутри header, то стоит ему указать и .nav__header и .nav. но это не точно))

2020-11-18 13:47 UTC, troospieler commented on src/index.html
> +            <p class="card__article">
на счет отступов (пустых/разделяющих строк) от каждого элемента - не совсем уверен, сам код вроде не большой , может там не нужно таких отступов (пустых строк)

2020-11-18 13:47 UTC, troospieler commented on src/index.html
> +                <div class="stars__img"></div>
опять же по BEM - на счет названия классов я не уверен что это правильный вариант. может будет лучше .card__stars, и .stars, и .stars--4 шоб работал цикл.

2020-11-18 13:47 UTC, troospieler commented on src/styles/variables.scss
> +
не знаю есть ли смысл задавать эти цвета именно в переменные, так как это просто черный и просто белый, а не оттенки.

2020-11-18 14:20 UTC, MarchD commented on src/styles/variables.scss
> +
ну мы это обсудили. Я решила так сделать на случай, а вдруг кто-то захочет сделать главным черным какой-то 
`#343233` такой цвет, а тут оп и везде поменял

2020-11-18 14:22 UTC, MarchD commented on src/index.html
> +          <li class="nav__item">
Исправила в других местах, правда для звёзд я не задавала класс дополнительный, так как все доп стили, которые к ним применяются, не влияют на взаимодействие этого блока с другими блоками и элементами (нет марджинов и тд)

2020-11-18 14:23 UTC, MarchD commented on src/index.html
> +
комменты удалила

2020-11-18 14:24 UTC, MarchD commented on src/index.html
> +            <p class="card__article">
тут посмотрим, пока мне замечаний не делали, а мне с такой разбивкой удобнее путешествовать по коду:)

2020-11-19 12:11 UTC, aionova requested changes
Отличная работа! Исправь замечания и будет огонь)

2020-11-19 12:11 UTC, aionova commented on src/styles/button.scss
> +    @include border($blue);
Не меняй на ховер весь бордер, меняй только цвет, а бордер задай прозрачный в .button

2020-11-19 12:11 UTC, aionova commented on src/styles/button.scss
> +  transition: color 0.5s, background-color 0.5s, border 1s;
```suggestion
  transition: color 0.5s, background-color 0.5s, border-color 1s;
```

2020-11-19 12:11 UTC, aionova commented on src/styles/header.scss
> +  margin: 0 auto 50px;
Не задавай марджины бем-блоку

2020-11-19 12:11 UTC, aionova commented on src/styles/header.scss
> +}
```suggestion
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.05);
  
  &__logo {
  margin: auto 50px;
}
}
```
Используй вложенность

2020-11-19 12:11 UTC, aionova commented on src/styles/navigation.scss
> +}
Все стили элементов блока header должны быть в файле header

2020-11-19 12:11 UTC, aionova commented on src/styles/navigation.scss
> +  color: $blue;
Вынеси is-active за блок header, чтобы не повышать специфичность. В блоке вложенность делай только через &

2020-11-19 12:22 UTC, MarchD commented on src/styles/button.scss
> +    @include border($blue);
забыла сюда подтянуть  :)) исправляюсь

2020-11-20 09:13 UTC, aionova approved these changes
Awesome!

2024-01-08 06:51 UTC, closed without merging