catalog solution
mate-academy/layout_catalog pull request #663
Opened 2021-01-19 14:01 UTC by yashnyi

- [DEMO LINK](https://yashnyi.github.io/layout_catalog/)
- [TEST REPORT LINK](https://yashnyi.github.io/layout_catalog/report/html_report/)

2021-01-21 19:45 UTC, Jastler commented
Вроде все курто!)

2021-01-21 20:00 UTC, yurasokal approved these changes
lgtm !

2021-01-22 07:50 UTC, yashnyi commented on src/styles/stars.scss
> +.stars--4 .stars__star:nth-child(-n+4) {
По суті, .stars--5 і т.д. теж є модифікаторами. Як на мене, краще додавати в html 1 модифікатор, який буде робити зірочки активними, ніж додавати 1-5 класів до кожної зірочки з --active.

2021-01-22 07:50 UTC, yashnyi commented on src/styles/main.scss
> +@import url("https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap");
Дякую!

2021-01-22 09:56 UTC, Vladimir-Beliy requested changes

2021-01-22 09:56 UTC, Vladimir-Beliy commented on src/styles/main.scss
> +}
reset-css https://www.npmjs.com/package/reset-css

2021-01-22 09:56 UTC, Vladimir-Beliy commented on src/styles/product.scss
> +  & > * {
```
  & > * {
```
так делать не нужно, это не по БЭМ и выглядит странно

2021-01-22 09:56 UTC, Vladimir-Beliy commented on src/styles/product.scss
> +  &-card {
```
  &-card {
```
это отдельный блок, модификатор или элемент?

2021-01-25 10:42 UTC, solaryasha approved these changes
Хороша робота, залишив невеличкі зауваження.

2021-01-25 10:42 UTC, solaryasha commented on src/index.html
> +              class="nav__link is-active">Apple
Краще переносити текст на новий рядок, так його простіше читати
```suggestion
              class="nav__link is-active">
                Apple
```

2021-01-25 10:42 UTC, solaryasha commented on src/index.html
> +          </a>
```suggestion
          <a 
             href="#"
             class="button"
             data-qa="card-hover"
           >
             Купить
          </a>
```

2021-01-25 10:42 UTC, solaryasha commented on src/styles/header.scss
> +  margin-bottom: 50px;
https://mateacademy.slack.com/archives/G01HVTAUW92/p1611568819299500

2025-09-01 20:49 UTC, closed without merging