catalog
mate-academy/layout_catalog pull request #766
Opened 2021-04-01 19:35 UTC by Andriykooo

- [DEMO LINK](https://Andriykooo.github.io/layout_catalog/)
- [TEST REPORT LINK](https://Andriykooo.github.io/layout_catalog/report/html_report/)

2021-04-02 09:13 UTC, rauzok commented
[DEMO LINK](https://andriykooo.github.io/layout_catalog/index.html)
В каталозі в 7 карточка із 8 зірки не активні, не відповідає шаблону

2021-04-02 09:23 UTC, rauzok requested changes
Поправ зірочки в картках, щоб всі виглядали як по дизайну, а все інше на твій розгляд!

2021-04-02 09:23 UTC, rauzok commented on src/index.html
> +            </div>
Можливо тут замість **div** варто було використати **span** через те, що це текст.
Так само в усіх картках!

2021-04-02 09:23 UTC, rauzok commented on src/index.html
> +            </div>
Можливо тут замість **div** варто було використати **span** через те, що це текст.
Так само в усіх картках!

2021-04-02 09:23 UTC, rauzok commented on src/styles/blocks/card.scss
> +    margin-top: 0;
```suggestion
```
Це по стандарту буде і так 0;

2021-04-02 09:23 UTC, rauzok commented on src/styles/blocks/card.scss
> +    width: 170px;
```suggestion
    width: 100%;

```
Якщо зміниться ширина карточки, то в тебе кнопка не розтягнеться.

2021-04-02 09:23 UTC, rauzok commented on src/styles/utlis/variables.scss
> +$blue-color: #00acdc;
Назва перемінної погано задана, що буде як колір зміниться на червоний?
**$blue-color: red;** - колір то червоний, а перемінна то **$blue-color** - не відповідає дійсності.

2021-04-02 11:21 UTC, rauzok approved these changes

2021-04-02 15:57 UTC, vsm2k17 requested changes
![image](https://user-images.githubusercontent.com/35385361/113431773-f0fef780-93e4-11eb-9760-d261a95a3f9e.png)
якось не красиво виглядає, давай зробим щоб було 2 ряди по чотири карти як в дизайні і на великих екранах вигляд не змінювався


![image](https://user-images.githubusercontent.com/35385361/113431913-23a8f000-93e5-11eb-8f8a-408613718c4c.png)
давай замість цього додамо на карточку клас catalog__card

2021-04-05 08:40 UTC, mgrinko requested changes
Разобрали на уроке

2021-04-06 07:01 UTC, aionova approved these changes
Great!

2022-09-21 14:53 UTC, closed without merging